/**
 * De Pentecostés a la separación con Roma.
 *
 * Los siete Concilios Ecuménicos llevan ficha completa: son las junturas
 * sobre las que se articula todo lo demás.
 */
import type { HistoryPeriod } from './history';

export const EARLY_PERIODS: HistoryPeriod[] = [
  /* ═════════════════ 1. Los orígenes ═════════════════ */
  {
    id: 'origenes',
    title: 'Los orígenes',
    range: 'c. 33 – 313',
    summary: [
      'La Iglesia empieza en una habitación de Jerusalén el día de Pentecostés, cuando unos ciento veinte judíos reciben el Espíritu Santo y salen a predicar que un ajusticiado ha resucitado. En menos de una generación hay comunidades en Antioquía, Éfeso, Corinto, Alejandría y Roma.',
      'Durante casi tres siglos es una religión ilegal. Las persecuciones no son continuas —hay décadas enteras de calma—, pero cuando llegan son brutales, y de ellas sale el rasgo que marcará para siempre a la Iglesia oriental: la veneración de los mártires, cuyas tumbas se convierten en altares. De ahí viene que todavía hoy no se consagre una iglesia sin reliquias.',
      'En este periodo se fija el canon del Nuevo Testamento por uso, no por decreto; aparece la estructura de obispo, presbíteros y diáconos que san Ignacio de Antioquía ya da por normal hacia el año 107; y se libran las primeras grandes discusiones: contra el gnosticismo, contra Marción y sobre cuándo celebrar la Pascua.',
    ],
    events: [
      { id: 'pentecostes', year: 'c. 33', sort: 33, title: 'Pentecostés', kind: 'liturgia',
        detail: 'Cincuenta días después de la Pascua, el Espíritu Santo desciende sobre los apóstoles reunidos en Jerusalén. La Iglesia considera este día su nacimiento, y no el de la predicación de Jesús: lo que empieza aquí es el cuerpo, no la enseñanza.' },
      { id: 'esteban', year: 'c. 34', sort: 34, title: 'Martirio de san Esteban', kind: 'persecucion',
        detail: 'El primero que muere por Cristo, lapidado ante la mirada de un joven llamado Saulo. Muere pidiendo perdón para quienes lo matan.',
        seeAlso: [{ label: 'San Esteban Protomártir', path: '/calendario/santos/esteban-protomartir' }] },
      { id: 'pablo-damasco', year: 'c. 36', sort: 36, title: 'Conversión de san Pablo', kind: 'figura' },
      { id: 'antioquia-cristianos', year: 'c. 43', sort: 43, title: 'En Antioquía se les llama cristianos por primera vez', kind: 'mision' },
      { id: 'concilio-jerusalen', year: 'c. 49', sort: 49, title: 'Concilio de Jerusalén', kind: 'concilio',
        detail: 'Los apóstoles deciden que los gentiles que entren en la Iglesia no tienen que hacerse judíos primero. Es la primera vez que la Iglesia resuelve un conflicto reuniéndose, y el modelo de todo lo que vendrá después: se delibera y se concluye «hemos decidido el Espíritu Santo y nosotros».' },
      { id: 'pedro-pablo-roma', year: 'c. 64-67', sort: 64, title: 'Martirio de Pedro y Pablo en Roma', kind: 'persecucion' },
      { id: 'jerusalen-70', year: '70', sort: 70, title: 'Destrucción del Templo de Jerusalén', kind: 'politico',
        detail: 'Roma arrasa el Templo. La Iglesia, que ya se había apartado de la ciudad, deja de tener a Jerusalén por centro y pasa a ser una red de comunidades urbanas por todo el Mediterráneo.' },
      { id: 'ignacio-antioquia', year: 'c. 107', sort: 107, title: 'Martirio de san Ignacio de Antioquía', kind: 'persecucion',
        detail: 'Camino de Roma para morir en el circo, escribe siete cartas donde aparece por primera vez la palabra «católica» aplicada a la Iglesia, y donde ya se describe la estructura de un obispo con sus presbíteros y diáconos como algo normal.',
        seeAlso: [{ label: 'San Ignacio de Antioquía', path: '/calendario/santos/ignacio-antioquia-dic' }] },
      { id: 'policarpo', year: '155', sort: 155, title: 'Martirio de san Policarpo de Esmirna', kind: 'persecucion',
        detail: 'Discípulo del apóstol Juan. En la hoguera responde a quien le pide renegar: «Ochenta y seis años le sirvo, y ningún mal me ha hecho». Su martirio es la primera acta martirial que se conserva.',
        seeAlso: [{ label: 'San Policarpo', path: '/calendario/santos/policarpo-esmirna' }] },
      { id: 'ireneo', year: 'c. 180', sort: 180, title: 'San Ireneo escribe «Contra las herejías»', kind: 'obra',
        detail: 'Contra el gnosticismo, opone el criterio que se volverá decisivo: la fe verdadera es la que las Iglesias fundadas por los apóstoles han transmitido públicamente, no un saber secreto reservado a unos pocos.' },
      { id: 'origenes-alejandria', year: 'c. 230', sort: 230, title: 'Orígenes y la escuela de Alejandría', kind: 'figura',
        detail: 'El primer gran exegeta cristiano y el más discutido. Su método alegórico marcó toda la interpretación posterior de la Escritura; algunas de sus tesis fueron condenadas tres siglos después de su muerte.' },
      { id: 'persecucion-decio', year: '250', sort: 250, title: 'Persecución de Decio', kind: 'persecucion',
        detail: 'La primera persecución sistemática en todo el imperio: se exige a cada ciudadano un certificado de haber sacrificado a los dioses. Deja tras de sí el problema de los lapsi, los que cedieron, y la discusión sobre si se les readmite. La Iglesia decide que sí, con penitencia.' },
      { id: 'antonio-desierto', year: 'c. 270', sort: 270, title: 'San Antonio se retira al desierto', kind: 'figura',
        detail: 'Nace el monacato. No es una huida del mundo sino un combate a cara descubierta, y en pocas décadas el desierto egipcio está poblado de miles de monjes.' },
      { id: 'persecucion-diocleciano', year: '303-311', sort: 303, title: 'La Gran Persecución de Diocleciano', kind: 'persecucion',
        detail: 'La última y la peor: se destruyen iglesias, se queman las Escrituras y se ejecuta al clero. De ella salen san Jorge, san Demetrio, santa Bárbara y la mayor parte de los grandes mártires que la Iglesia sigue conmemorando.' },
    ],
  },

  /* ═════════════════ 2. El siglo de los concilios ═════════════════ */
  {
    id: 'concilios',
    title: 'El siglo de los concilios',
    range: '313 – 451',
    summary: [
      'En 313 el Edicto de Milán da libertad a los cristianos, y en menos de un siglo la religión perseguida es la del imperio. El cambio trae misiones, basílicas y liturgia pública; también obispos cortesanos y emperadores que se creen con derecho a decidir sobre la fe.',
      'Y trae las grandes discusiones. Con la libertad, lo que antes se resolvía dentro de cada comunidad se convierte en un asunto imperial, y para zanjarlo se inventa el Concilio Ecuménico: obispos de todo el mundo reunidos para decir qué cree la Iglesia. Cuatro de los siete se celebran en este periodo.',
      'Es también el siglo de los grandes Padres: Atanasio, los tres capadocios, Juan Crisóstomo, Cirilo de Alejandría. Casi todo el vocabulario con el que la Iglesia habla de Dios se fija aquí.',
    ],
    events: [
      { id: 'edicto-milan', year: '313', sort: 313, title: 'Edicto de Milán', kind: 'politico',
        detail: 'Constantino y Licinio conceden libertad de culto. No hace cristiano al imperio —eso llegará en 380—, pero termina con tres siglos de ilegalidad.' },
      { id: 'nicea-i', year: '325', sort: 325, title: 'I Concilio Ecuménico · Nicea', kind: 'concilio',
        council: { number: 1, place: 'Nicea, Bitinia', year: '325', convokedBy: 'El emperador Constantino',
          attendees: 'Unos 318 obispos, casi todos de Oriente',
          against: 'El arrianismo: la enseñanza de Arrio de que el Hijo es la primera y más excelsa de las criaturas, y que «hubo un tiempo en que no era».',
          defined: ['El Hijo es consustancial al Padre —homooúsios—, engendrado y no creado.',
            'Las primeras dos terceras partes del Credo que todavía se recita.',
            'La fecha común de la Pascua, desligada del cómputo judío.',
            'Veinte cánones disciplinares.'],
          note: 'La palabra homooúsios no está en la Escritura, y eso escandalizó a muchos obispos. Se aceptó porque era la única que Arrio no podía firmar.' },
        detail: 'El primer concilio de toda la Iglesia. Lo convoca un emperador que aún no está bautizado, para resolver una disputa que estaba partiendo Egipto. Lo que se juega no es una sutileza: si el Hijo es criatura, no nos ha unido a Dios.',
        seeAlso: [{ label: 'San Atanasio', path: '/biblioteca/padres/atanasio' }] },
      { id: 'arrianismo-despues', year: '325-381', sort: 326, title: 'Medio siglo de crisis arriana', kind: 'cisma',
        detail: 'Nicea no zanja nada. Durante cincuenta años el arrianismo domina buena parte del episcopado con el apoyo de varios emperadores, y Atanasio pasa diecisiete años desterrado. Es el periodo que dio la expresión «Athanasius contra mundum».' },
      { id: 'basilio-cesarea', year: '370-379', sort: 370, title: 'San Basilio, arzobispo de Cesarea', kind: 'figura',
        seeAlso: [{ label: 'San Basilio el Grande', path: '/biblioteca/padres/basilio-magno' }] },
      { id: 'cristianismo-oficial', year: '380', sort: 380, title: 'El cristianismo, religión oficial del imperio', kind: 'politico' },
      { id: 'constantinopla-i', year: '381', sort: 381, title: 'II Concilio Ecuménico · Constantinopla', kind: 'concilio',
        council: { number: 2, place: 'Constantinopla', year: '381', convokedBy: 'El emperador Teodosio I',
          attendees: 'Unos 150 obispos, todos orientales',
          against: 'Los pneumatómacos o macedonianos, que aceptaban la divinidad del Hijo pero tenían al Espíritu Santo por criatura.',
          defined: ['El Espíritu Santo es Señor y dador de vida, procede del Padre y con el Padre y el Hijo recibe una misma adoración.',
            'El texto del Credo tal como se recita hoy, completado.',
            'Constantinopla tiene el primado de honor después de Roma, por ser la nueva capital.'],
          note: 'El artículo sobre el Espíritu es el que Occidente modificará siglos después con el Filioque. El canon sobre Constantinopla fue rechazado por Roma.' },
        detail: 'Preside san Gregorio Nacianceno, que llevaba dos años predicando en una capilla diminuta ante una ciudad entera arriana. Sus cinco Discursos teológicos son el trasfondo de lo que aquí se define.',
        seeAlso: [{ label: 'San Gregorio Nacianceno', path: '/biblioteca/padres/gregorio-nacianceno' }] },
      { id: 'crisostomo-constantinopla', year: '398-404', sort: 398, title: 'San Juan Crisóstomo, arzobispo de Constantinopla', kind: 'figura',
        detail: 'Llevado casi por la fuerza a la sede imperial, choca con la corte al denunciar el lujo. Desterrado dos veces, muere camino del exilio en 407.',
        seeAlso: [{ label: 'San Juan Crisóstomo', path: '/biblioteca/padres/juan-crisostomo' }] },
      { id: 'efeso', year: '431', sort: 431, title: 'III Concilio Ecuménico · Éfeso', kind: 'concilio',
        council: { number: 3, place: 'Éfeso', year: '431', convokedBy: 'El emperador Teodosio II',
          attendees: 'Unos 200 obispos',
          against: 'Nestorio, patriarca de Constantinopla, que se negaba a llamar Theotokos —Madre de Dios— a María, prefiriendo «Madre de Cristo», porque en su planteamiento las dos naturalezas quedaban demasiado separadas.',
          defined: ['María es Theotokos, la que dio a luz a Dios.',
            'En Cristo hay una sola persona, no dos sujetos yuxtapuestos.'],
          note: 'El título es una afirmación sobre el Hijo antes que sobre la Madre: si lo que nació de ella era Dios, la unión de las naturalezas es real desde el primer instante. De este concilio nace la primera separación duradera: las Iglesias del Oriente —llamadas nestorianas— no lo aceptan.' } },
      { id: 'calcedonia', year: '451', sort: 451, title: 'IV Concilio Ecuménico · Calcedonia', kind: 'concilio',
        council: { number: 4, place: 'Calcedonia', year: '451', convokedBy: 'El emperador Marciano',
          attendees: 'Unos 520 obispos, el más numeroso de los siete',
          against: 'El monofisismo de Eutiques: que tras la encarnación en Cristo hay una sola naturaleza, absorbida la humana por la divina.',
          defined: ['Cristo es reconocido en dos naturalezas, sin confusión, sin cambio, sin división y sin separación.',
            'Las dos naturalezas concurren en una sola persona y una sola hipóstasis.',
            'Constantinopla recibe privilegios iguales a los de Roma (canon 28).'],
          note: 'La fórmula de las cuatro negaciones sigue siendo la definición cristológica de referencia. Pero el concilio abre la segunda gran ruptura: las Iglesias copta, siria, armenia y etíope no lo aceptan y se separan hasta hoy. Los diálogos del siglo XX han concluido que buena parte de la diferencia era de vocabulario, aunque la comunión no se ha restablecido.' },
        disputed: 'Las llamadas Iglesias ortodoxas orientales —copta, armenia, siria, etíope, eritrea, malankar— rechazan Calcedonia y no están en comunión con la Iglesia ortodoxa, aunque hoy se reconoce que ambas confiesan la misma fe cristológica con lenguajes distintos.' },
    ],
  },

  /* ═════════════════ 3. Bizancio ═════════════════ */
  {
    id: 'bizancio',
    title: 'Bizancio',
    range: '451 – 843',
    summary: [
      'Cuatro siglos en los que el imperio de Oriente se convierte en algo sin precedente: un estado que se entiende a sí mismo como el brazo terreno de la Iglesia. Se levanta Santa Sofía, se fija la Liturgia que todavía se celebra y se escribe casi toda la himnografía que se canta.',
      'Es también el periodo en que Oriente pierde la mitad de su territorio. La irrupción del islam en el siglo VII arrebata Siria, Palestina y Egipto —tres de los cinco patriarcados— en menos de veinte años. Alejandría, Antioquía y Jerusalén quedan bajo dominio musulmán y ahí siguen.',
      'Y es el periodo de las dos últimas grandes crisis doctrinales: el monotelismo, que san Máximo el Confesor combate solo y por el que le cortan la lengua y la mano, y la iconoclastia, que dura más de un siglo y termina con el triunfo de los iconos que la Iglesia celebra cada primer domingo de Cuaresma.',
    ],
    events: [
      { id: 'benito-occidente', year: 'c. 529', sort: 529, title: 'San Benito funda Montecasino', kind: 'figura',
        detail: 'En Occidente. Su Regla, que bebe de la de san Basilio, ordenará el monacato latino como las de Basilio ordenaron el oriental.' },
      { id: 'santa-sofia', year: '537', sort: 537, title: 'Se consagra Santa Sofía', kind: 'liturgia',
        detail: 'Justiniano levanta en cinco años la iglesia más grande de la cristiandad, con una cúpula que nadie sabía construir. La tradición le atribuye la frase al entrar: «Salomón, te he vencido».' },
      { id: 'constantinopla-ii', year: '553', sort: 553, title: 'V Concilio Ecuménico · Constantinopla II', kind: 'concilio',
        council: { number: 5, place: 'Constantinopla', year: '553', convokedBy: 'El emperador Justiniano I',
          attendees: 'Unos 165 obispos',
          against: 'Los llamados Tres Capítulos, escritos de tendencia nestoriana, y ciertas tesis atribuidas a Orígenes.',
          defined: ['Condena de los Tres Capítulos.', 'Condena del origenismo, incluida la preexistencia de las almas y la apocatástasis.',
            'Reafirmación de Calcedonia interpretada en clave cirilina.'],
          note: 'Fue un intento de recuperar a los monofisitas mostrando que Calcedonia no era nestoriana. No lo consiguió: la ruptura siguió.' } },
      { id: 'islam', year: '634-698', sort: 634, title: 'La expansión del islam', kind: 'politico',
        detail: 'En pocas décadas Siria, Palestina, Egipto y el norte de África pasan a dominio musulmán. Tres de los cinco patriarcados antiguos quedan fuera del imperio cristiano. San Sofronio de Jerusalén entrega la ciudad al califa Omar en 638 y negocia que los cristianos puedan seguir viviendo en ella.' },
      { id: 'maximo-confesor', year: '649-662', sort: 649, title: 'San Máximo el Confesor y el monotelismo', kind: 'figura',
        detail: 'El imperio propone que en Cristo hay una sola voluntad, como fórmula de paz con los monofisitas. Máximo, monje sin cargo, se opone solo frente al emperador y al patriarca. Le cortan la lengua y la mano derecha para que no pueda hablar ni escribir. Muere en el destierro en 662.',
        seeAlso: [{ label: 'San Máximo el Confesor', path: '/biblioteca/padres/maximo-confesor' }] },
      { id: 'constantinopla-iii', year: '680-681', sort: 680, title: 'VI Concilio Ecuménico · Constantinopla III', kind: 'concilio',
        council: { number: 6, place: 'Constantinopla', year: '680-681', convokedBy: 'El emperador Constantino IV',
          attendees: 'Unos 170 obispos',
          against: 'El monotelismo: que en Cristo hay una sola voluntad y una sola operación.',
          defined: ['En Cristo hay dos voluntades y dos operaciones naturales, divina y humana, sin división ni oposición.',
            'La voluntad humana de Cristo sigue a la divina sin resistirse, pero es real y suya.'],
          note: 'Da la razón, palabra por palabra, a san Máximo el Confesor, muerto en el destierro diecinueve años antes. Condena también póstumamente al papa Honorio por su ambigüedad en el asunto.' } },
      { id: 'trullo', year: '691-692', sort: 691, title: 'Concilio Quinisexto (in Trullo)', kind: 'concilio',
        council: { place: 'Constantinopla, sala de la cúpula', year: '691-692', convokedBy: 'El emperador Justiniano II',
          against: 'No una herejía: la falta de cánones disciplinares en los dos concilios anteriores, que sólo habían tratado doctrina.',
          defined: ['102 cánones sobre disciplina, clero, matrimonio de sacerdotes, ayunos e iconografía.',
            'Prohibición de representar a Cristo como cordero: debe pintarse con figura humana.'],
          note: 'No es un concilio ecuménico por sí mismo: se considera complemento del V y del VI, y de ahí su nombre. Roma nunca lo aceptó del todo, y varios de sus cánones marcan diferencias disciplinares con Occidente que duran hasta hoy, como el matrimonio del clero.' } },
      { id: 'iconoclastia-i', year: '726-787', sort: 726, title: 'Primera iconoclastia', kind: 'cisma',
        detail: 'El emperador León III ordena retirar los iconos. La razón declarada es la idolatría; pesan también la presión del islam y la voluntad imperial de someter a los monasterios, que son el principal foco de resistencia. Miles de monjes son perseguidos.' },
      { id: 'damasceno-iconos', year: 'c. 730', sort: 730, title: 'San Juan Damasceno defiende los iconos', kind: 'obra',
        detail: 'Escribe sus tres discursos desde Palestina, bajo dominio musulmán y fuera del alcance del emperador. Su argumento zanja la cuestión: desde que Dios se hizo hombre, tiene rostro y puede pintarse.',
        seeAlso: [{ label: 'San Juan Damasceno', path: '/biblioteca/padres/juan-damasceno' }] },
      { id: 'nicea-ii', year: '787', sort: 787, title: 'VII Concilio Ecuménico · Nicea II', kind: 'concilio',
        council: { number: 7, place: 'Nicea', year: '787', convokedBy: 'La emperatriz Irene y el patriarca Tarasio',
          attendees: 'Unos 350 obispos',
          against: 'La iconoclastia: la destrucción de las imágenes sagradas y la enseñanza de que venerarlas es idolatría.',
          defined: ['Los iconos de Cristo, la Theotokos, los ángeles y los santos deben exponerse y venerarse.',
            'La veneración —proskýnesis— pasa a la persona representada; la adoración —latría— sólo se debe a Dios.',
            'Quien venera el icono venera a quien está pintado en él.'],
          note: 'El último de los siete. Su definición se apoya directamente en la encarnación: negar el icono equivale a negar que Dios se hizo visible. La versión latina que llegó a Carlomagno estaba mal traducida y confundía veneración con adoración, lo que produjo un rechazo franco que tardó en corregirse.' } },
      { id: 'iconoclastia-ii', year: '815-843', sort: 815, title: 'Segunda iconoclastia', kind: 'cisma' },
      { id: 'triunfo-ortodoxia', year: '843', sort: 843, title: 'El Triunfo de la Ortodoxia', kind: 'liturgia',
        detail: 'La emperatriz Teodora restablece definitivamente los iconos. La Iglesia lo celebra cada primer domingo de Gran Cuaresma con una procesión de imágenes: no es la fiesta de una obra de arte, sino de la encarnación.' },
    ],
  },
];
