/**
 * La Divina Liturgia de san Juan Crisóstomo, entera.
 *
 * Hasta la versión 1.25 ATHOS tenía de la Liturgia la estructura y lo que
 * canta el pueblo, y decía «sigue la oración de la Anáfora» donde el
 * sacerdote reza en voz baja. Ahora está todo: las letanías completas, las
 * oraciones de las antífonas, de la entrada, del Trisagio y del Evangelio, las
 * de los catecúmenos y de los fieles, la del Querúbico, la Anáfora entera con
 * la epíclesis y las conmemoraciones, las oraciones de la comunión y la
 * despedida.
 *
 * Se ha traducido del Hieratikón griego, en la edición digital de la
 * Archidiócesis Ortodoxa Griega de América (glt.goarch.org), que es la de la
 * Liturgia de cada día. Lo que allí no va escrito porque lo sabe todo el que
 * celebra —quién dice cada cosa— se indica en las rúbricas. Las lecturas no
 * se copian: son las del día, y están en Inicio y en el Calendario.
 *
 * La traducción es de ATHOS y no procede de ningún libro litúrgico español
 * publicado. Las oraciones del sacerdote se dan para que el fiel sepa qué se
 * está rezando en el altar mientras él canta, no para sustituir al
 * Hieratikón de quien celebra.
 */
import type { OfficeSection, TextBlock } from '@/types';

const t = (content: string): TextBlock => ({ kind: 'text', content });
const rub = (content: string): TextBlock => ({ kind: 'rubric', content });
const ref = (content: string): TextBlock => ({ kind: 'refrain', content });
const head = (content: string): TextBlock => ({ kind: 'heading', content });
const section = (
  id: string,
  title: string,
  blocks: TextBlock[],
  voice?: OfficeSection['voice'],
): OfficeSection => ({ id, title, blocks, voice });

const AMEN = ref('Amén.');
const SENOR = ref('Señor, ten piedad.');
const Y_CON_TU_ESPIRITU = ref('Y con tu espíritu.');
const POR_LOS_SIGLOS = 'ahora y siempre, y por los siglos de los siglos.';

/** El final de la pequeña letanía, que se repite entero varias veces. */
const PEQUENA_LETANIA: TextBlock[] = [
  rub('Diácono:'),
  t('Una y otra vez, en paz, oremos al Señor.'),
  SENOR,
  t('Socórrenos, sálvanos, ten piedad de nosotros y guárdanos, oh Dios, por tu gracia.'),
  SENOR,
  t('Conmemorando a nuestra santísima, purísima, bendita sobre todas y gloriosa Señora, la Theotokos y siempre Virgen María, junto con todos los santos, encomendémonos a nosotros mismos, unos a otros, y toda nuestra vida a Cristo Dios.'),
  ref('A Ti, Señor.'),
];

/** Las peticiones que piden al Señor, con las que se cierran dos letanías. */
const PETICIONES: TextBlock[] = [
  t('Pidamos al Señor que todo el día sea perfecto, santo, pacífico y sin pecado.'),
  ref('Concédelo, Señor.'),
  t('Pidamos al Señor un ángel de paz, guía fiel y guardián de nuestras almas y de nuestros cuerpos.'),
  ref('Concédelo, Señor.'),
  t('Pidamos al Señor el perdón y la remisión de nuestros pecados y de nuestras faltas.'),
  ref('Concédelo, Señor.'),
  t('Pidamos al Señor lo que es bueno y provechoso para nuestras almas, y la paz para el mundo.'),
  ref('Concédelo, Señor.'),
  t('Pidamos al Señor acabar en paz y en arrepentimiento el tiempo que nos queda de vida.'),
  ref('Concédelo, Señor.'),
  t('Pidamos un final de nuestra vida cristiano, sin dolor, sin vergüenza y en paz, y una buena defensa ante el temible tribunal de Cristo.'),
  ref('Concédelo, Señor.'),
];

export const LITURGIA_CRISOSTOMO: OfficeSection[] = [
  section('antes-de-empezar', 'Antes de empezar', [
    rub('Terminada la proscomidia, el sacerdote inciensa el altar y el templo. Después, ante el altar, el sacerdote y el diácono dicen en voz baja:'),
    t('Rey celestial, Consolador, Espíritu de la verdad, que estás en todo lugar y todo lo llenas, tesoro de bienes y dador de vida: ven y habita en nosotros, purifícanos de toda mancha y salva, oh Bueno, nuestras almas.'),
    { kind: 'text', content: 'Gloria a Dios en las alturas, y en la tierra paz, buena voluntad entre los hombres.', times: 3 },
    { kind: 'text', content: 'Señor, abre mis labios, y mi boca proclamará tu alabanza.', times: 2 },
    rub('El diácono, inclinándose ante el sacerdote:'),
    t('Es tiempo de obrar para el Señor. Bendice, santo señor.'),
    rub('El sacerdote lo bendice:'),
    t(`Bendito sea nuestro Dios, siempre, ${POR_LOS_SIGLOS}`),
    rub('Diácono:'),
    t('Ruega por mí, santo señor.'),
    rub('Sacerdote:'),
    t('Que el Señor dirija tus pasos a toda obra buena.'),
    rub('Diácono:'),
    t('Acuérdate de mí, santo señor.'),
    rub('Sacerdote:'),
    t(`Que el Señor Dios se acuerde de ti en su Reino, siempre, ${POR_LOS_SIGLOS}`),
    rub('El diácono sale del santuario, se pone en su sitio ante las puertas santas y dice:'),
    t('Bendice, señor.'),
  ], 'sacerdote'),

  section('bendicion-inicial', 'Bendición inicial', [
    rub('Sacerdote, en voz alta, trazando la señal de la cruz con el Evangeliario sobre el altar:'),
    t(`Bendito sea el Reino del Padre, y del Hijo, y del Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    rub('Es la primera palabra de la Liturgia, y no es una petición: es una proclamación. El Reino que se espera al final de los tiempos se hace presente aquí, ahora, en la asamblea.'),
  ]),

  section('gran-letania', 'Gran Letanía de la Paz', [
    rub('Diácono; el coro responde «Señor, ten piedad» a cada petición:'),
    t('En paz, oremos al Señor.'),
    t('Por la paz de lo alto y por la salvación de nuestras almas, oremos al Señor.'),
    t('Por la paz del mundo entero, por la estabilidad de las santas Iglesias de Dios y por la unión de todos, oremos al Señor.'),
    t('Por esta santa casa y por los que entran en ella con fe, piedad y temor de Dios, oremos al Señor.'),
    t('Por los cristianos piadosos y ortodoxos, oremos al Señor.'),
    t('Por nuestro arzobispo N., por el venerable presbiterio, por el diaconado en Cristo, por todo el clero y el pueblo, oremos al Señor.'),
    t('Por nuestro país, por sus autoridades y por todos los que lo protegen, oremos al Señor.'),
    t('Por esta ciudad, por toda ciudad y región, y por los que viven en ellas con fe, oremos al Señor.'),
    t('Por un clima benigno, por la abundancia de los frutos de la tierra y por tiempos de paz, oremos al Señor.'),
    t('Por los que navegan, los que viajan, los enfermos, los que sufren, los cautivos, y por su salvación, oremos al Señor.'),
    t('Por que seamos librados de toda aflicción, ira, peligro y necesidad, oremos al Señor.'),
    t('Socórrenos, sálvanos, ten piedad de nosotros y guárdanos, oh Dios, por tu gracia.'),
    t('Conmemorando a nuestra santísima, purísima, bendita sobre todas y gloriosa Señora, la Theotokos y siempre Virgen María, junto con todos los santos, encomendémonos a nosotros mismos, unos a otros, y toda nuestra vida a Cristo Dios.'),
    ref('A Ti, Señor.'),
    rub('Sacerdote, en voz baja, la oración de la primera antífona:'),
    t('Señor, Dios nuestro, cuyo poder es incomparable y cuya gloria es incomprensible, cuya misericordia no tiene medida y cuyo amor a los hombres es inefable: Tú mismo, Soberano, según tu compasión, mira hacia nosotros y hacia este santo templo, y concede tus abundantes misericordias y tus compasiones a nosotros y a los que oran con nosotros.'),
    rub('En voz alta:'),
    t(`Porque a Ti corresponde toda gloria, honor y adoración, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
  ]),

  section('antifonas', 'Las antífonas', [
    rub('Los días de diario se cantan estas antífonas; los domingos, los salmos típicos (102 y 145) y las Bienaventuranzas; en las grandes fiestas, las antífonas propias.'),
    head('Primera antífona'),
    t('Bueno es alabar al Señor y cantar a tu nombre, Altísimo.'),
    ref('Por las oraciones de la Theotokos, Salvador, sálvanos.'),
    t('Anunciar por la mañana tu misericordia, y tu fidelidad por la noche.'),
    t('Porque recto es el Señor, nuestro Dios, y no hay injusticia en Él.'),
    ...PEQUENA_LETANIA,
    rub('Sacerdote, en voz baja, la oración de la segunda antífona:'),
    t('Señor, Dios nuestro, salva a tu pueblo y bendice tu heredad; guarda la plenitud de tu Iglesia; santifica a los que aman el esplendor de tu casa. Glorifícalos Tú a cambio con tu poder divino y no nos abandones a los que esperamos en Ti.'),
    rub('En voz alta:'),
    t(`Porque tuyo es el poder, y tuyos son el Reino, la fuerza y la gloria, del Padre, y del Hijo, y del Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    head('Segunda antífona'),
    t('Alaba, alma mía, al Señor; alabaré al Señor toda mi vida, cantaré a mi Dios mientras exista.'),
    ref('Sálvanos, Hijo de Dios, admirable en tus santos, a los que te cantamos: Aleluya.'),
    t('Bienaventurado aquel cuya ayuda es el Dios de Jacob, cuya esperanza está en el Señor, su Dios.'),
    t('Reinará el Señor para siempre, tu Dios, oh Sión, de generación en generación.'),
    rub(`Gloria al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS} Amén.`),
    t('Hijo unigénito y Verbo de Dios, que siendo inmortal te dignaste, por nuestra salvación, encarnarte de la santa Theotokos y siempre Virgen María, y sin cambiar te hiciste hombre; y crucificado, oh Cristo Dios, con tu muerte venciste a la muerte: Tú, que eres uno de la santa Trinidad, glorificado con el Padre y el Espíritu Santo, sálvanos.'),
    rub('Este himno se atribuye al emperador Justiniano, en el siglo VI, y se canta en todas las Liturgias del año.'),
    ...PEQUENA_LETANIA,
    rub('Sacerdote, en voz baja, la oración de la tercera antífona:'),
    t('Tú, que nos has concedido estas oraciones comunes y unánimes, y que has prometido conceder las peticiones de dos o tres que se ponen de acuerdo en tu nombre: cumple Tú mismo ahora las peticiones de tus siervos en lo que les conviene, dándonos en este mundo el conocimiento de tu verdad y concediéndonos en el venidero la vida eterna.'),
    rub('En voz alta:'),
    t(`Porque eres Dios bueno y amigo de los hombres, y a Ti te damos gloria, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    head('Tercera antífona'),
    rub('Los días de diario se canta el tropario del día o de la fiesta, precedido de un versículo de los salmos según quién sea el santo. Para los apóstoles: «Por toda la tierra se extendió su voz, y hasta los confines del orbe sus palabras». Para los jerarcas: «Mi boca hablará sabiduría, y la meditación de mi corazón, inteligencia». Para los mártires: «Admirable es Dios en sus santos». Para los monjes: «Bienaventurado el hombre que teme al Señor». Los domingos se cantan las Bienaventuranzas con los troparios del día.'),
    { kind: 'day-troparion', content: 'Tropario del día' },
  ]),

  section('pequena-entrada', 'La pequeña entrada', [
    rub('Diácono:'),
    t('Oremos al Señor.'),
    SENOR,
    rub('Sacerdote, en voz baja, la oración de la entrada:'),
    t(`Soberano, Señor Dios nuestro, que estableciste en los cielos los órdenes y los ejércitos de los ángeles y de los arcángeles para el servicio de tu gloria: haz que con nuestra entrada se haga la entrada de los santos ángeles, que celebran con nosotros y glorifican con nosotros tu bondad. Porque a Ti corresponde toda gloria, honor y adoración, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS} Amén.`),
    rub('Diácono, señalando con el orarion hacia oriente:'),
    t('Bendice, señor, la santa entrada.'),
    rub('Sacerdote:'),
    t(`Bendita sea la entrada de tus santos, siempre, ${POR_LOS_SIGLOS} Amén.`),
    rub('El diácono eleva el Evangeliario:'),
    t('¡Sabiduría! ¡De pie!'),
    rub('Himno de la entrada:'),
    ref('Venid, adoremos y postrémonos ante Cristo. Sálvanos, Hijo de Dios, admirable en tus santos (el domingo: que resucitaste de entre los muertos), a los que te cantamos: Aleluya.'),
    rub('Se cantan el tropario del día o de la fiesta, el del santo del templo y el kontakion. Si no hay fiesta, el kontakion es el del día de la semana:'),
    head('Kontakion de cada día'),
    rub('El lunes, de los arcángeles:'),
    t('Arcángeles de Dios, servidores de la gloria divina, guías de los hombres y príncipes de los incorpóreos: pedid para nosotros lo que nos conviene y la gran misericordia, como arcángeles de los incorpóreos.'),
    rub('El martes, del Precursor:'),
    t('Profeta de Dios y Precursor de la gracia: hallamos en la tierra tu cabeza como una rosa santísima, y recibimos siempre curaciones; porque de nuevo, como antes, predicas en el mundo el arrepentimiento.'),
    rub('El miércoles y el viernes, de la Cruz:'),
    t('Tú, que voluntariamente fuiste elevado en la Cruz, concede tus misericordias, oh Cristo Dios, al nuevo pueblo que lleva tu nombre; alegra con tu poder a los fieles que nos gobiernan, dándoles victoria sobre los enemigos: que tengan tu ayuda, arma de paz, trofeo invencible.'),
    rub('El jueves, de los apóstoles:'),
    t('Tomaste, Señor, a los heraldos firmes que hablaban de Dios, la cumbre de tus discípulos, para que gozaran de tus bienes y de tu descanso; porque recibiste sus fatigas y su muerte por encima de todo holocausto, Tú, el único que conoce los corazones.'),
    rub('El sábado, de los mártires:'),
    t('Como primicias de la naturaleza, el mundo te ofrece, Señor, plantador de la creación, a los mártires portadores de Dios. Por sus súplicas, y por la Theotokos, guarda en paz profunda a tu Iglesia, oh lleno de misericordia.'),
  ]),

  section('trisagio', 'El Trisagio', [
    rub('Diácono:'),
    t('Oremos al Señor.'),
    SENOR,
    rub('Sacerdote, en voz baja, la oración del Trisagio:'),
    t('Dios santo, que descansas en los santos, cantado con la voz tres veces santa de los serafines, glorificado por los querubines y adorado por todos los poderes celestiales; que de la nada hiciste existir todas las cosas; que creaste al hombre a tu imagen y semejanza y lo adornaste con todos tus dones; que das a quien te pide sabiduría e inteligencia y no desprecias al pecador, sino que has puesto el arrepentimiento para la salvación; que nos has hecho dignos a nosotros, tus siervos humildes e indignos, de estar también en esta hora ante la gloria de tu santo altar y de ofrecerte la adoración y la glorificación que te debemos: recibe Tú mismo, Soberano, también de la boca de nosotros, pecadores, el himno tres veces santo, y visítanos en tu bondad. Perdónanos toda falta, voluntaria e involuntaria; santifica nuestras almas y nuestros cuerpos, y concédenos servirte en santidad todos los días de nuestra vida, por la intercesión de la santa Theotokos y de todos los santos que te han agradado desde siempre.'),
    rub('En voz alta:'),
    t(`Porque Tú eres santo, Dios nuestro, y a Ti te damos gloria, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    ref('Santo Dios, Santo Fuerte, Santo Inmortal, ten piedad de nosotros. <em>(tres veces)</em>'),
    rub(`Gloria al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS} Amén.`),
    ref('Santo Inmortal, ten piedad de nosotros.'),
    ref('Santo Dios, Santo Fuerte, Santo Inmortal, ten piedad de nosotros.'),
    rub('En Pascua, Navidad, Teofanía, Pentecostés, el Sábado de Lázaro y el Sábado Santo se canta en su lugar: «Cuantos habéis sido bautizados en Cristo, de Cristo os habéis revestido. Aleluya». En la Exaltación de la Cruz y el tercer domingo de Cuaresma: «Ante tu Cruz nos postramos, Soberano, y glorificamos tu santa Resurrección».'),
    rub('Mientras se canta, el sacerdote y el diácono van al trono que está detrás del altar. Diácono: «Manda, señor». Sacerdote: «Bendito el que viene en el nombre del Señor». Diácono: «Bendice, señor, el trono de lo alto». Sacerdote: «Bendito eres en el trono de la gloria de tu Reino, Tú que estás sentado sobre los querubines, siempre, ahora y siempre, y por los siglos de los siglos. Amén».'),
  ]),

  section('lecturas', 'El Apóstol y el Evangelio', [
    rub('Diácono: «¡Atendamos!». Sacerdote: «Paz a todos». Lector: «Y con tu espíritu». Diácono: «¡Sabiduría!». El lector anuncia el prokímenon del día, que el coro canta, y lee el Apóstol. Las lecturas del día están en Inicio y en el Calendario.'),
    rub('Sacerdote, al terminar: «Paz a ti, que has leído». Se canta el Aleluya con sus versículos, y mientras tanto el diácono inciensa. Al incienso, el sacerdote dice:'),
    t('Te ofrecemos el incienso, Cristo Dios nuestro, en olor de fragancia espiritual: Tú, que lo recibes en tu altar sobre los cielos, envíanos a cambio la gracia de tu Espíritu santísimo.'),
    rub('Sacerdote, en voz baja, la oración antes del Evangelio:'),
    t(`Haz brillar en nuestros corazones, Soberano amigo de los hombres, la luz pura del conocimiento de tu divinidad, y abre los ojos de nuestra mente para comprender la predicación de tu Evangelio. Pon en nosotros también el temor de tus bienaventurados mandamientos, para que, pisoteando todos los deseos de la carne, llevemos una vida espiritual, pensando y haciendo todo lo que te agrada. Porque Tú eres la iluminación de nuestras almas y de nuestros cuerpos, Cristo Dios, y a Ti te damos gloria, junto con tu Padre sin principio y tu santísimo, bueno y vivificante Espíritu, ${POR_LOS_SIGLOS} Amén.`),
    rub('El diácono, inclinándose ante el sacerdote: «Bendice, señor, al que anuncia el Evangelio del santo y glorioso apóstol y evangelista N.». Sacerdote:'),
    t('Que Dios, por la intercesión del santo, glorioso apóstol y evangelista N., te dé la palabra para anunciar el Evangelio con gran poder, para cumplimiento del Evangelio de su Hijo amado, nuestro Señor Jesucristo.'),
    rub('Diácono: «Amén». Sacerdote, en voz alta:'),
    t('¡Sabiduría! ¡De pie! Escuchemos el santo Evangelio. Paz a todos.'),
    Y_CON_TU_ESPIRITU,
    rub('Diácono:'),
    t('Lectura del santo Evangelio según san N.'),
    ref('Gloria a Ti, Señor, gloria a Ti.'),
    rub('Sacerdote: «¡Atendamos!». El diácono lee el Evangelio del día. Al terminar:'),
    ref('Gloria a Ti, Señor, gloria a Ti.'),
    rub('Aquí suele ir la homilía.'),
  ]),

  section('letania-ferviente', 'La letanía ferviente', [
    rub('Diácono; el coro responde a cada petición «Señor, ten piedad» tres veces:'),
    t('Digamos todos con toda el alma y con todo el entendimiento, digamos.'),
    t('Señor todopoderoso, Dios de nuestros padres, te rogamos: escúchanos y ten piedad.'),
    t('Ten piedad de nosotros, oh Dios, según tu gran misericordia; te rogamos: escúchanos y ten piedad.'),
    t('Oremos también por nuestro arzobispo N.'),
    t('Oremos también por nuestros hermanos, los sacerdotes, los hieromonjes, los hierodiáconos y los monjes, y por toda nuestra hermandad en Cristo.'),
    t('Oremos también por la misericordia, la vida, la paz, la salud, la salvación, la visita, el perdón y la remisión de los pecados de los siervos de Dios, de todos los cristianos piadosos y ortodoxos que viven en esta ciudad o están de paso, de los fieles, administradores y bienhechores de este santo templo.'),
    t('Oremos también por los bienaventurados y siempre recordados fundadores de esta santa iglesia, y por todos nuestros padres y hermanos que se han dormido antes que nosotros, los que reposan aquí piadosamente y los ortodoxos de todas partes.'),
    t('Oremos también por los que traen ofrendas y hacen el bien en este santo y venerabilísimo templo, por los que trabajan en él, por los que cantan, y por el pueblo aquí presente, que espera de Ti la grande y rica misericordia.'),
    rub('Sacerdote, en voz baja, la oración de la súplica ferviente:'),
    t('Señor, Dios nuestro: recibe de tus siervos esta súplica ferviente y ten piedad de nosotros según la multitud de tu misericordia, y envía tus compasiones sobre nosotros y sobre todo tu pueblo, que espera de Ti la grande y rica misericordia.'),
    rub('En voz alta:'),
    t(`Porque eres Dios misericordioso y amigo de los hombres, y a Ti te damos gloria, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
  ]),

  section('catecumenos', 'La letanía de los catecúmenos', [
    rub('Recuerda el tiempo en que los que se preparaban para el bautismo asistían a la primera parte de la Liturgia y salían antes de la Anáfora. Diácono:'),
    t('Catecúmenos, orad al Señor.'),
    SENOR,
    t('Fieles, oremos por los catecúmenos, para que el Señor tenga piedad de ellos;'),
    t('para que los instruya en la palabra de la verdad;'),
    t('para que les revele el Evangelio de la justicia;'),
    t('para que los una a su santa Iglesia, católica y apostólica.'),
    t('Sálvalos, ten piedad de ellos, socórrelos y guárdalos, oh Dios, por tu gracia.'),
    SENOR,
    t('Catecúmenos, inclinad la cabeza ante el Señor.'),
    ref('A Ti, Señor.'),
    rub('Sacerdote, en voz baja, la oración por los catecúmenos:'),
    t('Señor, Dios nuestro, que habitas en las alturas y miras lo humilde; que enviaste para la salvación del género humano a tu Hijo unigénito y Dios, nuestro Señor Jesucristo: mira a tus siervos los catecúmenos, que han inclinado ante Ti la cabeza, y hazlos dignos, a su debido tiempo, del baño de la regeneración, del perdón de los pecados y del vestido de la incorrupción; únelos a tu santa Iglesia, católica y apostólica, y cuéntalos en tu rebaño escogido.'),
    rub('En voz alta:'),
    t(`Para que también ellos glorifiquen con nosotros tu honorabilísimo y magnífico nombre, del Padre, y del Hijo, y del Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    rub('Diácono:'),
    t('Cuantos sois catecúmenos, salid. Catecúmenos, salid. Cuantos sois catecúmenos, salid. Que no quede ninguno de los catecúmenos. Cuantos somos fieles…'),
  ]),

  section('fieles', 'Las oraciones de los fieles', [
    rub('Diácono:'),
    t('Una y otra vez, en paz, oremos al Señor.'),
    SENOR,
    t('Socórrenos, sálvanos, ten piedad de nosotros y guárdanos, oh Dios, por tu gracia.'),
    SENOR,
    t('¡Sabiduría!'),
    rub('Sacerdote, en voz baja, la primera oración de los fieles:'),
    t('Te damos gracias, Señor, Dios de los ejércitos, que nos has hecho dignos de estar también ahora ante tu santo altar y de postrarnos ante tus misericordias por nuestros pecados y por las faltas que el pueblo comete por ignorancia. Recibe, oh Dios, nuestra súplica; haznos dignos de ofrecerte súplicas, ruegos y sacrificios sin sangre por todo tu pueblo; y capacítanos a nosotros, a quienes has puesto en este ministerio tuyo, con el poder de tu Espíritu Santo, para que sin reproche y sin tropiezo, con el testimonio limpio de nuestra conciencia, te invoquemos en todo tiempo y lugar, y para que, escuchándonos, seas propicio con nosotros en la abundancia de tu bondad.'),
    rub('En voz alta:'),
    t(`Porque a Ti corresponde toda gloria, honor y adoración, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    rub('Diácono:'),
    t('Una y otra vez, en paz, oremos al Señor.'),
    SENOR,
    t('Socórrenos, sálvanos, ten piedad de nosotros y guárdanos, oh Dios, por tu gracia.'),
    SENOR,
    t('¡Sabiduría!'),
    rub('Sacerdote, en voz baja, la segunda oración de los fieles:'),
    t('Una y muchas veces nos postramos ante Ti y te suplicamos, oh Bueno y amigo de los hombres, que, mirando nuestra súplica, purifiques nuestras almas y nuestros cuerpos de toda mancha de la carne y del espíritu, y nos concedas estar ante tu santo altar sin culpa y sin condena. Concede también, oh Dios, a los que oran con nosotros progreso en la vida, en la fe y en el entendimiento espiritual; dales que te sirvan siempre con temor y amor, que participen sin culpa y sin condena de tus santos misterios y que sean hechos dignos de tu Reino celestial.'),
    rub('En voz alta:'),
    t(`Para que, guardados siempre por tu poder, te demos gloria, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
  ]),

  section('gran-entrada', 'El Querúbico y la gran entrada', [
    rub('El coro empieza el himno querúbico:'),
    ref('Nosotros, que místicamente representamos a los querubines y cantamos el himno tres veces santo a la Trinidad vivificante, dejemos ahora toda preocupación de esta vida…'),
    rub('Mientras tanto, el sacerdote reza en voz baja la oración del himno querúbico:'),
    t('Nadie que esté atado a los deseos y placeres de la carne es digno de acercarse a Ti, de aproximarse o de servirte, Rey de la gloria; porque servirte es algo grande y temible, aun para los mismos poderes celestiales. Pero, por tu inefable e inmenso amor a los hombres, te hiciste hombre sin cambio ni alteración, y fuiste llamado nuestro Sumo Sacerdote, y nos entregaste, como Soberano de todo, la celebración de este sacrificio litúrgico y sin sangre. Porque sólo Tú, Señor Dios nuestro, gobiernas lo celestial y lo terreno: Tú, que vas sentado en el trono de los querubines, Señor de los serafines y Rey de Israel, el único santo, que descansas en los santos.'),
    t('A Ti, pues, el único bueno y dispuesto a escuchar, te suplico: mira hacia mí, tu siervo pecador e inútil, y purifica mi alma y mi corazón de la mala conciencia; y, revestido de la gracia del sacerdocio, capacítame con el poder de tu Espíritu Santo para estar ante esta tu santa mesa y consagrar tu santo y purísimo Cuerpo y tu preciosa Sangre. Porque a Ti me acerco inclinando la cabeza, y te suplico: no apartes tu rostro de mí, ni me rechaces de entre tus hijos, sino haz que te sean ofrecidos estos dones por mí, tu siervo pecador e indigno. Porque Tú eres el que ofrece y el que es ofrecido, el que recibe y el que es repartido, Cristo Dios nuestro, y a Ti te damos gloria, junto con tu Padre sin principio y tu santísimo, bueno y vivificante Espíritu, ahora y siempre, y por los siglos de los siglos. Amén.'),
    rub('Después, el sacerdote y el diácono dicen tres veces el himno querúbico, con una inclinación, y van a la prótesis. El sacerdote inciensa los dones, pone el aér sobre los hombros del diácono, toma el cáliz, y salen en procesión por la puerta norte. Ante el pueblo, conmemoran:'),
    t('A todos vosotros, cristianos piadosos y ortodoxos, os recuerde el Señor Dios en su Reino, siempre, ahora y siempre, y por los siglos de los siglos.'),
    rub('En los libros griegos la conmemoración se alarga: el arzobispo, el país, los presentes, los fundadores del templo y los difuntos. Al entrar en el santuario, el diácono pide al sacerdote que se acuerde de él, y el coro termina el himno:'),
    ref('…para recibir al Rey de todos, escoltado invisiblemente por los ejércitos angélicos. Aleluya, aleluya, aleluya.'),
    rub('El sacerdote deja los dones sobre el altar, los cubre con el aér y dice:'),
    t('El noble José bajó del madero tu purísimo Cuerpo, lo envolvió en una sábana limpia con aromas y lo puso en un sepulcro nuevo.'),
    rub('Y el salmo 50: «Favorece, Señor, con tu benevolencia a Sión, y reconstrúyanse los muros de Jerusalén; entonces aceptarás el sacrificio de justicia, ofrendas y holocaustos; entonces ofrecerán novillos sobre tu altar». Diácono y sacerdote se piden oraciones mutuamente; el sacerdote dice: «El Espíritu Santo vendrá sobre ti y el poder del Altísimo te cubrirá con su sombra», y el diácono: «El mismo Espíritu celebrará con nosotros todos los días de nuestra vida».'),
    rub('El Jueves Santo y el Sábado Santo se cantan en lugar del querúbico «De tu Cena mística» y «Calle toda carne mortal».'),
  ]),

  section('letania-ofrenda', 'La letanía de la ofrenda', [
    rub('Diácono; el coro responde «Señor, ten piedad»:'),
    t('Completemos nuestra oración al Señor.'),
    t('Por los preciosos dones presentados, oremos al Señor.'),
    t('Por esta santa casa y por los que entran en ella con fe, piedad y temor de Dios, oremos al Señor.'),
    t('Por que seamos librados de toda aflicción, ira, peligro y necesidad, oremos al Señor.'),
    t('Socórrenos, sálvanos, ten piedad de nosotros y guárdanos, oh Dios, por tu gracia.'),
    ...PETICIONES,
    t('Conmemorando a nuestra santísima, purísima, bendita sobre todas y gloriosa Señora, la Theotokos y siempre Virgen María, junto con todos los santos, encomendémonos a nosotros mismos, unos a otros, y toda nuestra vida a Cristo Dios.'),
    ref('A Ti, Señor.'),
    rub('Sacerdote, en voz baja, la oración de la ofrenda:'),
    t('Señor, Dios todopoderoso, el único santo, que recibes el sacrificio de alabanza de los que te invocan con todo el corazón: recibe también la súplica de nosotros, pecadores, y llévala a tu santo altar; y capacítanos para ofrecerte dones y sacrificios espirituales por nuestros pecados y por las faltas que el pueblo comete por ignorancia. Haznos dignos de encontrar gracia ante Ti, para que nuestro sacrificio te sea agradable y el buen Espíritu de tu gracia habite en nosotros, en estos dones presentados y en todo tu pueblo.'),
    rub('En voz alta:'),
    t(`Por las compasiones de tu Hijo unigénito, con quien eres bendito, junto con tu santísimo, bueno y vivificante Espíritu, ${POR_LOS_SIGLOS}`),
    AMEN,
  ]),

  section('credo', 'El beso de la paz y el Símbolo de la Fe', [
    rub('Sacerdote:'),
    t('Paz a todos.'),
    Y_CON_TU_ESPIRITU,
    rub('Diácono:'),
    t('Amémonos los unos a los otros, para que en un mismo espíritu confesemos…'),
    ref('…al Padre, y al Hijo, y al Espíritu Santo, Trinidad consustancial e indivisible.'),
    rub('El sacerdote se inclina tres veces ante los dones diciendo: «Te amaré, Señor, fortaleza mía; el Señor es mi roca, mi refugio y mi libertador». Los que celebran juntos se dan el beso de la paz: «Cristo está entre nosotros». «Está y estará».'),
    rub('Diácono:'),
    t('¡Las puertas, las puertas! ¡Con sabiduría, atendamos!'),
    rub('Todos dicen el Símbolo de la Fe:'),
    t('Creo en un solo Dios, Padre todopoderoso, Creador del cielo y de la tierra, de todo lo visible y lo invisible.'),
    t('Y en un solo Señor Jesucristo, Hijo unigénito de Dios, nacido del Padre antes de todos los siglos: Luz de Luz, Dios verdadero de Dios verdadero, engendrado, no creado, consustancial al Padre, por quien todo fue hecho; que por nosotros los hombres y por nuestra salvación bajó de los cielos, y se encarnó del Espíritu Santo y de María la Virgen, y se hizo hombre; y fue crucificado por nosotros bajo Poncio Pilato, y padeció y fue sepultado; y resucitó al tercer día según las Escrituras, y subió a los cielos, y está sentado a la derecha del Padre; y de nuevo vendrá con gloria para juzgar a vivos y muertos, y su Reino no tendrá fin.'),
    t('Y en el Espíritu Santo, Señor y dador de vida, que procede del Padre, que con el Padre y el Hijo es adorado y glorificado, que habló por los profetas.'),
    t('En una Iglesia, santa, católica y apostólica. Confieso un solo bautismo para el perdón de los pecados. Espero la resurrección de los muertos y la vida del siglo venidero. Amén.'),
  ]),

  section('anafora', 'La Anáfora', [
    rub('Diácono:'),
    t('Estemos de pie con dignidad, estemos con temor, atendamos para ofrecer en paz la santa ofrenda.'),
    ref('Misericordia de paz, sacrificio de alabanza.'),
    rub('Sacerdote, bendiciendo al pueblo:'),
    t('La gracia de nuestro Señor Jesucristo, el amor de Dios Padre y la comunión del Espíritu Santo estén con todos vosotros.'),
    ref('Y con tu espíritu.'),
    t('Levantemos el corazón.'),
    ref('Lo tenemos levantado hacia el Señor.'),
    t('Demos gracias al Señor.'),
    ref('Es digno y justo.'),
    rub('En los libros eslavos y en muchas iglesias griegas el coro canta: «Es digno y justo adorar al Padre, y al Hijo, y al Espíritu Santo, Trinidad consustancial e indivisible».'),
    rub('Sacerdote, en voz baja:'),
    t('Es digno y justo cantarte, bendecirte, alabarte, darte gracias y adorarte en todo lugar de tu dominio. Porque Tú eres Dios inefable, inconcebible, invisible, incomprensible, que siempre eres y eres igual: Tú, y tu Hijo unigénito, y tu Espíritu Santo. Tú nos sacaste de la nada a la existencia, y cuando caímos nos levantaste de nuevo, y no dejaste de hacerlo todo hasta subirnos al cielo y concedernos tu Reino venidero. Por todo esto te damos gracias a Ti, a tu Hijo unigénito y a tu Espíritu Santo; por todos los beneficios, manifiestos y ocultos, que hemos recibido, los que conocemos y los que no conocemos. Te damos gracias también por esta Liturgia, que te dignas recibir de nuestras manos, aunque están ante Ti miles de arcángeles y miríadas de ángeles, los querubines y los serafines, de seis alas y muchos ojos, que se elevan alados…'),
    rub('En voz alta:'),
    t('…cantando, aclamando, clamando y diciendo el himno de victoria:'),
    ref('Santo, santo, santo es el Señor de los ejércitos; llenos están el cielo y la tierra de tu gloria. Hosanna en las alturas. Bendito el que viene en el nombre del Señor. Hosanna en las alturas.'),
    rub('Sacerdote, en voz baja:'),
    t('Con estos poderes bienaventurados también nosotros, Soberano amigo de los hombres, clamamos y decimos: Santo eres y santísimo, Tú, y tu Hijo unigénito, y tu Espíritu Santo. Santo eres y santísimo, y magnífica es tu gloria, Tú que tanto amaste a tu mundo que entregaste a tu Hijo unigénito, para que todo el que crea en Él no perezca, sino que tenga vida eterna. Él vino, cumplió toda la economía de nuestra salvación, y en la noche en que fue entregado —o más bien, en que se entregó a sí mismo por la vida del mundo—, tomó el pan en sus manos santas, purísimas e inmaculadas, dio gracias, lo bendijo, lo santificó, lo partió y lo dio a sus santos discípulos y apóstoles, diciendo:'),
    rub('En voz alta:'),
    t('Tomad, comed: esto es mi Cuerpo, que por vosotros es partido para el perdón de los pecados.'),
    AMEN,
    rub('En voz baja: «Del mismo modo, después de cenar, tomó el cáliz, diciendo:». En voz alta:'),
    t('Bebed de él todos: ésta es mi Sangre, la de la nueva Alianza, que por vosotros y por muchos es derramada para el perdón de los pecados.'),
    AMEN,
    rub('Sacerdote, en voz baja:'),
    t('Recordando, pues, este mandamiento salvador y todo lo que se ha hecho por nosotros: la cruz, el sepulcro, la resurrección al tercer día, la subida a los cielos, el estar sentado a la derecha, la segunda y gloriosa venida…'),
    rub('En voz alta, mientras el diácono eleva los dones cruzando los brazos:'),
    t('Lo tuyo, de lo tuyo, te lo ofrecemos, en todo y por todo.'),
    ref('A Ti te cantamos, a Ti te bendecimos, a Ti te damos gracias, Señor, y te suplicamos, Dios nuestro.'),
    rub('Sacerdote, en voz baja, la epíclesis:'),
    t('Te ofrecemos todavía este culto espiritual y sin sangre, y te invocamos, te rogamos y te suplicamos: envía tu Espíritu Santo sobre nosotros y sobre estos dones presentados.'),
    rub('El sacerdote y el diácono se inclinan tres veces diciendo: «Oh Dios, sé propicio conmigo, pecador, y ten piedad de mí». En las iglesias eslavas se intercala aquí el tropario de la Hora Tercia. El diácono, señalando el pan: «Bendice, señor, el santo pan». Sacerdote, bendiciéndolo:'),
    t('Y haz de este pan el precioso Cuerpo de tu Cristo.'),
    rub('Diácono: «Amén. Bendice, señor, el santo cáliz». Sacerdote:'),
    t('Y de lo que hay en este cáliz, la preciosa Sangre de tu Cristo.'),
    rub('Diácono: «Amén. Bendice, señor, ambos». Sacerdote, bendiciendo los dos:'),
    t('Transformándolos por tu Espíritu Santo.'),
    rub('Diácono: «Amén, amén, amén». Sacerdote, en voz baja:'),
    t('Para que sean, para los que los reciban, sobriedad del alma, perdón de los pecados, comunión de tu Espíritu Santo, plenitud del Reino de los cielos y confianza ante Ti, y no juicio ni condena. Te ofrecemos todavía este culto espiritual por los que han descansado en la fe: antepasados, padres, patriarcas, profetas, apóstoles, predicadores, evangelistas, mártires, confesores, ascetas, maestros, y por todo espíritu justo que ha llegado a la perfección en la fe…'),
    rub('En voz alta, mientras inciensa:'),
    t('…especialmente por nuestra santísima, purísima, bendita sobre todas y gloriosa Señora, la Theotokos y siempre Virgen María.'),
    ref('Digno es en verdad bendecirte, oh Theotokos, siempre bienaventurada y del todo inmaculada, y Madre de nuestro Dios. Más venerable que los querubines e incomparablemente más gloriosa que los serafines, tú que sin corrupción diste a luz a Dios Verbo, verdadera Theotokos, te engrandecemos.'),
    rub('En las grandes fiestas, en lugar de «Digno es», se canta el irmos de la novena oda de la fiesta. Sacerdote, en voz baja:'),
    t('Por san Juan, profeta, Precursor y Bautista; por los santos, gloriosos y dignos de toda alabanza apóstoles; por san N., cuya memoria celebramos, y por todos tus santos, por cuyas súplicas visítanos, oh Dios. Y acuérdate de todos los que se han dormido con la esperanza de la resurrección para la vida eterna (aquí se nombran los difuntos), y dales descanso, Dios nuestro, donde brilla la luz de tu rostro.'),
    t('Te suplicamos todavía: acuérdate, Señor, de todo el episcopado ortodoxo, que dispensa rectamente la palabra de tu verdad, de todo el presbiterio, del diaconado en Cristo y de todo el orden sacerdotal y monástico. Te ofrecemos todavía este culto espiritual por el mundo entero, por tu santa Iglesia, católica y apostólica, por los que viven en pureza y en una vida digna, y por los que nos gobiernan: concédeles, Señor, un gobierno en paz, para que también nosotros, en su calma, llevemos una vida tranquila y sosegada, con toda piedad y dignidad.'),
    rub('En voz alta:'),
    t('Ante todo, acuérdate, Señor, de nuestro arzobispo N.: concédelo a tus santas Iglesias en paz, sano y salvo, honrado, con salud, largos días y dispensando rectamente la palabra de tu verdad.'),
    rub('El diácono conmemora a los vivos, y el coro canta:'),
    ref('Y de todos y de todas.'),
    rub('Sacerdote, en voz baja:'),
    t('Acuérdate, Señor, de la ciudad en que vivimos, de toda ciudad y región y de los que viven en ellas con fe. Acuérdate, Señor, de los que navegan, de los que viajan, de los enfermos, de los que sufren, de los cautivos, y de su salvación. Acuérdate, Señor, de los que traen ofrendas y hacen el bien en tus santas Iglesias, y de los que se acuerdan de los pobres; y envía sobre todos nosotros tus misericordias.'),
    rub('En voz alta:'),
    t(`Y concédenos glorificar y cantar con una sola boca y un solo corazón tu honorabilísimo y magnífico nombre, del Padre, y del Hijo, y del Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    rub('Sacerdote, volviéndose y bendiciendo al pueblo:'),
    t('Y que las misericordias de nuestro gran Dios y Salvador Jesucristo estén con todos vosotros.'),
    ref('Y con tu espíritu.'),
  ]),

  section('padre-nuestro', 'La letanía antes del Padre Nuestro', [
    rub('Diácono; el coro responde «Señor, ten piedad»:'),
    t('Recordando a todos los santos, una y otra vez, en paz, oremos al Señor.'),
    t('Por los preciosos dones ofrecidos y santificados, oremos al Señor.'),
    t('Para que nuestro Dios, amigo de los hombres, que los ha recibido en su altar santo, celeste y espiritual en olor de fragancia espiritual, nos envíe a cambio la gracia divina y el don del Espíritu Santo, oremos.'),
    t('Por que seamos librados de toda aflicción, ira, peligro y necesidad, oremos al Señor.'),
    t('Socórrenos, sálvanos, ten piedad de nosotros y guárdanos, oh Dios, por tu gracia.'),
    ...PETICIONES,
    t('Habiendo pedido la unidad de la fe y la comunión del Espíritu Santo, encomendémonos a nosotros mismos, unos a otros, y toda nuestra vida a Cristo Dios.'),
    ref('A Ti, Señor.'),
    rub('Sacerdote, en voz baja:'),
    t('A Ti te encomendamos, Soberano amigo de los hombres, toda nuestra vida y nuestra esperanza, y te invocamos, te rogamos y te suplicamos: haznos dignos de participar de tus misterios celestiales y temibles de esta mesa sagrada y espiritual con la conciencia limpia, para el perdón de los pecados, para la remisión de las faltas, para la comunión del Espíritu Santo, para la herencia del Reino de los cielos, para la confianza ante Ti, y no para juicio ni para condena.'),
    rub('En voz alta:'),
    t('Y concédenos, Soberano, que con confianza y sin condena nos atrevamos a invocarte a Ti, Dios del cielo, como Padre, y a decir:'),
    rub('Todos:'),
    t('Padre nuestro, que estás en los cielos: santificado sea tu nombre; venga tu Reino; hágase tu voluntad, así en la tierra como en el cielo. El pan nuestro de cada día dánoslo hoy; y perdónanos nuestras deudas, así como nosotros perdonamos a nuestros deudores; y no nos dejes caer en la tentación, mas líbranos del maligno.'),
    rub('Sacerdote:'),
    t(`Porque tuyos son el Reino, el poder y la gloria, del Padre, y del Hijo, y del Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    t('Paz a todos.'),
    Y_CON_TU_ESPIRITU,
    rub('Diácono:'),
    t('Inclinemos la cabeza ante el Señor.'),
    ref('A Ti, Señor.'),
    rub('Sacerdote, en voz baja, la oración de la inclinación:'),
    t('Te damos gracias, Rey invisible, que con tu poder sin medida lo creaste todo y en la abundancia de tu misericordia lo sacaste todo de la nada a la existencia. Tú mismo, Soberano, mira desde el cielo a los que han inclinado la cabeza ante Ti: porque no la han inclinado ante la carne y la sangre, sino ante Ti, Dios temible. Tú, pues, Soberano, dispón para bien de todos lo que tenemos delante, según la necesidad de cada uno: navega con los que navegan, acompaña a los que viajan, cura a los enfermos, Tú, médico de nuestras almas y de nuestros cuerpos.'),
    rub('En voz alta:'),
    t(`Por la gracia, las compasiones y el amor a los hombres de tu Hijo unigénito, con quien eres bendito, junto con tu santísimo, bueno y vivificante Espíritu, ${POR_LOS_SIGLOS}`),
    AMEN,
    rub('Sacerdote, en voz baja, la oración de la elevación:'),
    t('Atiende, Señor Jesucristo, Dios nuestro, desde tu santa morada y desde el trono de la gloria de tu Reino, y ven a santificarnos, Tú que estás sentado arriba con el Padre y estás aquí invisiblemente con nosotros. Y dígnate, con tu mano poderosa, darnos tu Cuerpo purísimo y tu preciosa Sangre, y por medio de nosotros a todo el pueblo.'),
    rub('El sacerdote y el diácono se inclinan tres veces: «Oh Dios, sé propicio conmigo, pecador, y ten piedad de mí».'),
  ]),

  section('comunion', 'La Comunión', [
    rub('Diácono:'),
    t('¡Atendamos!'),
    rub('Sacerdote, elevando el Cordero:'),
    t('Las cosas santas, para los santos.'),
    ref('Uno solo es santo, uno solo es Señor, Jesucristo, para gloria de Dios Padre. Amén.'),
    rub('El coro canta el versículo de comunión. Si no hay fiesta, el de cada día de la semana:'),
    rub('Domingo: «Alabad al Señor desde los cielos, alabadle en las alturas. Aleluya». Lunes, de los ángeles: «El que hace de sus ángeles espíritus, y de sus servidores llama de fuego. Aleluya». Martes, del Precursor: «En memoria eterna quedará el justo. Aleluya». Miércoles, de la Theotokos: «Tomaré el cáliz de la salvación e invocaré el nombre del Señor. Aleluya». Jueves, de los apóstoles: «Por toda la tierra se extendió su voz, y hasta los confines del orbe sus palabras. Aleluya». Viernes, de la Cruz: «Obraste la salvación en medio de la tierra, oh Cristo Dios. Aleluya». Sábado, de los difuntos: «Bienaventurados los que escogiste y tomaste, Señor; su memoria, de generación en generación. Aleluya».'),
    rub('Mientras tanto, el sacerdote parte el Cordero en cuatro:'),
    t('Se parte y se reparte el Cordero de Dios, que se parte y no se divide, que siempre se come y nunca se consume, sino que santifica a los que participan de Él.'),
    rub('Pone una parte en el cáliz: «Plenitud del cáliz de la fe, del Espíritu Santo». Y vierte en él el agua caliente: «Bendito el fervor de tus santos, siempre, ahora y siempre, y por los siglos de los siglos. Amén. Fervor de la fe, lleno del Espíritu Santo».'),
    rub('Antes de comulgar, el sacerdote y el diácono se piden perdón, y dicen la oración de la comunión, la misma que dirán los fieles:'),
    t('Creo, Señor, y confieso que Tú eres verdaderamente el Cristo, el Hijo de Dios vivo, que viniste al mundo a salvar a los pecadores, de los cuales yo soy el primero. Creo también que esto mismo es tu Cuerpo purísimo y que esto mismo es tu preciosa Sangre. Por eso te suplico: ten piedad de mí y perdóname mis faltas, voluntarias e involuntarias, de palabra y de obra, conscientes e inconscientes, y hazme digno de participar sin condena de tus purísimos misterios, para el perdón de los pecados y para la vida eterna. Amén.'),
    t('De tu Cena mística, Hijo de Dios, recíbeme hoy como comensal; porque no diré el misterio a tus enemigos, ni te daré un beso como Judas, sino que, como el ladrón, te confieso: Acuérdate de mí, Señor, en tu Reino.'),
    t('Que la comunión de tus santos misterios, Señor, no sea para mi juicio ni para mi condena, sino para la curación del alma y del cuerpo.'),
    rub('En la tradición griega se añaden algunos versos de san Simeón Metafrasta: «He aquí que me acerco a la divina comunión: Creador, no me quemes al participar, porque eres fuego que quema a los indignos; purifícame, más bien, de toda mancha». Comulgan el clero y, abiertas las puertas santas, el diácono dice:'),
    t('Acercaos con temor de Dios, con fe y con amor.'),
    ref('Bendito el que viene en el nombre del Señor; Dios es el Señor y se nos ha manifestado.'),
    rub('Al dar la comunión a cada fiel, el sacerdote dice: «Comulga el siervo de Dios N. el Cuerpo y la Sangre de Cristo, para el perdón de los pecados y la vida eterna. Amén». Mientras tanto se canta: «Recibid el Cuerpo de Cristo, gustad la fuente inmortal».'),
    rub('El sacerdote vuelve al altar y pone en el cáliz las partículas de la patena: «Lava, Señor, con tu santa Sangre los pecados de tus siervos aquí recordados, por las intercesiones de la Theotokos y de todos tus santos». Después bendice al pueblo:'),
    t('Salva, oh Dios, a tu pueblo y bendice tu heredad.'),
    ref('Hemos visto la luz verdadera, hemos recibido el Espíritu celestial, hemos encontrado la fe verdadera, adorando a la Trinidad indivisible, porque ella nos ha salvado.'),
    rub('El sacerdote inciensa los dones y dice en voz baja: «Elévate sobre los cielos, oh Dios, y sobre toda la tierra tu gloria». Toma el cáliz y, volviéndose al pueblo:'),
    t(`Siempre, ${POR_LOS_SIGLOS}`),
    ref('Amén. Que nuestra boca se llene de tu alabanza, Señor, para que cantemos tu gloria, porque nos has hecho dignos de participar de tus santos misterios. Guárdanos en tu santidad, para que meditemos todo el día tu justicia. Aleluya, aleluya, aleluya.'),
  ]),

  section('accion-de-gracias', 'La acción de gracias', [
    rub('Diácono:'),
    t('De pie. Habiendo recibido los divinos, santos, purísimos, inmortales, celestiales, vivificantes y temibles misterios de Cristo, demos gracias dignamente al Señor.'),
    SENOR,
    t('Socórrenos, sálvanos, ten piedad de nosotros y guárdanos, oh Dios, por tu gracia.'),
    SENOR,
    t('Habiendo pedido que todo el día sea perfecto, santo, pacífico y sin pecado, encomendémonos a nosotros mismos, unos a otros, y toda nuestra vida a Cristo Dios.'),
    ref('A Ti, Señor.'),
    rub('Sacerdote, en voz baja, la oración de acción de gracias:'),
    t('Te damos gracias, Soberano amigo de los hombres, bienhechor de nuestras almas, porque también en este día nos has hecho dignos de tus misterios celestiales e inmortales. Endereza nuestro camino, afiánzanos a todos en tu temor, guarda nuestra vida, asegura nuestros pasos, por las oraciones y súplicas de la gloriosa Theotokos y siempre Virgen María y de todos tus santos.'),
    rub('En voz alta:'),
    t(`Porque Tú eres nuestra santificación, y a Ti te damos gloria, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
  ]),

  section('despedida', 'La oración detrás del ambón y la despedida', [
    rub('Sacerdote:'),
    t('En paz, salgamos.'),
    ref('En el nombre del Señor.'),
    rub('Diácono:'),
    t('Oremos al Señor.'),
    SENOR,
    rub('El sacerdote sale del santuario y, ante el pueblo, dice la oración detrás del ambón:'),
    t(`Señor, que bendices a los que te bendicen y santificas a los que confían en Ti: salva a tu pueblo y bendice tu heredad. Guarda la plenitud de tu Iglesia; santifica a los que aman el esplendor de tu casa; glorifícalos Tú a cambio con tu poder divino, y no nos abandones a los que esperamos en Ti. Da la paz a tu mundo, a tus Iglesias, a los sacerdotes, a los que nos gobiernan, a los que nos protegen y a todo tu pueblo. Porque todo buen don y todo don perfecto viene de lo alto y baja de Ti, Padre de las luces, y a Ti te damos gloria, acción de gracias y adoración, al Padre, y al Hijo, y al Espíritu Santo, ${POR_LOS_SIGLOS}`),
    AMEN,
    ref('Bendito sea el nombre del Señor, desde ahora y para siempre. <em>(tres veces)</em>'),
    rub('Mientras se canta, el sacerdote dice en voz baja ante la prótesis, donde se consumirán los dones: «Tú, Cristo Dios nuestro, que eres la plenitud de la Ley y de los profetas, que cumpliste toda la economía del Padre: llena de gozo y de alegría nuestros corazones, siempre, ahora y siempre, y por los siglos de los siglos. Amén».'),
    rub('Sacerdote:'),
    t(`Que la bendición del Señor y su misericordia vengan sobre vosotros, por su gracia divina y su amor a los hombres, siempre, ${POR_LOS_SIGLOS}`),
    AMEN,
    t('Gloria a Ti, Cristo Dios, esperanza nuestra, gloria a Ti.'),
    rub('Despedida:'),
    t('Cristo, nuestro Dios verdadero (el domingo: que resucitó de entre los muertos), por las intercesiones de su purísima y del todo inmaculada santa Madre; por el poder de la preciosa y vivificante Cruz; por la protección de las venerables Potestades celestiales incorpóreas; por las súplicas del venerable y glorioso profeta, Precursor y Bautista Juan; de los santos, gloriosos y dignos de toda alabanza apóstoles; de nuestros santos padres, los grandes jerarcas y maestros ecuménicos; de nuestro santo padre Juan Crisóstomo, arzobispo de Constantinopla; de los santos, gloriosos y victoriosos mártires; de nuestros venerables padres portadores de Dios; del santo de este templo; de los santos y justos antepasados de Dios Joaquín y Ana; del santo del día y de todos los santos, tenga piedad de nosotros y nos salve, porque es bueno, amigo de los hombres y misericordioso.'),
    t('Por las oraciones de nuestros santos padres, Señor Jesucristo, Dios nuestro, ten piedad de nosotros y sálvanos.'),
    AMEN,
    rub('Los fieles se acercan a besar la cruz y reciben el antídoron, el pan bendito que sobró de la proscomidia. El sacerdote consume los dones que quedan en el cáliz y lee las oraciones de acción de gracias.'),
  ]),
];
