/**
 * Tercera tanda del santoral.
 *
 * Mismo criterio que las dos anteriores: las biografías son reseñas históricas
 * redactadas para ATHOS a partir de fuentes hagiográficas comunes —no son
 * textos litúrgicos—, y no se incluye ningún tropario, porque incorporarlos
 * exige una versión española verificable que ATHOS todavía no tiene.
 *
 * Sólo entran conmemoraciones cuya fecha en el calendario bizantino conozco con
 * seguridad. Colocar a un santo en un día equivocado sería la misma falta que
 * inventarle un texto.
 */
import type { SaintCategory } from '@/types';

export interface SaintSeedThird {
  id: string;
  name: string;
  day: string;
  category: SaintCategory[];
  century?: string;
  place?: string;
  biography: string;
}

export const THIRD_SAINTS: SaintSeedThird[] = [
  /* ---------------- Enero ---------------- */
  { id: 'malaquias-profeta', name: 'Profeta Malaquías', day: '01-03', category: ['profeta'], century: 'V a.C.', place: 'Judea', biography: 'El último de los profetas menores, cuyo libro cierra el Antiguo Testamento. Anunció al mensajero que prepararía el camino del Señor y el «sol de justicia» que traería la sanación. Su nombre significa «mi mensajero».' },
  { id: 'setenta-apostoles', name: 'Sínaxis de los Setenta Apóstoles', day: '01-04', category: ['apostol'], century: 'I', biography: 'Los setenta discípulos que el Señor envió de dos en dos delante de Él. La Iglesia los conmemora juntos porque, salvo unos pocos, sus nombres y sus caminos se perdieron: fueron los primeros obispos de ciudades que hoy no sabríamos señalar en un mapa.' },
  { id: 'polieucto-melitene', name: 'San Polieucto de Melitene', day: '01-09', category: ['martir'], century: 'III', place: 'Melitene, Armenia', biography: 'Soldado romano († 259). Al convertirse rompió los ídolos que se llevaban en procesión y rasgó el edicto imperial contra los cristianos. Ni las súplicas de su suegro, que era el juez, ni las de su mujer lo hicieron retractarse.' },
  { id: 'tatiana-roma', name: 'Santa Tatiana de Roma', day: '01-12', category: ['martir'], century: 'III', place: 'Roma', biography: 'Diaconisa de la Iglesia de Roma († c. 226). Hija de un cónsul, repartió su fortuna entre los pobres y cuidó de los enfermos. Es patrona de los estudiantes en la tradición rusa, por la universidad de Moscú fundada el día de su fiesta.' },
  { id: 'cadenas-pedro', name: 'Veneración de las cadenas de san Pedro', day: '01-16', category: ['apostol'], century: 'I', place: 'Jerusalén y Roma', biography: 'Se veneran las cadenas con que Herodes ató al apóstol y que un ángel le soltó en la cárcel, según cuentan los Hechos. La fiesta no celebra un objeto, sino que Dios abre puertas que los hombres cierran.' },
  { id: 'juan-crisostomo-reliquias', name: 'Traslado de las reliquias de san Juan Crisóstomo', day: '01-27', category: ['padre', 'obispo'], century: 'V', place: 'Comana y Constantinopla', biography: 'Treinta años después de morir en el destierro, el pueblo de Constantinopla recibió de vuelta el cuerpo del arzobispo al que había dejado marchar. El emperador Teodosio II pidió públicamente perdón por lo que su madre le había hecho.' },
  { id: 'ciro-juan', name: 'Santos Ciro y Juan, anárgiros', day: '01-31', category: ['martir'], century: 'IV', place: 'Alejandría', biography: 'Médico y soldado († 311), martirizados en Egipto durante la persecución de Diocleciano. Como los santos Cosme y Damián, atendían sin cobrar, y curaban tanto el cuerpo como el alma de quien acudía.' },

  /* ---------------- Febrero ---------------- */
  { id: 'trifon-martir', name: 'San Trifón', day: '02-01', category: ['martir'], century: 'III', place: 'Frigia', biography: 'Pastor de ocas de Campsada († 250). Se le invoca contra las plagas del campo, y en muchos pueblos de tradición ortodoxa el día de su fiesta se bendicen las viñas.' },
  { id: 'agata-catania', name: 'Santa Águeda de Catania', day: '02-05', category: ['martir'], century: 'III', place: 'Catania, Sicilia', biography: 'Virgen y mártir siciliana († 251). Rechazó al gobernador que la pretendía y sufrió tormento por ello. Su memoria se guarda igual en Oriente y en Occidente.' },
  { id: 'teodoro-estratelates', name: 'San Teodoro Estratelates', day: '02-08', category: ['granmartir'], century: 'IV', place: 'Heraclea', biography: 'General del ejército romano († 319), de donde su título de «estratelates», jefe de tropas. Confesó la fe ante Licinio y fue ejecutado. Es, con Teodoro Tirón, uno de los dos grandes mártires soldados que la Iglesia venera con ese nombre.' },
  { id: 'blas-sebaste', name: 'San Blas de Sebaste', day: '02-11', category: ['martir', 'obispo'], century: 'IV', place: 'Sebaste, Armenia', biography: 'Obispo y médico († c. 316). Se retiró a una cueva durante la persecución y allí, cuenta la tradición, le acompañaban los animales del monte. Se le invoca por las enfermedades de la garganta.' },
  { id: 'teodoro-tiron', name: 'San Teodoro Tirón', day: '02-17', category: ['granmartir'], century: 'IV', place: 'Amasea', biography: 'Recluta del ejército —«tirón» significa eso— martirizado hacia el año 306. El primer sábado de Gran Cuaresma se le recuerda por el milagro del kolyva: avisó a los cristianos de que el alimento del mercado había sido contaminado, y les mandó comer trigo cocido con miel.' },
  { id: 'policarpo-esmirna', name: 'San Policarpo de Esmirna', day: '02-23', category: ['martir', 'obispo', 'padre'], century: 'II', place: 'Esmirna', biography: 'Obispo de Esmirna († 155) y discípulo del apóstol Juan: uno de los últimos hombres que conoció a alguien que había visto al Señor. En la hoguera respondió a quien le pedía renegar: «Ochenta y seis años le sirvo, y ningún mal me ha hecho». Su martirio es la primera acta martirial que se conserva.' },
  { id: 'cabeza-bautista', name: 'Hallazgo de la cabeza de san Juan Bautista', day: '02-24', category: ['justo'], century: 'IV', biography: 'Se conmemoran el primero y el segundo hallazgo de la reliquia del Precursor. La Iglesia hace fiesta de un hallazgo porque lo que se recobra no es un objeto, sino la memoria de quien señaló al Cordero.' },
  { id: 'porfirio-gaza', name: 'San Porfirio de Gaza', day: '02-26', category: ['obispo'], century: 'V', place: 'Gaza', biography: 'Obispo de Gaza († 420). Llegó a una ciudad donde los cristianos eran una minoría hostigada y la dejó con iglesia y hospital. Su vida, escrita por su diácono Marcos, es uno de los relatos más vivos que se conservan de aquel siglo.' },

  /* ---------------- Marzo ---------------- */
  { id: 'eudocia-heliopolis', name: 'Santa Eudocia de Heliópolis', day: '03-01', category: ['monje', 'martir'], century: 'II', place: 'Heliópolis, Siria', biography: 'Vivió de su belleza hasta que la predicación de un monje la detuvo en seco. Repartió cuanto había ganado, entró en un monasterio y murió mártir. Su historia se leyó durante siglos como prueba de que ninguna vida está perdida.' },
  { id: 'cuarenta-dos-amorion', name: 'Los cuarenta y dos mártires de Amorion', day: '03-06', category: ['martir'], century: 'IX', place: 'Amorion, Frigia', biography: 'Oficiales bizantinos capturados en la caída de Amorion († 845). Siete años de cárcel en Samarra no los movieron; les ofrecieron la libertad a cambio de la fe y respondieron que no. Fueron decapitados a orillas del Tigris.' },
  { id: 'cuarenta-sebaste', name: 'Los cuarenta mártires de Sebaste', day: '03-09', category: ['martir'], century: 'IV', place: 'Sebaste, Armenia', biography: 'Cuarenta soldados de la Legión Doce († 320) condenados a morir de frío en un lago helado, con unos baños calientes a la vista para el que se retractara. Uno salió y murió; un guardia ocupó su lugar y entró en el hielo, y siguieron siendo cuarenta.' },
  { id: 'gregorio-dialogo', name: 'San Gregorio Dialogista', day: '03-12', category: ['padre', 'obispo'], century: 'VI', place: 'Roma', biography: 'Papa de Roma († 604), llamado en Oriente «el Dialogista» por sus Diálogos. La Liturgia de los Dones Presantificados, que se celebra los días de Cuaresma, lleva su nombre. Fue de los últimos Padres venerados por igual en Oriente y Occidente antes de la separación.' },
  { id: 'padres-san-sabas', name: 'Los Padres muertos en el monasterio de San Sabas', day: '03-20', category: ['monje', 'martir'], century: 'VIII', place: 'Desierto de Judea', biography: 'Monjes de la Gran Laura degollados en una incursión. No opusieron resistencia. Su monasterio, fundado en el siglo V, sigue habitado hoy: es la comunidad monástica con vida ininterrumpida más antigua del mundo.' },

  /* ---------------- Abril ---------------- */
  { id: 'maria-egipcia', name: 'Santa María Egipcíaca', day: '04-01', category: ['monje'], century: 'V–VI', place: 'Desierto del Jordán', biography: 'Vivió diecisiete años en el desvarío de Alejandría y cuarenta y siete sola en el desierto, más allá del Jordán, sin ver rostro humano. La halló el monje Zósimo, que la sorprendió recitando de memoria unas Escrituras que nadie le había leído. Su vida se lee entera en la quinta semana de Gran Cuaresma.' },
  { id: 'jorge-megalomartir', name: 'San Jorge, el Gran Mártir', day: '04-23', category: ['granmartir'], century: 'IV', place: 'Lida, Palestina', biography: 'Oficial del ejército de Diocleciano († 303) que confesó su fe delante del emperador y fue ejecutado tras largo tormento. La tradición lo llama «Tropheóforos», el portador del trofeo. Es patrón de Grecia, Georgia, Rusia, Inglaterra, Cataluña y Aragón.' },

  /* ---------------- Mayo ---------------- */
  { id: 'atanasio-traslado', name: 'Traslado de las reliquias de san Atanasio el Grande', day: '05-02', category: ['padre', 'obispo', 'confesor'], century: 'IV', place: 'Alejandría', biography: 'Segunda conmemoración del gran arzobispo de Alejandría († 373), en el día en que sus reliquias fueron trasladadas. Su memoria principal es el 18 de enero. Pasó diecisiete de sus cuarenta y cinco años de episcopado en el destierro por no ceder ante el arrianismo.' },
  { id: 'irene-tesalonica', name: 'Santa Irene', day: '05-05', category: ['granmartir'], century: 'IV', place: 'Magedón, Persia', biography: 'Hija de un rey persa, encerrada por su padre en una torre para apartarla del mundo. Allí llegó la fe, y allí empezó una vida de predicación que acabó en martirio. Su nombre significa «paz».' },
  { id: 'cirilo-metodio', name: 'Santos Cirilo y Metodio', day: '05-11', category: ['obispo', 'confesor'], century: 'IX', place: 'Tesalónica y Moravia', biography: 'Hermanos de Tesalónica, apóstoles de los eslavos. Crearon un alfabeto para una lengua que no lo tenía y tradujeron a ella la Escritura y la Liturgia, contra quienes sostenían que sólo podía orarse en tres idiomas. De su trabajo nacen el cirílico y la cultura escrita de media Europa.' },
  { id: 'constantino-elena', name: 'Santos Constantino y Elena', day: '05-21', category: ['justo'], century: 'IV', place: 'Constantinopla y Jerusalén', biography: 'El emperador que dio libertad a la Iglesia y convocó el Concilio de Nicea, y su madre, que halló en Jerusalén la Cruz. La Iglesia los llama «iguales a los apóstoles» por lo que su decisión abrió, no por la santidad de sus vidas.' },

  /* ---------------- Junio ---------------- */
  { id: 'nicetas-remesiana', name: 'San Nicetas de Remesiana', day: '06-24', category: ['obispo'], century: 'IV–V', place: 'Remesiana, Dacia', biography: 'Obispo en los Balcanes († c. 414), evangelizador de los pueblos del Danubio. Se le atribuye el himno «Te Deum», que Oriente y Occidente siguen cantando.' },
  { id: 'natividad-bautista', name: 'Natividad de san Juan Bautista', day: '06-24', category: ['justo'], century: 'I', place: 'Judea', biography: 'Seis meses antes del nacimiento del Señor, como dice el Evangelio. Es uno de los tres nacimientos que la Iglesia celebra —el de Cristo, el de la Theotokos y el del Precursor—, porque de los demás santos se celebra la muerte.' },
  { id: 'pedro-pablo', name: 'Santos Apóstoles Pedro y Pablo', day: '06-29', category: ['apostol'], century: 'I', place: 'Roma', biography: 'Los dos «coripheos», los primeros del coro apostólico, martirizados en Roma. La Iglesia los junta en un mismo día aunque discutieron entre sí: el pescador que negó y lloró, y el perseguidor derribado camino de Damasco. Cierran el ayuno que lleva su nombre.' },
  { id: 'sinaxis-doce', name: 'Sínaxis de los Doce Apóstoles', day: '06-30', category: ['apostol'], century: 'I', biography: 'Al día siguiente de Pedro y Pablo se recuerda a los Doce juntos. Cada uno tiene su fiesta propia, pero esta reúne a todo el colegio: los que estuvieron con Él desde el bautismo de Juan hasta la Ascensión.' },

  /* ---------------- Julio ---------------- */
  { id: 'manto-theotokos', name: 'Deposición del manto de la Theotokos', day: '07-02', category: ['theotokos'], century: 'V', place: 'Blaquernas, Constantinopla', biography: 'Se conmemora el depósito del manto de la Madre de Dios en la iglesia de las Blaquernas. La ciudad atribuyó a esa protección haber resistido más de un asedio, y de ahí nace buena parte de la devoción bizantina a la Theotokos como amparo.' },
  { id: 'eufemia-calcedonia', name: 'Santa Eufemia', day: '07-11', category: ['granmartir'], century: 'IV', place: 'Calcedonia', biography: 'En este día no se conmemora su martirio —que es el 16 de septiembre— sino lo que ocurrió siglo y medio después. En 451, los Padres del Cuarto Concilio Ecuménico se reunieron en la basílica de Calcedonia que guardaba sus reliquias, y la tradición cuenta que depositaron sobre su sepulcro los dos escritos enfrentados y hallaron el ortodoxo en sus manos. Sea cual fuere el hecho, la fe de Calcedonia lleva desde entonces el nombre de una muchacha martirizada allí mismo.' },
  { id: 'padres-seis-concilios', name: 'Los Padres de los seis primeros Concilios', day: '07-16', category: ['padre'], century: 'IV–VIII', biography: 'Se conmemora a los obispos reunidos en Nicea, Constantinopla, Éfeso, Calcedonia y los dos concilios constantinopolitanos siguientes. No se celebra su erudición, sino que supieron decir lo que la Iglesia creía cuando hizo falta decirlo.' },

  /* ---------------- Agosto ---------------- */
  { id: 'procesion-cruz-ago', name: 'Procesión de la Preciosa Cruz', day: '08-01', category: ['senor'], century: 'IX', place: 'Constantinopla', biography: 'Se sacaba la reliquia de la Cruz por las calles de Constantinopla para pedir por la ciudad en el mes más duro del verano. Abre el ayuno de la Dormición. Ese día se hace también la pequeña bendición de las aguas.' },
  { id: 'transfiguracion', name: 'La Transfiguración del Señor', day: '08-06', category: ['senor'], century: 'I', place: 'Monte Tabor', biography: 'Cristo se transfigura ante Pedro, Santiago y Juan, y aparecen Moisés y Elías. La luz del Tabor está en el centro de la teología hesicasta: no es un símbolo, sino la energía increada de Dios, que el hombre puede ver sin ver su esencia. Ese día se bendicen las uvas.' },
  { id: 'dormicion', name: 'La Dormición de la Theotokos', day: '08-15', category: ['theotokos'], century: 'I', place: 'Jerusalén', biography: 'La Madre de Dios entrega su alma en manos de su Hijo. Los iconos la muestran acostada, y a Cristo de pie sosteniendo un niño en brazos: su alma. Es la última de las doce grandes fiestas del año litúrgico, que empieza en septiembre y termina aquí.' },
  { id: 'mandylion', name: 'Traslado de la Santa Imagen no hecha por mano', day: '08-16', category: ['senor'], century: 'X', place: 'Edesa y Constantinopla', biography: 'El Mandylion, el lienzo con el rostro del Señor que la tradición hace llegar al rey Abgar de Edesa. Su traslado a Constantinopla en 944 se celebra como fiesta, y es el argumento más citado a favor de los iconos: si Dios se hizo visible, puede pintarse.' },

  /* ---------------- Septiembre ---------------- */
  { id: 'natividad-theotokos', name: 'Natividad de la Theotokos', day: '09-08', category: ['theotokos'], century: 'I', place: 'Jerusalén', biography: 'El nacimiento de María, hija de Joaquín y Ana en su vejez. Es la primera de las doce grandes fiestas del año litúrgico: la historia de la salvación empieza con el nacimiento de una niña de la que nadie esperaba nada.' },
  { id: 'exaltacion-cruz', name: 'Exaltación de la Preciosa Cruz', day: '09-14', category: ['senor'], century: 'IV', place: 'Jerusalén', biography: 'Se conmemora el hallazgo de la Cruz por santa Elena y su elevación ante el pueblo por el patriarca Macario. Es día de ayuno estricto en plena fiesta: no se celebra un triunfo sin recordar cómo se ganó.' },
  { id: 'sofia-hijas', name: 'Santa Sofía y sus hijas Fe, Esperanza y Caridad', day: '09-17', category: ['martir'], century: 'II', place: 'Roma', biography: 'Una madre que vio morir a sus tres hijas —de doce, diez y nueve años— y murió tres días después sobre sus tumbas. Los nombres son los de las tres virtudes, y la tradición los ha guardado así, como una catequesis en cuatro nombres.' },
  { id: 'juan-teologo-sep', name: 'Reposo de san Juan el Teólogo', day: '09-26', category: ['apostol'], century: 'I', place: 'Éfeso', biography: 'El único de los Doce que no murió mártir. Anciano en Éfeso, cuentan que repetía a sus discípulos una sola frase: «Hijitos, amaos los unos a los otros», y que al preguntarle por qué no decía otra cosa respondió que, si se cumplía aquélla, bastaba.' },

  /* ---------------- Octubre ---------------- */
  { id: 'proteccion-theotokos', name: 'Protección de la Theotokos', day: '10-01', category: ['theotokos'], century: 'X', place: 'Blaquernas, Constantinopla', biography: 'San Andrés el Loco por Cristo vio a la Madre de Dios extendiendo su manto sobre los fieles reunidos en las Blaquernas mientras la ciudad estaba sitiada. La fiesta —Pokrov en las Iglesias eslavas— es una de las más queridas de la tradición rusa.' },
  { id: 'padres-septimo-concilio', name: 'Los Padres del Séptimo Concilio Ecuménico', day: '10-11', category: ['padre'], century: 'VIII', place: 'Nicea', biography: 'Los obispos reunidos en Nicea en 787, que restablecieron la veneración de los iconos. Distinguieron entre la adoración, que sólo a Dios se debe, y la veneración, que pasa a través de la imagen hasta quien está representado en ella.' },

  /* ---------------- Noviembre ---------------- */
  { id: 'arcangeles', name: 'Sínaxis de los Arcángeles Miguel y Gabriel', day: '11-08', category: ['justo'], biography: 'La fiesta de todas las potestades incorpóreas: Miguel, que capitanea el ejército celestial, y Gabriel, que anuncia. La Iglesia los recuerda en noviembre, el noveno mes desde marzo, por los nueve coros angélicos.' },
  { id: 'juan-crisostomo', name: 'San Juan Crisóstomo', day: '11-13', category: ['padre', 'obispo'], century: 'IV–V', place: 'Constantinopla', biography: 'Arzobispo de Constantinopla († 407), «boca de oro» por su predicación. Desterrado dos veces por decir la verdad a la corte, murió camino del exilio con las palabras «Gloria a Dios por todas las cosas». Su Liturgia es la que se celebra casi todos los domingos del año.' },
  { id: 'andres-apostol', name: 'San Andrés el Primer Llamado', day: '11-30', category: ['apostol'], century: 'I', place: 'Patras', biography: 'El primero a quien el Señor llamó, y quien llevó a su hermano Pedro. Predicó por el mar Negro y murió crucificado en Patras sobre una cruz en aspa. Es el apóstol fundador de la Iglesia de Constantinopla y patrón de Grecia, Rusia y Escocia.' },

  /* ---------------- Diciembre ---------------- */
  { id: 'barbara-martir', name: 'Santa Bárbara', day: '12-04', category: ['granmartir'], century: 'III–IV', place: 'Heliópolis', biography: 'Encerrada por su padre en una torre, mandó abrir en ella una tercera ventana en honor de la Trinidad († c. 306). Es patrona de los mineros y de cuantos trabajan con explosivos, y se la invoca por una buena muerte.' },
  { id: 'nicolas-mira-dic', name: 'San Nicolás de Mira', day: '12-06', category: ['obispo'], century: 'IV', place: 'Mira, Licia', biography: 'Obispo de Mira († c. 343), el santo más representado después de la Theotokos. Salvó de la miseria a tres muchachas dejando el oro de sus dotes por la ventana, de donde viene toda la costumbre de los regalos de invierno. Se le invoca por los que navegan y por los que van de camino.' },
  { id: 'espiridon-trimitunte', name: 'San Espiridón de Trimitunte', day: '12-12', category: ['obispo'], century: 'IV', place: 'Chipre y Corfú', biography: 'Pastor de ovejas que llegó a obispo († 348) y acudió al Concilio de Nicea vestido como lo que era. Cuentan que explicó la Trinidad apretando un ladrillo del que salieron fuego, agua y barro. Su cuerpo se venera incorrupto en Corfú.' },
  { id: 'ignacio-antioquia-dic', name: 'San Ignacio de Antioquía', day: '12-20', category: ['martir', 'obispo', 'padre'], century: 'I–II', place: 'Antioquía y Roma', biography: 'Obispo de Antioquía († c. 107), llevado a Roma para morir en el circo. En las siete cartas que escribió por el camino aparece por primera vez la palabra «católica» aplicada a la Iglesia, y pidió a los cristianos de Roma que no impidieran su martirio.' },
  { id: 'natividad-senor', name: 'La Natividad de Cristo', day: '12-25', category: ['senor'], century: 'I', place: 'Belén', biography: 'Dios se hace hombre. Los tropiarios de la fiesta no hablan de un niño tierno, sino de que lo increado entra en lo creado: «Hoy la Virgen da a luz al Trascendente, y la tierra ofrece una cueva al Inaccesible». La segunda gran fiesta del año, después de la Pascua.' },
  { id: 'sinaxis-theotokos', name: 'Sínaxis de la Theotokos', day: '12-26', category: ['theotokos'], century: 'I', biography: 'Al día siguiente de Navidad, la Iglesia se vuelve hacia la Madre. Es la costumbre bizantina: después de cada gran fiesta se recuerda a quien fue instrumento de ella, y aquí no puede ser otra.' },
];
