/**
 * El año completo, primera mitad: de enero a junio.
 *
 * Con esta tanda y la siguiente, los 366 días del calendario tienen al menos
 * una conmemoración escrita. Antes había 197 días en blanco, y un calendario
 * con huecos empuja a saltárselo justo los días corrientes, que son casi
 * todos.
 *
 * Las fechas son las del calendario eclesiástico —el mismo que usa el
 * Menaion—, no las civiles: quien siga el calendario nuevo verá cada
 * conmemoración en el día civil que le corresponda, y ATHOS hace esa cuenta.
 *
 * Criterio, el de siempre: las reseñas son historia redactada para ATHOS a
 * partir de fuentes hagiográficas comunes. No son textos litúrgicos y no se
 * presentan como tales. Ningún tropario se inventa: donde no hay versión
 * española verificable, la ficha lo dice.
 */
import type { SaintCategory } from '@/types';

export interface SaintSeedYear {
  id: string;
  name: string;
  fullName?: string;
  day: string;
  category: SaintCategory[];
  century?: string;
  place?: string;
  biography: string;
}

export const YEAR_SAINTS_1: SaintSeedYear[] = [
  /* ═══════════════ Enero ═══════════════ */
  { id: 'sinclitica-alejandria', name: 'Santa Sinclética de Alejandría', day: '01-05', category: ['monje'], century: 'IV', place: 'Alejandría', biography: 'Hija de una familia rica de Alejandría († c. 350). Al morir sus padres repartió la herencia, se cortó el cabello y se retiró con su hermana ciega a un sepulcro abandonado en las afueras. Las mujeres empezaron a buscarla y acabó siendo maestra de muchas. Los dichos que se le atribuyen figuran entre los pocos de mujeres que conserva el Gerontikón: «Al principio hay lucha y fatiga para los que se acercan a Dios, y después alegría indecible». Murió de un cáncer que la consumió tres años sin arrancarle una queja.' },
  { id: 'domnica-constantinopla', name: 'Santa Domnica de Constantinopla', day: '01-08', category: ['monje'], century: 'IV–V', place: 'Constantinopla', biography: 'Llegó de Cartago a Constantinopla en tiempos de Teodosio y fue bautizada por el patriarca Nectario († c. 474). Fundó un monasterio junto a la iglesia del profeta Zacarías y vivió allí más de setenta años. Se cuenta que los marineros del Bósforo pedían su oración antes de zarpar.' },
  { id: 'hermilo-estratonico', name: 'Santos Hermilo y Estratónico', day: '01-13', category: ['martir'], century: 'IV', place: 'Singidunum, el Danubio', biography: 'Un diácono y el carcelero que lo custodiaba, martirizados hacia el año 315 en la actual Belgrado. Estratónico se delató a sí mismo llorando al ver los tormentos de Hermilo. Los ataron juntos en una red y los echaron al Danubio; los cuerpos aparecieron a dos leguas, todavía unidos.' },
  { id: 'nina-georgia', name: 'Santa Nina de Georgia', fullName: 'Santa Nina, igual a los Apóstoles, iluminadora de Georgia', day: '01-14', category: ['justo'], century: 'IV', place: 'Mtsjeta, Georgia', biography: 'Cautiva cristiana llevada a Iberia del Cáucaso († c. 335). Sin ordenación ni encargo de nadie, su vida y sus curaciones convencieron primero a la reina Nana y luego al rey Mirian, y Georgia se hizo cristiana por decisión del reino entero, la segunda nación en hacerlo. La cruz de sarmientos de vid atada con su propio cabello sigue siendo el emblema de la Iglesia georgiana.' },
  { id: 'clemente-ancira', name: 'San Clemente de Ancira', day: '01-23', category: ['obispo', 'martir'], century: 'III–IV', place: 'Ancira, Galacia', biography: 'Obispo de Ancira († c. 312). Su martirio duró veintiocho años, repartido entre siete emperadores y varias provincias: la tradición lo presenta como el caso extremo de una persecución que se alargaba hasta el absurdo. Murió degollado mientras celebraba la Liturgia.' },
  { id: 'xenofonte-familia', name: 'San Xenofonte y su familia', day: '01-26', category: ['justo'], century: 'V–VI', place: 'Constantinopla y Beirut', biography: 'Un matrimonio acomodado de Constantinopla y sus dos hijos, Juan y Arcadio, que fueron a estudiar leyes a Beirut y naufragaron. Los padres los dieron por muertos y peregrinaron a Jerusalén; allí los encontraron, vivos y ya monjes. Los cuatro terminaron sus días en el desierto de Palestina.' },

  /* ═══════════════ Febrero ═══════════════ */
  { id: 'lucas-estirio', name: 'San Lucas de Estirio', fullName: 'Hósios Lukás', day: '02-07', category: ['monje'], century: 'X', place: 'Fócide, Grecia', biography: 'Ermitaño del Helicón († 953). Vivió de un huerto que cultivaba él mismo y anunció con años de antelación la reconquista bizantina de Creta, que se cumplió en 961. Sobre su tumba se levantó el monasterio de Hósios Lukás, cuyos mosaicos del siglo XI están entre los mejor conservados del arte bizantino medio.' },
  { id: 'niceforo-antioquia', name: 'San Nicéforo de Antioquía', day: '02-09', category: ['martir'], century: 'III', place: 'Antioquía', biography: 'Mártir del año 257 cuya historia se cuenta por lo que enseña. Nicéforo se había peleado con el presbítero Saprikio; cuando llevaban a Saprikio al martirio, Nicéforo le salió al paso una y otra vez pidiéndole perdón, y el otro se negó. Al llegar al lugar de la ejecución, Saprikio abjuró; Nicéforo se declaró cristiano en su lugar y murió por él. La Iglesia lo lee cada año como aviso: sin perdón, ni el martirio sirve.' },
  { id: 'simeon-mirobleta', name: 'San Simeón el Mirobleta', fullName: 'San Simeón, antes Esteban Nemanja, gran zhupán de Serbia', day: '02-13', category: ['monje'], century: 'XII–XIII', place: 'Monte Athos', biography: 'Fundador del Estado serbio medieval († 1199). Abdicó a los setenta años, tomó el hábito con el nombre de Simeón y se fue al Athos con su hijo, san Sava; juntos restauraron Hilandar. De su tumba manó el mirra que le dio el sobrenombre, y de la pared del monasterio sigue brotando la vid que la tradición hace nacer de ella.' },
  { id: 'panfilo-cesarea', name: 'San Pánfilo y sus compañeros', day: '02-16', category: ['martir'], century: 'III–IV', place: 'Cesarea de Palestina', biography: 'Presbítero de Cesarea († 309) y bibliotecario de la escuela que había fundado Orígenes. Copió de su mano ejemplares enteros de la Escritura para regalarlos y trabajó dos años en la cárcel, antes de ser decapitado con once compañeros. Eusebio, que lo tenía por maestro, tomó su nombre —«el de Pánfilo»— y le dedicó una biografía hoy perdida.' },
  { id: 'arquipo-filemon', name: 'Santos Arquipo, Filemón y Apia', day: '02-19', category: ['apostol', 'martir'], century: 'I', place: 'Colosas', biography: 'La casa de Colosas a la que san Pablo escribió pidiendo que recibieran a Onésimo «no ya como esclavo, sino como hermano amado». En ella se reunía la comunidad. La tradición los hace morir apedreados durante una fiesta de Artemisa.' },
  { id: 'leon-catania', name: 'San León de Catania', day: '02-20', category: ['obispo'], century: 'VIII', place: 'Catania, Sicilia', biography: 'Obispo de Catania († c. 785), recordado por su porfía en atender a los pobres de la ciudad y por levantar una iglesia sobre el sepulcro de santa Lucía. Sicilia era entonces territorio bizantino y su vida es uno de los pocos testimonios de la Iglesia griega de la isla.' },
  { id: 'eustacio-antioquia', name: 'San Eustacio de Antioquía', day: '02-21', category: ['obispo', 'confesor'], century: 'IV', place: 'Antioquía', biography: 'Arzobispo de Antioquía († c. 337) y uno de los que más firmemente sostuvieron el «consustancial» en el Concilio de Nicea. Los arrianos lo depusieron con acusaciones fabricadas y lo desterraron a Tracia, donde murió; sus fieles, los llamados eustacianos, siguieron reuniéndose aparte durante ochenta años y dividieron Antioquía en un cisma que costó generaciones cerrar.' },
  { id: 'talasio-limneo', name: 'Santos Talasio y Limneo', day: '02-22', category: ['monje'], century: 'V', place: 'Siria', biography: 'Dos ascetas del norte de Siria de quienes escribió Teodoreto de Ciro, que los conoció. Limneo, ciego de nacimiento, vivía a la intemperie en un cercado de piedra y aprendió a curar heridas de mordedura; construyó dos albergues para mendigos ciegos junto a su celda y los mantuvo con las limosnas que le llevaban.' },
  { id: 'procopio-decapolita', name: 'San Procopio el Decapolita', day: '02-27', category: ['monje', 'confesor'], century: 'VIII–IX', place: 'Decápolis y Constantinopla', biography: 'Monje († c. 750) encarcelado y azotado bajo León III el Isaurio por negarse a entregar los iconos. Salió de la cárcel al morir el emperador y vivió sus últimos años enseñando a los monjes jóvenes lo que había aprendido dentro.' },
  { id: 'basilio-confesor', name: 'San Basilio el Confesor', day: '02-28', category: ['monje', 'confesor'], century: 'VIII–IX', place: 'Constantinopla', biography: 'Compañero de celda y de prisión de san Procopio († 750). Sufrió los mismos tormentos y sobrevivió a ellos; la Iglesia los conmemora en días seguidos, como vivieron.' },
  { id: 'juan-casiano', name: 'San Juan Casiano el Romano', day: '02-29', category: ['monje', 'padre'], century: 'IV–V', place: 'Escitia Menor, Belén, Egipto y Marsella', biography: 'Monje nacido en la actual Dobruja († c. 435). Pasó años entre los ascetas de Egipto tomando nota de lo que decían y llevó esa experiencia a la Galia, donde fundó dos monasterios en Marsella. Sus Instituciones y sus Conferencias son el puente por el que el monacato del desierto llegó a Occidente; san Benito manda leerlas en su Regla. Se le conmemora el 29 de febrero, de modo que su fiesta sólo cae en los años bisiestos: en los demás se traslada al día anterior.' },

  /* ═══════════════ Marzo ═══════════════ */
  { id: 'teodoto-cirene', name: 'San Teodoto de Cirene', day: '03-02', category: ['obispo', 'martir'], century: 'IV', place: 'Cirene, Chipre', biography: 'Obispo de Cirene en Chipre († c. 326). Torturado bajo Licinio y liberado por el edicto de Constantino, volvió a su sede tan quebrantado que murió a los dos años. Es uno de los últimos mártires de la persecución imperial en Oriente.' },
  { id: 'eutropio-cleonico', name: 'Santos Eutropio, Cleónico y Basilisco', day: '03-03', category: ['martir'], century: 'IV', place: 'Amasea del Ponto', biography: 'Compañeros de armas de san Teodoro el Tirón († 308). Cuando el gobernador les ofreció riquezas por sacrificar, Eutropio respondió que ya habían visto lo que valían las promesas del Imperio. Los tres fueron crucificados.' },
  { id: 'marcos-asceta', name: 'San Marcos el Asceta', day: '03-05', category: ['monje', 'padre'], century: 'IV–V', place: 'Egipto o Ancira', biography: 'Escritor espiritual del que apenas se sabe nada seguro, ni siquiera dónde vivió. Lo que dejó, en cambio, se lee sin interrupción desde hace mil quinientos años: la Filocalia se abre casi con sus tratados. Su tesis es que la gracia está entera en el bautizado desde el bautismo, y que la vida cristiana no consiste en conseguirla sino en descubrirla bajo lo que la tapa. Un dicho antiguo decía: «Vende cuanto tienes y compra a Marcos».' },
  { id: 'teofilacto-nicomedia', name: 'San Teofilacto de Nicomedia', day: '03-08', category: ['obispo', 'confesor'], century: 'VIII–IX', place: 'Nicomedia', biography: 'Obispo de Nicomedia († c. 845). Cuando León V el Armenio reabrió la persecución de los iconos, Teofilacto le dijo a la cara que Dios le pediría cuentas; el emperador lo desterró a Caria treinta años, hasta su muerte. Sus reliquias volvieron a Nicomedia en 845, restablecida ya la veneración de las imágenes.' },
  { id: 'codrato-corinto', name: 'San Codrato de Corinto y sus compañeros', day: '03-10', category: ['martir'], century: 'III', place: 'Corinto', biography: 'Grupo de mártires corintios († 251 o 258). Codrato había nacido en el campo, de una madre que huía de la persecución y murió al darlo a luz; se cuenta que se crió solo. Arrastró consigo a los demás en la confesión de la fe y fue decapitado con ellos.' },
  { id: 'niceforo-traslacion', name: 'San Nicéforo de Constantinopla', fullName: 'Traslación de las reliquias de san Nicéforo, patriarca de Constantinopla', day: '03-13', category: ['obispo', 'confesor'], century: 'VIII–IX', place: 'Constantinopla', biography: 'Patriarca depuesto en 815 por defender los iconos y muerto en el destierro en 828. En 846, restablecida la ortodoxia, sus reliquias volvieron a la ciudad y fueron depositadas en la iglesia de los Santos Apóstoles. La Iglesia conmemora ese regreso porque significaba algo más que un traslado: era la sentencia revocada en público.' },
  { id: 'agapio-cesarea', name: 'San Agapio y sus compañeros', day: '03-15', category: ['martir'], century: 'IV', place: 'Cesarea de Palestina', biography: 'Siete mártires ejecutados en el anfiteatro de Cesarea en 303. Eusebio, que estaba en la ciudad, cuenta que Agapio fue expuesto a las fieras tres veces distintas en días de espectáculo y que el gobernador lo devolvía a la cárcel cada vez para prolongar la humillación.' },
  { id: 'cristodulo-patmos', name: 'San Cristódulo de Patmos', day: '03-16', category: ['monje'], century: 'XI', place: 'Patmos', biography: 'Monje bitinio († 1093) que obtuvo del emperador Alejo Comneno la isla entera de Patmos, entonces despoblada, para fundar en ella un monasterio sobre la cueva donde la tradición sitúa el Apocalipsis. El crisóbulo imperial y el testamento que escribió de su mano se conservan todavía allí, y el monasterio no ha dejado de estar habitado desde entonces.' },
  { id: 'crisanto-daria', name: 'Santos Crisanto y Daría', day: '03-19', category: ['martir'], century: 'III', place: 'Roma', biography: 'Matrimonio romano martirizado hacia 283. Él era hijo de un senador y se convirtió leyendo los Hechos de los Apóstoles; ella, sacerdotisa de Minerva enviada a apartarlo de la fe, acabó compartiéndola. Fueron enterrados vivos en una cantera de la vía Salaria.' },
  { id: 'jacobo-confesor', name: 'San Jacobo el Confesor', day: '03-21', category: ['obispo', 'confesor'], century: 'VIII–IX', place: 'Studion, Constantinopla', biography: 'Monje del Studion y luego obispo († c. 833). Bajo León V el Armenio fue azotado, encarcelado y dejado sin comer durante años por no firmar la condena de los iconos. Salió con la salud rota y murió poco después de recobrar la libertad.' },
  { id: 'basilio-ancira', name: 'San Basilio de Ancira', day: '03-22', category: ['martir'], century: 'IV', place: 'Ancira, Galacia', biography: 'Presbítero martirizado en 362, en la breve restauración pagana de Juliano. Había recorrido la ciudad exhortando a los cristianos a no ceder cuando el emperador devolvió los templos al culto antiguo; lo prendieron por eso y murió en el tormento.' },
  { id: 'nicon-martir', name: 'San Nicón y sus discípulos', day: '03-23', category: ['martir'], century: 'III', place: 'Sicilia', biography: 'Antiguo soldado romano hecho monje en Oriente († c. 251) que pasó a Sicilia con un grupo de discípulos. Fueron sorprendidos allí durante la persecución de Decio y ejecutados todos; la tradición cuenta ciento noventa y nueve compañeros.' },
  { id: 'artemon-seleucia', name: 'San Artemón de Seleucia', day: '03-24', category: ['obispo'], century: 'I–II', place: 'Seleucia de Pisidia', biography: 'Primer obispo de Seleucia de Pisidia, ordenado según la tradición por el apóstol san Pablo. Se le conmemora la víspera de la Anunciación, en el día que la Iglesia llama de preparación: los grandes días no empiezan por la mañana, sino la tarde antes.' },
  { id: 'sinaxis-gabriel', name: 'Sinaxis del Arcángel Gabriel', day: '03-26', category: ['senor'], biography: 'Al día siguiente de la Anunciación, la Iglesia honra al que la trajo. Es una costumbre bizantina antigua: después de una gran fiesta se conmemora a quien tuvo en ella el papel principal después del protagonista. Así, tras la Navidad viene la Theotokos, tras la Teofanía el Bautista y tras la Anunciación el arcángel Gabriel, el que «está delante de Dios» y fue enviado tres veces según la Escritura: a Daniel, a Zacarías y a Nazaret.' },
  { id: 'matrona-tesalonica', name: 'Santa Matrona de Tesalónica', day: '03-27', category: ['martir'], century: 'III–IV', place: 'Tesalónica', biography: 'Esclava de una señora judía de Tesalónica. Acompañaba a su ama a la sinagoga y se escapaba a orar a la iglesia; descubierta, fue encerrada y golpeada hasta morir. Es de las pocas mártires de las que la tradición conserva la condición social, que en su caso lo explica todo.' },
  { id: 'hilarion-nuevo', name: 'San Hilarión el Nuevo', day: '03-28', category: ['monje', 'confesor'], century: 'VIII–IX', place: 'Pelekete, Bitinia', biography: 'Higúmeno del monasterio de Pelekete († 754). El emperador Constantino V mandó asaltar el monasterio un Jueves Santo: los monjes fueron apresados en plena Liturgia, el edificio quemado y muchos ahogados en el mar. Hilarión murió en la cárcel de Éfeso.' },
  { id: 'marcos-aretusa', name: 'San Marcos de Aretusa y el diácono Cirilo', day: '03-29', category: ['obispo', 'martir'], century: 'IV', place: 'Aretusa, Siria', biography: 'Obispo sirio martirizado en 362. Había derribado un templo pagano en tiempos de Constancio; cuando Juliano restauró el culto antiguo, la ciudad se lo cobró: lo pasearon desnudo por las calles, lo colgaron de un árbol untado de miel para las avispas y le exigieron pagar la reconstrucción. Se negó a dar una sola moneda. Sus verdugos acabaron soltándolo, y hasta el propio Juliano prohibió por escrito que se le tocara de nuevo.' },
  { id: 'hipacio-gangra', name: 'San Hipacio de Gangra', day: '03-31', category: ['obispo', 'martir'], century: 'IV', place: 'Gangra, Paflagonia', biography: 'Obispo de Gangra († c. 326) y uno de los Padres del Concilio de Nicea. Volviendo de Constantinopla fue emboscado por un grupo de novacianos que lo apedrearon y lo arrojaron a un barranco. Murió pidiendo perdón para ellos.' },

  /* ═══════════════ Abril ═══════════════ */
  { id: 'niceta-medikion', name: 'San Niceta el Confesor', day: '04-03', category: ['monje', 'confesor'], century: 'VIII–IX', place: 'Medikion, Bitinia', biography: 'Higúmeno del monasterio de Medikion († 824). Desterrado por León V el Armenio, cedió un momento y firmó la condena de los iconos; se arrepintió enseguida, se retractó en público y volvió al destierro por su propia voluntad. La Iglesia lo cuenta entre los confesores sin ocultar la caída, porque la caída es parte de lo que enseña.' },
  { id: 'agatopodo-teodulo', name: 'Santos Agatópodo y Teódulo', day: '04-05', category: ['martir'], century: 'IV', place: 'Tesalónica', biography: 'Un diácono anciano y un lector joven de la iglesia de Tesalónica, ahogados en 303 por negarse a entregar los libros sagrados durante la persecución de Diocleciano. Lo que se les pedía no era abjurar, sino sólo dar los códices; entendieron que era lo mismo.' },
  { id: 'jorge-mitilene', name: 'San Jorge de Mitilene', day: '04-07', category: ['obispo', 'confesor'], century: 'IX', place: 'Lesbos', biography: 'Obispo de Mitilene († 816), desterrado a Quersoneso por defender las imágenes. Su isla lo recordaba sobre todo por el reparto de grano que organizaba en los años de hambre, de modo que ninguna casa quedara sin nada.' },
  { id: 'herodion-agabo', name: 'Los apóstoles Herodión, Agabo, Rufo y sus compañeros', day: '04-08', category: ['apostol'], century: 'I', biography: 'Seis de los Setenta discípulos, nombrados casi todos en el capítulo final de la carta a los Romanos. Agabo es el profeta que en los Hechos anuncia el hambre y la prisión de Pablo. La Iglesia mantiene el recuerdo de los Setenta junto al de los Doce para que no se olvide que el Evangelio se extendió por muchas más manos de las que dan nombre a los libros.' },
  { id: 'eupsiquio-cesarea', name: 'San Eupsiquio de Cesarea', day: '04-09', category: ['martir'], century: 'IV', place: 'Cesarea de Capadocia', biography: 'Noble capadocio martirizado en 362 por haber participado en la destrucción del templo de la Fortuna. Juliano castigó a la ciudad entera confiscando los bienes de la Iglesia y borrándola de la lista de ciudades. San Basilio, que era de allí, escribió varias cartas invitando a obispos amigos a su fiesta anual.' },
  { id: 'gregorio-v', name: 'San Gregorio V de Constantinopla', day: '04-10', category: ['obispo', 'neomartir'], century: 'XVIII–XIX', place: 'Constantinopla', biography: 'Patriarca ecuménico ahorcado el domingo de Pascua de 1821 en la puerta central del Patriarcado, en represalia por el levantamiento griego que él mismo había condenado por escrito. El cuerpo estuvo colgado tres días y fue arrojado al Bósforo; unos marinos lo recogieron y lo llevaron a Odesa. La puerta sigue tapiada desde entonces. Su figura es a la vez venerada y discutida, porque la condena que firmó no le sirvió de nada.' },
  { id: 'basilio-parios', name: 'San Basilio de Parios', day: '04-12', category: ['obispo', 'confesor'], century: 'VIII', place: 'Paros', biography: 'Obispo de Paros († c. 750). Se negó a firmar el decreto iconoclasta del concilio de Hieria y perdió su sede; pasó el resto de su vida escondido, sin dejar de administrar los sacramentos a los que lo buscaban.' },
  { id: 'maximo-quintiliano-dadas', name: 'Santos Máximo, Cuintiliano y Dadas', day: '04-13', category: ['martir'], century: 'IV', place: 'Ozovia, Mesia', biography: 'Tres campesinos del bajo Danubio martirizados hacia 286. Sus actas son de las pocas que dejan oír a gente sin instrucción ante un tribunal: no citan filósofos ni Escrituras, sólo repiten que no pueden adorar lo que no hizo el cielo. El juez insistió en que bastaba un gesto y ninguno lo hizo. En este mismo mes, el día 14, se conmemora a san Martín el Confesor, papa de Roma.' },
  { id: 'agapia-irene-quionia', name: 'Santas Agapia, Irene y Quionia', day: '04-16', category: ['martir'], century: 'IV', place: 'Tesalónica', biography: 'Tres hermanas quemadas vivas en 304. Se conservan las actas del juicio, que son de las más antiguas que existen: el prefecto Dulcicio no las acusa de nada salvo de guardar libros cristianos y negarse a comer carne sacrificada. Irene, la menor, sobrevivió unos días a sus hermanas porque se buscaba que declarase quién le había dado los códices; no lo dijo.' },
  { id: 'simeon-persia', name: 'San Simeón de Persia y sus compañeros', day: '04-17', category: ['obispo', 'martir'], century: 'IV', place: 'Seleucia-Ctesifonte', biography: 'Obispo de la capital persa († 344). El rey Sapor II impuso a los cristianos un impuesto doble por sospecha de simpatía con el Imperio romano; Simeón se negó a recaudarlo y fue ejecutado un Viernes Santo con más de cien clérigos, degollados uno tras otro ante sus ojos. Empezaba así una persecución de cuarenta años, la mayor que sufrió la Iglesia fuera del Imperio.' },
  { id: 'juan-yanina', name: 'San Juan el Nuevo de Yánina', day: '04-18', category: ['neomartir'], century: 'XVI', place: 'Constantinopla', biography: 'Artesano epirota († 1526) que trabajaba en Constantinopla. Unos vecinos aseguraron que se había hecho musulmán y lo denunciaron por apostasía cuando siguió yendo a la iglesia. Se negó a confirmar lo que nunca había dicho y murió quemado. Es uno de los primeros neomártires del período otomano, el largo capítulo del santoral que va de 1453 a 1821.' },
  { id: 'anastasio-sinaita', name: 'San Anastasio del Sinaí', day: '04-20', category: ['monje', 'padre'], century: 'VII', place: 'Monte Sinaí', biography: 'Monje del Sinaí († c. 700). Recorrió Egipto, Siria y Palestina discutiendo con monofisitas en los años en que el Imperio acababa de perder aquellas provincias, y escribió el Hodegós o Guía, un manual para sostener esas conversaciones. También reunió relatos de los Padres del Sinaí que son fuente casi única sobre la vida allí tras la conquista árabe.' },
  { id: 'jenaro-benevento', name: 'San Jenaro y sus compañeros', day: '04-21', category: ['obispo', 'martir'], century: 'III–IV', place: 'Nápoles', biography: 'Obispo de Benevento († c. 305), decapitado en Pozzuoli con su diácono y su lector durante la persecución de Diocleciano. Venerado en Oriente y en Occidente, es el patrono de Nápoles; su sangre conservada en la catedral es objeto de una devoción popular que la Iglesia nunca ha declarado obligatoria.' },
  { id: 'sabas-estratelates', name: 'San Sabas Estratelates', day: '04-24', category: ['martir'], century: 'III', place: 'Roma', biography: 'Oficial godo del ejército romano († 272). Visitaba a los cristianos presos y les llevaba comida hasta que lo delataron; entregó el cinturón militar antes de que se lo quitaran. Fue ahogado en un río con setenta soldados de su unidad que se declararon cristianos al verlo condenado.' },
  { id: 'basileo-amasea', name: 'San Basileo de Amasea', day: '04-26', category: ['obispo', 'martir'], century: 'IV', place: 'Amasea del Ponto', biography: 'Obispo de Amasea († 322), ejecutado por Licinio en los últimos años de su enfrentamiento con Constantino. El motivo fue haber dado refugio a Glafira, una sirvienta de la emperatriz que huía del acoso del propio Licinio. Es uno de los pocos martirios documentados cuyo origen no es un edicto, sino una venganza personal.' },
  { id: 'nueve-cizico', name: 'Los Nueve Mártires de Cízico', day: '04-28', category: ['martir'], century: 'III–IV', place: 'Cízico, Misia', biography: 'Nueve hombres de edades y oficios distintos —un soldado, un campesino, un médico, un anciano, un muchacho— que se presentaron juntos ante el gobernador de Cízico y se declararon cristianos en una ciudad donde casi no quedaban. Fueron decapitados. Sus reliquias se recuperaron bajo Constantino y san Basilio predicó en su fiesta.' },
  { id: 'jason-sosipatro', name: 'Santos Jasón y Sosípatro', day: '04-29', category: ['apostol'], century: 'I', place: 'Corfú', biography: 'Dos de los Setenta, nombrados por san Pablo en la carta a los Romanos. Predicaron en Corfú, donde fueron encarcelados; la tradición cuenta que convirtieron a siete presos comunes y a la hija del rey. La iglesia que guarda su memoria en la isla es del siglo XI y sigue en pie.' },
  { id: 'santiago-zebedeo', name: 'Santiago el Apóstol', fullName: 'San Santiago, hijo de Zebedeo, hermano de san Juan el Teólogo', day: '04-30', category: ['apostol', 'martir'], century: 'I', place: 'Jerusalén', biography: 'Uno de los Doce y el primero de ellos en morir: Herodes Agripa lo hizo decapitar hacia el año 44, y los Hechos lo cuentan en una sola frase. Estuvo con Pedro y Juan en el Tabor y en Getsemaní. Una tradición occidental muy antigua lo hace predicar en Hispania y lleva su cuerpo a Compostela; la Iglesia ortodoxa conmemora su martirio sin pronunciarse sobre aquel viaje.' },

  /* ═══════════════ Mayo ═══════════════ */
  { id: 'profeta-jeremias', name: 'Profeta Jeremías', day: '05-01', category: ['profeta'], century: 'VII–VI a.C.', place: 'Judá y Egipto', biography: 'Llamado siendo casi un niño y obligado a anunciar durante cuarenta años una ruina que nadie quería oír. Lo metieron en un aljibe, le quemaron el rollo delante y lo acusaron de traidor por decir que Babilonia vencería. Vio cumplirse todo lo que había dicho y fue arrastrado a Egipto por los que huían; allí murió, según la tradición, apedreado por los suyos. Es el profeta que más habla de sí mismo, y casi siempre para quejarse.' },
  { id: 'teodosio-cuevas', name: 'San Teodosio de las Cuevas', day: '05-03', category: ['monje'], century: 'XI', place: 'Kiev', biography: 'Higúmeno del monasterio de las Cuevas de Kiev († 1074). Su madre lo persiguió durante años para apartarlo de la vida monástica; él se escapó tres veces. Introdujo en la Rus el typikón del Studion y con él la vida cenobítica: comida común, trabajo manual para todos y la puerta abierta a los pobres. Con san Antonio, es el padre del monacato ruso.' },
  { id: 'pelagia-tarso', name: 'Santa Pelagia de Tarso', day: '05-04', category: ['martir'], century: 'III', place: 'Tarso de Cilicia', biography: 'Joven de familia pagana martirizada bajo Diocleciano. La tradición cuenta que rechazó casarse con el hijo del emperador y que éste se quitó la vida; ella fue quemada dentro de un toro de bronce. Tarso, la ciudad de san Pablo, guardó su memoria con particular apego.' },
  { id: 'aparicion-cruz', name: 'Aparición de la Cruz en Jerusalén', day: '05-07', category: ['senor'], century: 'IV', place: 'Jerusalén', biography: 'El 7 de mayo del año 351, sobre el Gólgota y hasta el monte de los Olivos, se vio en el cielo una cruz de luz que duró varias horas y fue contemplada por la ciudad entera. No es una tradición tardía: san Cirilo de Jerusalén, obispo entonces, se lo escribió al emperador Constancio en una carta que se conserva. La Iglesia lo recuerda cada año en la misma fecha.' },
  { id: 'profeta-isaias', name: 'Profeta Isaías', day: '05-09', category: ['profeta'], century: 'VIII a.C.', place: 'Jerusalén', biography: 'El profeta al que se llama evangelista antes del Evangelio, por la precisión con que habla de la Virgen que concebirá y del Siervo que carga con los dolores de todos. Su visión inaugural en el Templo —los serafines y el «Santo, Santo, Santo»— pasó a la Liturgia y se canta en cada celebración. La tradición judía y cristiana lo hace morir aserrado bajo el rey Manasés.' },
  { id: 'glicera-martir', name: 'Santa Glicera', day: '05-13', category: ['martir'], century: 'II', place: 'Traianópolis, Tracia', biography: 'Joven tracia martirizada bajo Antonino Pío. Se presentó ante el gobernador durante un sacrificio público con una cruz marcada en la frente y volcó el altar. Fue echada a las fieras; el carcelero que la había custodiado, llamado Laodicio, se declaró cristiano al ver el final y murió con ella.' },
  { id: 'isidoro-quios', name: 'San Isidoro de Quíos', day: '05-14', category: ['martir'], century: 'III', place: 'Quíos', biography: 'Marinero de la flota romana fondeada en Quíos, denunciado por su propio comandante († 251). Fue arrastrado por la isla atado a un caballo y decapitado. El pozo donde arrojaron su cuerpo sigue siendo lugar de peregrinación, y su culto se extendió por el Mediterráneo con los propios marinos.' },
  { id: 'teodoro-santificado', name: 'San Teodoro el Santificado', day: '05-16', category: ['monje'], century: 'IV', place: 'Tabennisi, Egipto', biography: 'Discípulo predilecto de san Pacomio y su sucesor al frente de los monasterios del alto Egipto († 368). Sostuvo la comunidad en los años difíciles que siguieron a la muerte del fundador y mantuvo la amistad con san Atanasio cuando esa amistad costaba cara. Le llamaron «el Santificado» sus propios hermanos, en vida.' },
  { id: 'andronico-junia', name: 'Los apóstoles Andrónico y Junia', day: '05-17', category: ['apostol'], century: 'I', biography: 'Parientes de san Pablo, que los saluda al final de la carta a los Romanos como «señalados entre los apóstoles» y añade que estuvieron presos con él y que fueron cristianos antes que él. La tradición bizantina los conmemora juntos y llama apóstoles a los dos; san Juan Crisóstomo, comentando el pasaje, se detiene expresamente en que Junia es mujer.' },
  { id: 'teodoto-mesonero', name: 'San Teódoto de Ancira y las siete vírgenes', day: '05-18', category: ['martir'], century: 'IV', place: 'Ancira, Galacia', biography: 'Posadero de Ancira († 303). Escondía cristianos en su casa y rescataba de noche los cuerpos de los ejecutados para enterrarlos. Cuando siete mujeres ancianas fueron ahogadas en un lago, sacó sus cuerpos y les dio sepultura; lo delataron por eso y murió decapitado. No hay que confundirlo con el obispo Teódoto de Ancira, que se conmemora el 7 de junio.' },
  { id: 'patricio-prusa', name: 'San Patricio de Prusa', day: '05-19', category: ['obispo', 'martir'], century: 'III–IV', place: 'Prusa, Bitinia', biography: 'Obispo de Prusa martirizado con tres presbíteros. Las actas conservan su discusión con el gobernador junto a las aguas termales de la ciudad: le preguntaron si aquellas fuentes calientes no probaban la existencia de los dioses del subsuelo, y respondió explicando que el fuego y el agua son criaturas y que también el infierno lo es.' },
  { id: 'talaleo-martir', name: 'San Talaleo', day: '05-20', category: ['martir'], century: 'III', place: 'Egas, Cilicia', biography: 'Médico joven martirizado bajo Numeriano († c. 284). Atendía gratis a los enfermos, cosa rara entonces, y por eso lo llamaron el sin plata, como a los santos Cosme y Damián. Fue ahogado en el mar tras negarse a sacrificar.' },
  { id: 'basilisco-comana', name: 'San Basilisco', day: '05-22', category: ['martir'], century: 'IV', place: 'Comana del Ponto', biography: 'Sobrino de san Teodoro el Tirón, martirizado en Comana hacia 308. Su recuerdo quedó unido a otro: la tradición cuenta que se apareció a san Juan Crisóstomo la víspera de su muerte, en aquella misma Comana adonde lo llevaban desterrado, y le dijo: «Ánimo, hermano, mañana estaremos juntos». Crisóstomo murió al día siguiente y fue enterrado a su lado.' },
  { id: 'miguel-sinada', name: 'San Miguel de Sinada', day: '05-23', category: ['obispo', 'confesor'], century: 'VIII–IX', place: 'Sinada, Frigia', biography: 'Obispo y diplomático († 821). Fue embajador bizantino ante Harún al-Rashid y ante Carlomagno, y acabó desterrado por León V el Armenio por negarse a firmar contra los iconos. Murió en el exilio de Eudocíada.' },
  { id: 'simeon-monte-admirable', name: 'San Simeón Estilita el Joven', day: '05-24', category: ['monje'], century: 'VI', place: 'Monte Admirable, cerca de Antioquía', biography: 'Subió a una columna siendo niño y vivió en ella sesenta y ocho años († 596). En torno a su pilar creció un monasterio y luego un pueblo entero de peregrinos, cuyas ruinas todavía se ven al oeste de Antioquía. Recibía consultas de obispos y de campesinos con la misma paciencia; se conservan cartas suyas a emperadores.' },
  { id: 'tercer-hallazgo-cabeza', name: 'Tercer hallazgo de la cabeza del Bautista', day: '05-25', category: ['profeta'], biography: 'La Iglesia conmemora tres hallazgos distintos de la reliquia del Precursor, en fechas distintas del año, porque tres veces se perdió y se volvió a encontrar en el curso de las persecuciones y las guerras. Este último lo sitúa la tradición en Comana, hacia el año 850, tras el fin de la iconoclastia. Lo que se celebra no es la reliquia en sí, sino la porfía de una memoria que sobrevivió a todo lo que intentó borrarla.' },
  { id: 'apostol-carpo', name: 'Apóstol Carpo', day: '05-26', category: ['apostol'], century: 'I', place: 'Tróade', biography: 'Uno de los Setenta, discípulo de san Pablo, que le dejó su capote y sus libros en Tróade. De él se cuenta la historia que recoge el Areopagita: indignado con un apóstata, pidió a Dios que lo fulminara, y en la visión que tuvo esa noche vio a Cristo bajando del cielo hacia el hombre que él quería ver castigado, para levantarlo.' },
  { id: 'niceta-calcedonia', name: 'San Niceta de Calcedonia', day: '05-28', category: ['obispo', 'confesor'], century: 'VIII–IX', place: 'Calcedonia', biography: 'Obispo de Calcedonia desterrado por León V el Armenio († c. 829). De él cuentan sus contemporáneos que gastó los bienes de la sede en rescatar cautivos y en dotar a huérfanas, y que salió al destierro sin nada que le fuera confiscado.' },
  { id: 'teodosia-constantinopla', name: 'Santa Teodosia de Constantinopla', day: '05-29', category: ['monje', 'martir'], century: 'VIII', place: 'Constantinopla', biography: 'Monja martirizada en 726, al comienzo mismo de la iconoclastia. Un oficial subió a descolgar la imagen de Cristo de la puerta de Calcé, la principal del palacio; un grupo de mujeres, con Teodosia al frente, derribó la escalera con él encima. Fue ejecutada con un cuerno de carnero. En esta misma fecha, siete siglos después, cayó Constantinopla, y las dos memorias han quedado unidas en la conciencia griega.' },
  { id: 'isaac-dalmacia', name: 'San Isaac de Dalmacia', day: '05-30', category: ['monje', 'confesor'], century: 'IV', place: 'Constantinopla', biography: 'Monje que salió del desierto para plantarse ante el emperador Valente, arriano, cuando marchaba contra los godos, y le anunció que no volvería si no devolvía las iglesias a los ortodoxos († c. 383). Valente lo mandó echar a un barranco y murió poco después quemado en Adrianópolis. Isaac fundó a su vuelta el primer monasterio de la capital.' },
  { id: 'hermias-martir', name: 'San Hermias', day: '05-31', category: ['martir'], century: 'II', place: 'Comana de Capadocia', biography: 'Veterano del ejército romano martirizado ya anciano bajo Antonino Pío. Las actas cuentan que el verdugo encargado de darle veneno se convirtió al ver que no le hacía efecto y fue ejecutado antes que él.' },

  /* ═══════════════ Junio ═══════════════ */
  { id: 'lucillano-martir', name: 'San Lucillano y sus compañeros', day: '06-03', category: ['martir'], century: 'III', place: 'Bizancio', biography: 'Antiguo sacerdote pagano convertido en la vejez († 270) y cuatro muchachos que se declararon cristianos con él. Fueron ejecutados en Bizancio, en el lugar donde luego se levantaría la capital del Imperio cristiano.' },
  { id: 'doroteo-tiro', name: 'San Doroteo de Tiro', day: '06-05', category: ['obispo', 'martir'], century: 'III–IV', place: 'Tiro', biography: 'Obispo de Tiro († c. 362). Sobrevivió a la persecución de Diocleciano escondido en Tracia, volvió a su sede con Constantino y murió a los ciento siete años, apaleado bajo Juliano. Se le atribuye un catálogo de los Setenta discípulos que la tradición bizantina siguió durante siglos.' },
  { id: 'visarion-egipto', name: 'San Visarión el Taumaturgo', day: '06-06', category: ['monje'], century: 'IV–V', place: 'Egipto', biography: 'Anacoreta egipcio que no tuvo celda: pasó cuarenta años a la intemperie, andando de un sitio a otro sin dormir dos noches en el mismo. Los Apotegmas cuentan que vendió el Evangelio que le quedaba para dar de comer a un pobre, y que al preguntarle dónde estaba el libro respondió que lo había vendido porque le mandaba hacer eso mismo.' },
  { id: 'teodoto-obispo-ancira', name: 'San Teódoto, obispo de Ancira', day: '06-07', category: ['obispo', 'martir'], century: 'IV', place: 'Ancira, Galacia', biography: 'Obispo de Ancira martirizado hacia 303, distinto del posadero del mismo nombre y de la misma ciudad que se conmemora el 18 de mayo. Las ciudades de la Galacia dieron a la Iglesia tantos mártires que los nombres se repiten, y la tradición ha conservado a los dos sin confundirlos.' },
  { id: 'teodoro-estratelates-tr', name: 'Traslación de las reliquias de san Teodoro Estratelates', day: '06-08', category: ['granmartir'], century: 'IV', place: 'Euquita, Ponto', biography: 'El general de Heraclea, martirizado en 319, pidió antes de morir que su cuerpo fuera llevado a la finca familiar de Euquita. Su siervo Uaro cumplió el encargo, y la Iglesia conmemora ese traslado además del martirio. Es una costumbre bizantina firme: el día de la muerte y el día del regreso se guardan por separado.' },
  { id: 'timoteo-prusa', name: 'San Timoteo de Prusa', day: '06-10', category: ['obispo', 'martir'], century: 'IV', place: 'Prusa, Bitinia', biography: 'Obispo de Prusa decapitado por orden de Juliano hacia 362. El emperador le había mandado dejar de predicar; respondió que podía prohibirle hablar en la calle pero no en la iglesia, y siguió haciéndolo en las dos.' },
  { id: 'aquilina-biblos', name: 'Santa Aquilina', day: '06-13', category: ['martir'], century: 'III', place: 'Biblos, Fenicia', biography: 'Muchacha de doce años martirizada en 293. La denunció un criado de su casa por hablar de Cristo a sus compañeras de juego. Su edad no es un detalle piadoso añadido después: las actas insisten en ella porque el juez insistió, ofreciéndole una y otra vez que dijera que no entendía lo que decía.' },
  { id: 'profeta-eliseo', name: 'Profeta Eliseo', day: '06-14', category: ['profeta'], century: 'IX a.C.', place: 'Israel', biography: 'Discípulo de Elías, que lo llamó echándole el manto encima mientras araba. Pidió doble porción de su espíritu y la Escritura le atribuye el doble de milagros: la harina que no se acaba, el hacha que flota, el leproso Naamán curado en el Jordán. A diferencia de su maestro no huyó al desierto: vivió entre reyes y campesinos durante sesenta años.' },
  { id: 'profeta-amos', name: 'Profeta Amós', day: '06-15', category: ['profeta'], century: 'VIII a.C.', place: 'Tecoa y Betel', biography: 'Pastor y cultivador de higos, no profeta de oficio ni hijo de profeta, como él mismo aclara. Subió del sur al santuario del norte para decir que Dios aborrece las fiestas religiosas de quien pisa al pobre: «Aparta de mí el ruido de tus cantos». Lo echaron de Betel por sedición. Es el primero de los profetas escritores.' },
  { id: 'tijon-amato', name: 'San Tijón de Amato', day: '06-16', category: ['obispo'], century: 'IV–V', place: 'Amato, Chipre', biography: 'Obispo de Amato, en la costa sur de Chipre († c. 425). Siendo hijo de panadero, repartía el pan de su padre a los pobres; la tradición chipriota cuenta que la panera nunca se vaciaba. Dedicó su episcopado a acabar con los últimos cultos paganos de la isla sin violencia, comprando los templos para convertirlos en iglesias.' },
  { id: 'manuel-sabel-ismael', name: 'Santos Manuel, Sabel e Ismael', day: '06-17', category: ['martir'], century: 'IV', place: 'Calcedonia', biography: 'Tres hermanos persas, cristianos, enviados como embajadores de su rey ante Juliano para negociar la paz († 362). El emperador les exigió participar en un sacrificio; se negaron alegando que eran embajadores y no súbditos. Los ejecutó igualmente, y el hecho estuvo a punto de provocar la guerra que la embajada venía a evitar.' },
  { id: 'leoncio-tripoli', name: 'San Leoncio de Trípoli', day: '06-18', category: ['martir'], century: 'II', place: 'Trípoli, Fenicia', biography: 'Oficial romano de origen griego martirizado en Fenicia bajo Vespasiano o Trajano. El tribuno enviado a prenderlo, Hypatio, cayó enfermo por el camino y sanó tras invocar el nombre de Cristo; se bautizó y fue ejecutado antes que él.' },
  { id: 'apostol-judas', name: 'Apóstol Judas', fullName: 'San Judas Tadeo, hermano del Señor', day: '06-19', category: ['apostol'], century: 'I', biography: 'Uno de los Doce, llamado también Tadeo y Lebeo, y hermano de Santiago el Menor. Su carta, de veinticinco versículos, es de las más breves de la Escritura y de las más duras. Eusebio conserva una noticia notable: sus nietos, campesinos, fueron llevados ante el emperador Domiciano por ser de la estirpe de David, y los soltó al ver sus manos encallecidas y al oírles decir que el reino que esperaban no era de este mundo.' },
  { id: 'julian-tarso', name: 'San Julián de Tarso', day: '06-21', category: ['martir'], century: 'III–IV', place: 'Tarso de Cilicia', biography: 'Hijo de un senador, martirizado hacia 305. Lo pasearon un año entero por las ciudades de Cilicia, torturándolo en cada una a la vista del público, y por fin lo cosieron en un saco con serpientes y lo arrojaron al mar. San Juan Crisóstomo predicó un panegírico suyo que se conserva.' },
  { id: 'eusebio-samosata', name: 'San Eusebio de Samosata', day: '06-22', category: ['obispo', 'martir'], century: 'IV', place: 'Samosata, Siria', biography: 'Obispo de Samosata († 380) y amigo de san Basilio, con quien mantuvo una correspondencia que se conserva y que deja ver los años más duros del arrianismo desde dentro. Desterrado por Valente, recorrió disfrazado de soldado las provincias del Danubio ordenando obispos ortodoxos en secreto. Murió al volver a su ciudad, alcanzado por una teja que le arrojó una mujer arriana desde un tejado; prohibió a los suyos buscarla.' },
  { id: 'agripina-roma', name: 'Santa Agripina', day: '06-23', category: ['martir'], century: 'III', place: 'Roma y Sicilia', biography: 'Virgen romana martirizada bajo Valeriano. Sus reliquias fueron llevadas a Mineo, en Sicilia, por tres mujeres que huían de la persecución, y allí se la venera desde entonces. Es una de las santas romanas cuyo culto pasó al Oriente griego por la Italia bizantina.' },
  { id: 'febronia-nisibis', name: 'Santa Febronia', day: '06-25', category: ['monje', 'martir'], century: 'III–IV', place: 'Nisibis, Mesopotamia', biography: 'Monja de un monasterio de Nisibis martirizada hacia 304. Su vida, escrita por una hermana de la misma comunidad que dice haber estado presente, es uno de los pocos relatos de martirio compuestos por una mujer. La abadesa Bryene la había criado desde niña y la escondió cuando llegaron los soldados; salió ella sola.' },
];
