/**
 * Santoral.
 *
 * Las biografías son reseñas históricas redactadas para ATHOS. Los troparios y
 * kontakia son textos litúrgicos: sólo se incluyen cuando se dispone de una
 * versión española de dominio público o de uso tradicional; en caso contrario
 * la ficha queda marcada como pendiente y no se inventa el texto.
 */
import type { Saint, SaintCategory, SourceMeta, TextBlock } from '@/types';
import { MORE_SAINTS } from './saints-more';
import { THIRD_SAINTS } from './saints-third';
import { YEAR_SAINTS_1 } from './saints-year-1';
import { YEAR_SAINTS_2 } from './saints-year-2';

const bio: SourceMeta = {
  source: 'Reseña histórica redactada para ATHOS a partir de fuentes hagiográficas comunes',
  tradition: 'Iglesia ortodoxa',
  language: 'es',
  license: 'cc-by-sa-4.0',
  dateAdded: '2026-01-01',
};

const pendingHymn: TextBlock[] = [
  { kind: 'pending', content: 'Contenido pendiente de incorporar.' },
];

interface SaintSeed {
  id: string;
  name: string;
  fullName?: string;
  day: string;
  category: SaintCategory[];
  century?: string;
  place?: string;
  biography: string;
  troparion?: TextBlock[];
  status?: Saint['status'];
}

const seeds: SaintSeed[] = [
  /* ---------------- Enero ---------------- */
  { id: 'basilio-magno', name: 'San Basilio el Grande', day: '01-01', category: ['obispo', 'padre'], century: 'IV', place: 'Cesarea de Capadocia', biography: 'Nació hacia el año 330 en Cesarea de Capadocia, en una familia que dio a la Iglesia una santa por generación: su abuela Macrina la Mayor, su madre Emelia, su hermana Macrina y sus hermanos Gregorio de Nisa y Pedro de Sebaste. Estudió en Constantinopla y en Atenas, donde trabó con Gregorio de Nacianzo la amistad más célebre de la patrística. Volvió a casa con fama de retórico brillante, y fue su hermana Macrina quien lo convenció de que aquello era vanidad.\n\nSe bautizó hacia 357, recorrió los monasterios de Egipto, Palestina y Siria, y se retiró a una finca familiar junto al río Iris. De allí salieron sus Reglas, que dieron forma a la vida monástica en común del Oriente cristiano: trabajo, oración a horas fijas y obediencia, frente a los excesos de los ermitaños solitarios. Ordenado sacerdote en 364, fue elegido arzobispo de Cesarea en 370.\n\nComo obispo plantó cara al emperador arriano Valente. Al prefecto Modesto, que lo amenazaba con la confiscación, el destierro y la muerte, le respondió que no tenía bienes que perder, que toda la tierra era de Dios y que la muerte sería un favor; el prefecto dijo que nunca le habían hablado así, y Basilio contestó que quizá nunca se había topado con un obispo. Escribió Sobre el Espíritu Santo, en defensa de su divinidad, y levantó a las puertas de la ciudad la Basiliada: hospital, albergue y leprosería.\n\nMurió el 1 de enero de 379, con unos cuarenta y nueve años. La Divina Liturgia que lleva su nombre se celebra diez veces al año, y en Grecia su fiesta es la del pan de san Basilio, la vasilópita, con una moneda escondida dentro.' },
  { id: 'serafin-sarov', name: 'San Serafín de Sarov', day: '01-02', category: ['monje'], century: 'XVIII–XIX', place: 'Sarov, Rusia', biography: 'Se llamaba Projor Moshnin y nació en 1754 en Kursk, hijo de un comerciante. De niño cayó desde lo alto del campanario que construía su madre y se levantó ileso. A los diecinueve años peregrinó a Kiev y un anciano le señaló el monasterio de Sarov, donde entró en 1778. Fue tonsurado con el nombre de Serafín, «el ardiente», y ordenado sacerdote en 1793.\n\nAl año siguiente se retiró a una cabaña en el bosque, a unos kilómetros del monasterio, para vivir en soledad. Unos ladrones lo apalearon hasta dejarlo por muerto, y quedó encorvado para siempre; cuando los detuvieron, pidió que no los castigaran. Pasó después mil días y mil noches rezando sobre una piedra, y luego años de silencio completo y de reclusión en su celda.\n\nEn 1825 abrió la puerta. Recibía a todos —campesinos, nobles, enfermos— con una reverencia hasta el suelo y el mismo saludo, fuera cual fuera la fecha: «¡Alegría mía, Cristo ha resucitado!». Enseñaba que el fin de la vida cristiana es la adquisición del Espíritu Santo, y así se lo explicó en 1831 a Nikolái Motovílov en una conversación que éste puso por escrito y que no se publicó hasta 1903. Fundó y guió el convento de mujeres de Diveyevo.\n\nMurió el 2 de enero de 1833, arrodillado ante un icono de la Theotokos. Fue canonizado en 1903; sus reliquias, perdidas tras la revolución, reaparecieron en 1991 y volvieron a Diveyevo en procesión.' },
  { id: 'teofania-señor', name: 'Bautismo del Señor', day: '01-06', category: ['senor'], biography: 'Treinta años después de su nacimiento, Cristo acude al Jordán, donde Juan bautiza a quienes se arrepienten, y se pone en la fila de los pecadores. Juan se resiste —«soy yo quien necesita ser bautizado por ti»— y Jesús insiste. Al salir del agua se abren los cielos, el Espíritu desciende en forma de paloma y la voz del Padre dice: «Éste es mi Hijo amado». Por eso la fiesta se llama Teofanía, manifestación de Dios: es la primera vez que la Trinidad se muestra entera ante los hombres.\n\nEn los primeros siglos, Oriente celebraba el 6 de enero el nacimiento y el bautismo juntos, como una sola Epifanía. Cuando en el siglo IV se separó la Navidad, esta fecha quedó para el Jordán. Los Padres la llaman también la fiesta de las Luces, porque el bautismo es iluminación.\n\nLa Iglesia ve en ella el día en que Cristo santificó las aguas: no necesitaba ser purificado, sino que entró en el agua para purificarla. De ahí la Gran Bendición de las Aguas, que se hace en la víspera y en la fiesta; con esa agua se bendicen después las casas, y los fieles la guardan todo el año. En Grecia y en muchos puertos se arroja una cruz al mar o al río y los jóvenes se lanzan a recogerla.\n\nLa víspera es día de ayuno estricto. La fiesta tiene su celebración anticipada y su clausura, el 14 de enero, y a la Teofanía se asocia al día siguiente la memoria de san Juan Bautista.' },
  { id: 'juan-bautista-sinaxis', name: 'San Juan Bautista', fullName: 'Sinaxis del santo Profeta, Precursor y Bautista Juan', day: '01-07', category: ['profeta'], century: 'I', biography: 'El día después de la Teofanía, la Iglesia se reúne —eso significa sínaxis— para honrar a quien sirvió al misterio: Juan, el que bautizó a Cristo. Es la costumbre bizantina de dedicar el día siguiente a una gran fiesta a quien tuvo en ella el papel principal junto al Señor. Se recuerda también la llegada a Constantinopla, en el siglo X, de la reliquia de su mano derecha, la que tocó la cabeza de Cristo en el Jordán.\n\nHijo del sacerdote Zacarías y de Isabel, pariente de la Virgen, nació seis meses antes que Jesús. Se crió en el desierto, vestido de pelo de camello y alimentado de langostas y miel silvestre, y apareció junto al Jordán predicando un bautismo de arrepentimiento. A él acudía la gente de toda Judea. Señaló a Cristo con las palabras que se repiten en cada Liturgia: «He aquí el Cordero de Dios, que quita el pecado del mundo».\n\nReprochó al tetrarca Herodes Antipas que viviera con Herodías, la mujer de su hermano, y fue encerrado en la fortaleza de Maqueronte. Allí lo decapitaron por el capricho de Salomé en un banquete.\n\nLa Iglesia lo llama Precursor, el último de los profetas y el mayor de los nacidos de mujer, según palabra del mismo Cristo. En los iconos aparece con alas, porque Malaquías lo anunció como el mensajero, el ángel, que prepara el camino; y en la Deisis está a la izquierda de Cristo, frente a la Theotokos, intercediendo por el mundo. Ningún santo tiene tantas fiestas en el año: seis.' },
  { id: 'antonio-magno', name: 'San Antonio el Grande', day: '01-17', category: ['monje'], century: 'III–IV', place: 'Egipto', biography: 'Nació hacia el año 251 en Coma, en el Egipto medio, hijo de cristianos acomodados. Quedó huérfano hacia los veinte años con una hermana pequeña a su cargo. Un domingo oyó leer en la iglesia: «Si quieres ser perfecto, ve, vende lo que tienes y dáselo a los pobres». Lo tomó como dicho para él. Repartió sus tierras, confió a su hermana a una comunidad de vírgenes y se fue a vivir cerca del pueblo, junto a un anciano asceta del que aprendió.\n\nDespués se encerró en unas tumbas, donde según su Vida sufrió los asaltos de los demonios, y más tarde en un fortín abandonado junto al Nilo, donde pasó unos veinte años sin ver a nadie. Cuando hacia 305 sus amigos derribaron la puerta, salió sereno, ni flaco ni consumido, y en torno a él se reunieron discípulos: nació así la primera generación de monjes del desierto.\n\nEn 311 bajó a Alejandría para confortar a los mártires durante la persecución de Maximino, y en 338 volvió para apoyar a san Atanasio contra los arrianos. El resto de su vida lo pasó en la Montaña Interior, cerca del mar Rojo, cultivando un pequeño huerto y recibiendo a quienes lo buscaban. Allí visitó, según la tradición, a san Pablo de Tebas, el primer ermitaño.\n\nMurió en 356, con unos ciento cinco años. Pidió que se ocultara su tumba y dejó su manto de piel a Atanasio, que escribió su Vida. Aquel libro se leyó en todo el Imperio, y fue su lectura la que precipitó la conversión de san Agustín.' },
  { id: 'atanasio-alejandria', name: 'San Atanasio el Grande', day: '01-18', category: ['obispo', 'padre', 'confesor'], century: 'IV', place: 'Alejandría', biography: 'Nació en Alejandría hacia 296. Era todavía diácono y secretario del obispo Alejandro cuando lo acompañó al Concilio de Nicea en 325, donde se condenó a Arrio, que enseñaba que el Hijo era la primera y más excelsa de las criaturas, pero criatura. Tres años después, muy joven, sucedió a Alejandro en la sede, y dedicó el resto de su vida a defender lo que Nicea había definido: que el Hijo es consustancial al Padre, Dios del mismo modo que Él.\n\nLe costó cinco destierros y diecisiete años fuera de su ciudad, bajo cuatro emperadores. Constantino lo envió a Tréveris; Constancio, a Roma y después al desierto, donde los monjes lo escondieron seis años; Juliano lo expulsó por pagano, y Valente por arriano. Hubo un momento en que casi todos los obispos del Imperio parecían haber cedido, y de ahí viene la expresión «Atanasio contra el mundo».\n\nDe joven escribió Sobre la Encarnación del Verbo, que contiene la frase que resume la teología oriental: Dios se hizo hombre para que el hombre se hiciera dios. Escribió también los Discursos contra los arrianos y la Vida de san Antonio. En su carta pascual del año 367 dio la primera lista que se conserva con los veintisiete libros exactos del Nuevo Testamento.\n\nMurió en su sede, en paz, el 2 de mayo de 373. El 18 de enero la Iglesia lo conmemora junto con san Cirilo de Alejandría, el otro gran defensor de la fe de su ciudad.' },
  { id: 'macario-egipcio', name: 'San Macario el Egipcio', day: '01-19', category: ['monje'], century: 'IV', place: 'Escete, Egipto', biography: 'Nació hacia el año 300 en el Alto Egipto y de joven trabajó como camellero, llevando natrón por el desierto. Vivía como asceta en un pueblo cuando una muchacha embarazada lo acusó de ser el padre. Lo apalearon y él no se defendió: se puso a trabajar para mantenerla. Cuando llegó el parto y ella no podía dar a luz, confesó la verdad, y el pueblo quiso pedirle perdón; él huyó para evitar los honores.\n\nHacia 330 se internó en el desierto de Escete, donde llegó a ser el padre de una gran colonia de monjes. Visitó a san Antonio y fue ordenado sacerdote. Por su madurez temprana lo llamaban el niño anciano. Hacia 374, durante la persecución arriana del obispo Lucio, fue desterrado con Macario de Alejandría a una isla del Nilo, y volvió después a Escete, donde murió hacia 390, con noventa años.\n\nLos Dichos de los Padres del desierto conservan muchas palabras suyas. A quien le preguntaba cómo orar, le decía que no hacía falta hablar mucho: basta extender las manos y decir «Señor, como Tú quieras y como Tú sepas, ten piedad de mí».\n\nBajo su nombre circulan las Cincuenta homilías espirituales, sobre la oración del corazón y la acción del Espíritu en el alma, que marcaron a toda la tradición hesicasta. La crítica moderna las atribuye a un autor sirio posterior; la Iglesia las sigue leyendo con el nombre de Macario.' },
  { id: 'gregorio-teologo', name: 'San Gregorio el Teólogo', fullName: 'San Gregorio Nacianceno', day: '01-25', category: ['obispo', 'padre'], century: 'IV', place: 'Nacianzo, Capadocia', biography: 'Nació hacia 329 en Arianzo, cerca de Nacianzo, en Capadocia. Su padre, también Gregorio, era el obispo de la ciudad, y su madre, santa Nona, lo había convertido. Estudió en Cesarea, en Alejandría y en Atenas, donde conoció a san Basilio. Soñaba con una vida de estudio y retiro, y le tocó otra.\n\nSu padre lo ordenó sacerdote casi a la fuerza hacia 361; huyó al Ponto, volvió y escribió para justificarse un discurso sobre el sacerdocio que san Juan Crisóstomo tuvo después delante. Basilio lo hizo obispo de Sásima, una aldea de paso a la que Gregorio nunca fue, y la amistad se resintió.\n\nEn 379 aceptó ir a Constantinopla, donde los arrianos tenían todas las iglesias. Predicó en una capilla de una casa, a la que llamó Anastasia, la resurrección, y allí pronunció en 380 los cinco Discursos teológicos sobre la Trinidad. Le apedrearon los fieles en una Vigilia Pascual. Cuando Teodosio devolvió las iglesias a los nicenos, lo sentó en la sede y en 381 presidió el segundo Concilio Ecuménico; pero las intrigas contra su nombramiento lo cansaron, y dimitió con un discurso de despedida memorable.\n\nPasó sus últimos años en Arianzo, escribiendo poesía, y murió en 390. La Iglesia lo llama el Teólogo, un título que sólo comparte con san Juan Evangelista y san Simeón el Nuevo Teólogo.' },
  { id: 'tres-jerarcas', name: 'Los Tres Santos Jerarcas', day: '01-30', category: ['obispo', 'padre'], century: 'IV–V', biography: 'San Basilio el Grande, san Gregorio el Teólogo y san Juan Crisóstomo tienen cada uno su fiesta en enero. A finales del siglo XI, en tiempos del emperador Alejo Comneno, los fieles de Constantinopla estaban divididos en tres partidos que discutían cuál de los tres era el mayor: si Basilio por su obra y su gobierno, si Gregorio por su teología, si Juan por su predicación.\n\nSegún el relato, los tres se aparecieron al metropolita Juan Mauropus de Euchaita, uno a uno y después juntos, para decirle que entre ellos no había ni primero ni segundo, que eran uno ante Dios, y que no querían ser motivo de división. Mauropus compuso para ellos un oficio común y se fijó la fiesta el 30 de enero.\n\nLos tres fueron obispos y los tres escribieron las obras que sostienen la teología, la liturgia y la predicación de la Iglesia. Dos de las tres Liturgias bizantinas llevan sus nombres. En los iconos aparecen juntos, de pie, con el libro de los Evangelios en las manos.\n\nEn Grecia, desde el siglo XIX, el 30 de enero es la fiesta de la educación y de las letras: los tres fueron hombres de la mejor cultura de su tiempo y la pusieron al servicio de la fe, y las escuelas y la Universidad de Atenas los tienen por patronos.' },

  /* ---------------- Febrero ---------------- */
  { id: 'encuentro-senor', name: 'Encuentro del Señor', day: '02-02', category: ['senor'], biography: 'Cuarenta días después del nacimiento, María y José llevan al Niño al Templo de Jerusalén para cumplir dos preceptos de la Ley: la purificación de la madre y la presentación del primogénito, que pertenece a Dios. Ofrecen dos tórtolas, la ofrenda que la Ley permitía a los pobres.\n\nEn el Templo los espera el anciano Simeón, un hombre justo al que el Espíritu había prometido que no moriría sin ver al Mesías. Toma al Niño en brazos y dice la oración que la Iglesia repite cada tarde en Vísperas: «Ahora, Señor, despides a tu siervo en paz». A María le anuncia que una espada le atravesará el alma. Llega también Ana, una profetisa viuda de ochenta y cuatro años que no se apartaba del Templo, y habla del Niño a todos los que esperaban la redención.\n\nEl nombre griego de la fiesta, Hypapante, significa encuentro: el del Señor con su pueblo, y el del Antiguo Testamento, en la persona de Simeón, con el Nuevo, que tiene en sus brazos. En Constantinopla se celebró con especial solemnidad desde 542, cuando Justiniano la mandó guardar tras una epidemia de peste.\n\nEs una de las doce grandes fiestas. Es a la vez del Señor y de la Theotokos, y en muchas iglesias se bendicen ese día las velas.' },
  { id: 'haralambos', name: 'San Haralampo', day: '02-10', category: ['martir', 'obispo'], century: 'II', place: 'Magnesia', biography: 'Según su Pasión, era obispo de Magnesia, en Asia Menor, y tenía ciento trece años cuando lo arrestaron durante la persecución de Septimio Severo, hacia el año 202. Seguía predicando abiertamente, y el gobernador Luciano mandó llevarlo a juicio.\n\nEl relato cuenta que lo desollaron con garfios de hierro y que el anciano dio gracias a sus verdugos por renovarle el cuerpo. Dos soldados, Porfirio y Dauctos, y tres mujeres que presenciaban el tormento se hicieron cristianos y fueron martirizados. También se convirtió, dice la tradición, Galini, la hija del emperador.\n\nFue condenado a morir decapitado, y la Pasión dice que entregó el espíritu antes de que cayera la espada. Como tantas vidas de mártires antiguos, la suya llegó envuelta en detalles legendarios; lo que la Iglesia conmemora es el testimonio de un pastor que no dejó a su rebaño en la vejez.\n\nEs uno de los santos más queridos de Grecia, invocado contra la peste y las epidemias: en los iconos aparece pisando a la plaga en figura humana. Su cráneo se venera en el monasterio de San Esteban de Meteora.' },
  { id: 'cirilo-metodio-c', name: 'San Cirilo, iguales a los Apóstoles', day: '02-14', category: ['obispo'], century: 'IX', place: 'Tesalónica', biography: 'Constantino, al que la Iglesia conoce por el nombre de monje que tomó al final de su vida, Cirilo, nació hacia 827 en Tesalónica, el menor de siete hermanos. Era hijo de un oficial bizantino, y en la ciudad se hablaba tanto griego como eslavo. Estudió en Constantinopla con Focio y fue bibliotecario de Santa Sofía; lo llamaban el Filósofo.\n\nHacia 862, el príncipe Rastislav de la Gran Moravia pidió a Constantinopla maestros que enseñaran la fe a su pueblo en su propia lengua. El emperador envió a Constantino y a su hermano mayor, Metodio. Para ello Cirilo inventó un alfabeto, el glagolítico, y tradujo el Evangelio y los libros de la Liturgia al eslavo.\n\nEl clero franco de la región se opuso: sostenía que sólo había tres lenguas dignas del culto, el hebreo, el griego y el latín, las del letrero de la Cruz. Los hermanos fueron a Roma, y en 868 el papa Adriano II aprobó los libros eslavos y los depositó en el altar de Santa María la Mayor. Allí enfermó Constantino, se hizo monje con el nombre de Cirilo y murió el 14 de febrero de 869, a los cuarenta y dos años. Está enterrado en San Clemente.\n\nMetodio siguió la misión como arzobispo, entre prisiones y persecuciones, hasta su muerte en 885. Sus discípulos, expulsados de Moravia, llevaron el eslavo litúrgico a Bulgaria, donde nació el alfabeto cirílico. De aquella traducción vienen las Iglesias eslavas. La Iglesia los llama iguales a los Apóstoles.' },

  /* ---------------- Marzo ---------------- */
  { id: 'gregorio-palamas', name: 'San Gregorio Palamás', day: '03-14', category: ['obispo', 'padre'], century: 'XIV', place: 'Monte Athos y Tesalónica', biography: 'Nació en 1296 en Constantinopla, en una familia de la aristocracia; su padre era senador en la corte de Andrónico II y murió cuando Gregorio era niño. El emperador se ocupó de su educación, y el joven brilló en filosofía. A los veinte años lo dejó todo y se fue al Monte Athos con dos de sus hermanos; su madre y sus hermanas entraron en un monasterio.\n\nEn el Athos vivió en Vatopedi, en la Gran Laura y en ermitas, dedicado a la oración hesicasta, la oración de Jesús dicha en el silencio del corazón. Hacia 1337, un monje calabrés, Barlaam, se burló de los hesicastas: decía que era imposible ver a Dios y que la luz que afirmaban contemplar era una ilusión o una criatura. Palamás respondió con las Tríadas en defensa de los santos hesicastas. Explicó que Dios es inaccesible en su esencia, pero se comunica realmente en sus energías, que son increadas: lo que ven los santos es la misma luz del Tabor.\n\nUn concilio le dio la razón en 1341, pero la guerra civil lo arrastró: estuvo preso y excomulgado hasta 1347, cuando fue rehabilitado y nombrado arzobispo de Tesalónica. Los zelotes, que gobernaban la ciudad, no lo dejaron entrar hasta 1350. En 1354 lo capturaron los turcos y pasó un año cautivo en Asia Menor, donde discutió de religión con musulmanes.\n\nMurió el 14 de noviembre de 1359. Fue canonizado en 1368, y su fiesta principal es el segundo domingo de Cuaresma, como prolongación del Triunfo de la Ortodoxia.' },
  { id: 'anunciacion-s', name: 'Anunciación de la Theotokos', day: '03-25', category: ['theotokos'], biography: 'En el sexto mes del embarazo de Isabel, el arcángel Gabriel es enviado a Nazaret, a una virgen desposada con José, de la casa de David. La saluda: «Alégrate, llena de gracia, el Señor está contigo». Ella se turba, y el ángel le anuncia que concebirá y dará a luz un hijo al que llamará Jesús, Hijo del Altísimo, cuyo reino no tendrá fin.\n\nMaría pregunta cómo será eso, puesto que no conoce varón. El ángel responde que el Espíritu Santo vendrá sobre ella y la fuerza del Altísimo la cubrirá con su sombra, y le da una señal: su pariente Isabel, estéril y anciana, espera un hijo, porque para Dios no hay nada imposible. Entonces ella responde: «He aquí la esclava del Señor; hágase en mí según tu palabra».\n\nLa Iglesia entiende esa respuesta como el consentimiento de la humanidad entera. Dios no se impone: pide, y la Encarnación empieza con un sí libre. El tropario de la fiesta la llama el principio de nuestra salvación. La fiesta va exactamente nueve meses antes de la Navidad.\n\nEs la única que no se aplaza nunca: se celebra aunque caiga en Viernes Santo, y entonces se cantan a la vez el anuncio y el sepulcro. Aunque suele caer en Cuaresma, ese día se permite el pescado. En Grecia es además fiesta nacional, porque el levantamiento de 1821 se proclamó el 25 de marzo.' },

  /* ---------------- Abril ---------------- */
  { id: 'jorge-trofeoforo', name: 'San Jorge el Trofeóforo', day: '04-23', category: ['granmartir'], century: 'IV', place: 'Capadocia y Lida', biography: 'Según la tradición, nació en Capadocia en una familia cristiana, y su madre era de Lida, en Palestina. Entró en el ejército y llegó a ser oficial de alto rango al servicio de Diocleciano.\n\nCuando en 303 el emperador publicó en Nicomedia el edicto de persecución, Jorge repartió sus bienes entre los pobres, se presentó ante el consejo imperial y se declaró cristiano. Su Pasión, que creció con los siglos, cuenta tormentos sucesivos —la rueda, la cal viva, el veneno— de los que salía ileso, y conversiones entre los soldados y hasta en la familia imperial. Fue decapitado el 23 de abril de 303 y enterrado en Lida, donde se levantó su basílica.\n\nEl episodio del dragón y la princesa, el más conocido en Occidente, es un relato medieval muy posterior. La Iglesia lo ha conservado en sus iconos leyéndolo como una imagen: la fe que vence al mal.\n\nEs uno de los santos más venerados de toda la cristiandad, patrono de ejércitos, de caballeros y de naciones enteras. Lo llaman Trofeóforo, el portador de trofeos. En el uso griego, cuando su fiesta cae antes de Pascua, se traslada al lunes de la Semana Luminosa, para no celebrarla en Cuaresma.' },
  { id: 'marcos-evangelista', name: 'San Marcos Evangelista', day: '04-25', category: ['apostol'], century: 'I', place: 'Alejandría', biography: 'Es el Juan Marcos de los Hechos de los Apóstoles. En casa de su madre, María, se reunía la Iglesia de Jerusalén, y allí fue Pedro al salir milagrosamente de la cárcel. Era primo de Bernabé, y acompañó a Pablo y a Bernabé en su primer viaje misionero, pero los dejó a mitad de camino. Pablo no quiso llevarlo en el siguiente, y aquello separó a los dos apóstoles. Años después Pablo lo reclamó a su lado, porque le era útil para el ministerio.\n\nDespués estuvo con Pedro en Roma, que en su carta lo llama «mi hijo». Papías, a comienzos del siglo II, dice que Marcos fue el intérprete de Pedro y puso por escrito con exactitud lo que recordaba de su predicación. Así nació el segundo Evangelio, el más breve y, según casi todos los estudiosos, el más antiguo de los cuatro. Escribe deprisa, con el adverbio «enseguida» en cada página, y no oculta las torpezas de los apóstoles. Algunos lo identifican con el muchacho que huyó desnudo de Getsemaní, un detalle que sólo cuenta su Evangelio.\n\nSegún la tradición, fundó la Iglesia de Alejandría, que llegó a ser la segunda del mundo antiguo. Allí, hacia el año 68, durante una fiesta pagana, lo arrastraron por las calles hasta matarlo. Su símbolo es el león.\n\nUnos mercaderes venecianos robaron sus reliquias en 828 y las llevaron a San Marcos de Venecia. En 1968, el papa Pablo VI devolvió una parte a la Iglesia copta de Alejandría.' },

  /* ---------------- Mayo ---------------- */
  { id: 'juan-teologo-mayo', name: 'San Juan el Teólogo', day: '05-08', category: ['apostol', 'padre'], century: 'I', place: 'Éfeso y Patmos', biography: 'Hijo de Zebedeo y de Salomé, hermano de Santiago, era pescador en el lago de Galilea y había sido discípulo del Bautista. Con Pedro y Santiago formó el grupo de los tres más cercanos: los únicos presentes en la Transfiguración y en la agonía de Getsemaní. Jesús los llamó a él y a su hermano hijos del trueno. En la Última Cena se reclinó sobre el pecho del Señor, y fue el único de los apóstoles que estuvo al pie de la Cruz, donde Cristo le confió a su Madre.\n\nCorrió con Pedro al sepulcro vacío, fue una de las columnas de la Iglesia de Jerusalén y más tarde se estableció en Éfeso con la Theotokos. Bajo Domiciano fue desterrado a la isla de Patmos, donde recibió las visiones del Apocalipsis; la tradición dice que las dictó a su discípulo Prócoro en una cueva que todavía se visita.\n\nEscribió el cuarto Evangelio, tres cartas y el Apocalipsis. El prólogo de su Evangelio —«En el principio era el Verbo»— le valió el nombre de Teólogo, que la Iglesia sólo da a otros dos santos. Según la tradición, fue el único de los doce que no murió mártir, y alcanzó una edad muy avanzada.\n\nEl 26 de septiembre se recuerda su muerte. La fiesta del 8 de mayo conmemora un hecho que cuenta la tradición de Éfeso: cada año, en esta fecha, brotaba de su tumba un polvo fino que los fieles recogían para curar a los enfermos.' },

  /* ---------------- Junio ---------------- */
  { id: 'justino-filosofo', name: 'San Justino Filósofo', day: '06-01', category: ['martir', 'padre'], century: 'II', place: 'Roma', biography: 'Nació hacia el año 100 en Flavia Neápolis, la antigua Siquem de Samaria, en una familia pagana de lengua griega. Buscó la verdad en las escuelas de su tiempo: pasó por un estoico, un peripatético al que sólo le interesaba cobrar, un pitagórico que le exigía saber música y geometría antes de hablar de Dios, y un platónico que le entusiasmó. Un día, paseando junto al mar, un anciano le habló de los profetas, que habían anunciado a Cristo mucho antes que los filósofos, y Justino se convirtió.\n\nNo dejó el manto de filósofo: pensaba que había encontrado la única filosofía segura y útil. Enseñó en Roma, donde abrió una escuela, y escribió en defensa de los cristianos, a los que la gente acusaba de ateísmo, incesto y canibalismo. Se conservan sus dos Apologías, dirigidas al emperador Antonino Pío y al Senado, y el Diálogo con Trifón, una conversación con un judío sobre las Escrituras.\n\nEn la Primera Apología describe cómo celebraban los cristianos el domingo: las lecturas de los apóstoles y los profetas, la exhortación del que preside, las oraciones, el pan y el vino mezclado con agua, el amén del pueblo y los diáconos que llevan la Comunión a los ausentes. Es la descripción más antigua de la Liturgia. Enseñó también que en los filósofos había semillas del Verbo, fragmentos de la verdad que Cristo muestra entera.\n\nHacia 165 fue denunciado y decapitado en Roma con seis compañeros. Se conservan las actas de su juicio ante el prefecto Junio Rústico.' },

  /* ---------------- Julio ---------------- */
  { id: 'cosme-damian', name: 'Santos Cosme y Damián', day: '07-01', category: ['justo'], century: 'III', biography: 'Eran hermanos médicos y atendían sin cobrar nada, de donde les viene el nombre de anárgiros, los sin plata: tomaron al pie de la letra el «gratis lo recibisteis, dadlo gratis» del Evangelio. Curaban a hombres y animales, y la tradición une en su caso la medicina y la oración.\n\nHay tres parejas distintas de santos Cosme y Damián en el santoral bizantino, conmemoradas en tres días del año, y la tradición no las ha llegado a distinguir del todo. Los del 1 de julio son los de Roma. Según el Sinaxario, murieron hacia el año 284 a manos de su propio maestro de medicina, que los envidiaba: los llevó a recoger hierbas al monte y allí los apedreó. Los del 1 de noviembre, hijos de santa Teódota, eran de Asia Menor y murieron en paz. Los del 17 de octubre fueron martirizados en Cilicia con sus hermanos, bajo Diocleciano, y son los que venera la Iglesia latina.\n\nLo que tienen en común las tres parejas es lo que hace de ellos un tipo de santidad: el médico que ve en el enfermo a Cristo y no a un cliente.\n\nSe les invoca en la enfermedad, y el aceite de sus santuarios se sigue repartiendo en Grecia. En los iconos aparecen con la caja de las medicinas y una cucharilla.' },
  { id: 'atanasio-athonita', name: 'San Atanasio el Athonita', day: '07-05', category: ['monje'], century: 'X', place: 'Monte Athos', biography: 'Nació hacia 920 en Trebisonda y fue bautizado con el nombre de Abraham. Quedó huérfano muy pronto, estudió en Constantinopla y llegó a enseñar allí. Se hizo monje en el monte Kyminas, en Bitinia, bajo la guía de san Miguel Maleinos, y allí trabó amistad con el sobrino de éste, el general Nicéforo Focas.\n\nPara escapar de los honores huyó en 958 al Monte Athos, donde se hizo pasar por un analfabeto y trabajó como jornalero de un ermitaño, hasta que lo descubrieron. En 961, antes de partir a reconquistar Creta a los árabes, Nicéforo le pidió oraciones y le prometió fundar un monasterio. Con aquella ayuda, Atanasio levantó en 963 la Gran Laura.\n\nAntes de él, el Athos era una montaña de ermitaños dispersos; él la organizó en comunidad, con regla, refectorio y oficio en común. Los eremitas de la Montaña se lo tomaron tan mal que estuvieron a punto de expulsarlo, y el emperador tuvo que intervenir. Cuando Nicéforo, que había prometido hacerse monje, aceptó en cambio la corona imperial, Atanasio se enfadó con él y el emperador tuvo que pedirle perdón. En 972 se aprobó el primer reglamento común del Athos.\n\nMurió hacia el año 1000, cuando se desplomó la cúpula de la iglesia que estaba construyendo, con cinco monjes más. La Gran Laura sigue siendo el primero de los veinte monasterios.' },
  { id: 'elias-profeta', name: 'Santo Profeta Elías', day: '07-20', category: ['profeta'], century: 'IX a. C.', place: 'Israel', biography: 'Era de Tisbé, en Galaad, y vivió en el siglo IX antes de Cristo, en tiempos del rey Ajab y de la reina Jezabel, que había traído a Israel el culto de Baal. Se presentó ante el rey para anunciarle que no llovería más que cuando él lo dijera, y se ocultó junto al torrente de Querit, donde lo alimentaban los cuervos. En Sarepta, una viuda pobre compartió con él su último puñado de harina; la harina y el aceite no se le acabaron, y Elías resucitó a su hijo.\n\nAl cabo de tres años desafió en el monte Carmelo a los cuatrocientos cincuenta profetas de Baal: cada uno prepararía un sacrificio sin fuego, y el Dios que respondiera con fuego sería el verdadero. Baal calló, y el fuego del cielo consumió el sacrificio de Elías empapado en agua. Después, perseguido por Jezabel, huyó al desierto y quiso morir. Caminó cuarenta días hasta el Horeb, y allí Dios no se le mostró en el viento, ni en el terremoto, ni en el fuego, sino en el susurro de una brisa suave.\n\nUngió a Eliseo como sucesor y fue arrebatado al cielo en un torbellino, en un carro de fuego. Malaquías anunció que volvería antes del Día del Señor; Cristo dijo que Juan Bautista había venido con su espíritu, y Elías apareció junto a Moisés en la Transfiguración.\n\nLos monjes lo tienen por modelo de la vida en el desierto y de la oración. En Grecia, las capillas de lo alto de los montes suelen estar dedicadas al profeta Elías.' },
  { id: 'panteleimon', name: 'San Panteleimón', day: '07-27', category: ['granmartir'], century: 'III–IV', place: 'Nicomedia', biography: 'Nació en Nicomedia, capital de Oriente en tiempos de Diocleciano. Su padre, Eustorgio, era un senador pagano; su madre, Eubula, cristiana, murió cuando él era niño. Estudió medicina con el médico más famoso de la ciudad, y el emperador pensaba tomarlo a su servicio. Su nombre era Pantoleón, «león en todo».\n\nSegún su Pasión, un sacerdote llamado Hermolao le habló de Cristo, el médico de las almas y los cuerpos. Poco después encontró en la calle a un niño muerto por la mordedura de una víbora, invocó a Cristo y el niño se levantó. Se bautizó, devolvió la vista a un ciego y con ello convirtió a su padre. Al morir éste, repartió la herencia y empezó a atender gratis a todos. Su clientela arruinó a los demás médicos de la ciudad, que lo denunciaron.\n\nEl relato cuenta tormentos de los que salía ileso y la conversión de los verdugos. Fue decapitado en 305. La tradición añade que las espadas se doblaban hasta que él mismo dio permiso, y que el olivo al que lo ataron floreció. La Iglesia le cambió el nombre a Panteleimón, «el que todo lo compadece».\n\nEs, con san Cosme y san Damián, el santo más invocado en la enfermedad, y el patrono de los médicos en Oriente. Con él se bendice el aceite de la unción de los enfermos. El monasterio ruso del Monte Athos lleva su nombre y guarda parte de su cabeza.' },

  /* ---------------- Agosto ---------------- */
  { id: 'degollacion-s', name: 'Degollación de San Juan Bautista', day: '08-29', category: ['profeta', 'martir'], century: 'I', biography: 'Herodes Antipas, tetrarca de Galilea, había repudiado a su mujer para casarse con Herodías, la mujer de su hermano Filipo. Juan Bautista se lo reprochó en público —«no te es lícito tenerla»—, y Herodes lo encerró en la fortaleza de Maqueronte, al este del mar Muerto. Lo temía y a la vez lo escuchaba con gusto, dice el Evangelio; Herodías, en cambio, quería matarlo.\n\nLa ocasión llegó en el banquete de cumpleaños del tetrarca. La hija de Herodías, a la que Flavio Josefo llama Salomé, bailó ante los invitados, y Herodes, complacido, le juró darle lo que pidiera, aunque fuera la mitad de su reino. Aconsejada por su madre, pidió la cabeza de Juan en una bandeja. El rey se entristeció, pero por el juramento y por los convidados no quiso negarse, y mandó decapitarlo en la cárcel. Los discípulos de Juan recogieron el cuerpo y lo enterraron.\n\nLa Iglesia guarda ese día ayuno estricto, aunque caiga en domingo, en duelo por el mayor de los profetas. En muchos sitios se evita cortar nada redondo ni comer en plato hondo: una costumbre popular que no obliga a nadie, pero que ha conservado la memoria del modo en que murió.\n\nEl Evangelio de la fiesta lo presenta como el precursor de Cristo también en la muerte: el justo condenado por el poder, sin juicio, por el capricho de una fiesta.' },
  { id: 'cosme-etolia', name: 'San Cosme de Etolia', day: '08-24', category: ['martir', 'monje'], century: 'XVIII', place: 'Monte Athos y Epiro', biography: 'Nació en 1714 en Megalo Dendro, en Etolia, en una familia de tejedores. Estudió tarde y con dificultad, fue maestro, y hacia 1759 entró en el monasterio de Filotheu, en el Monte Athos, donde se hizo monje con el nombre de Cosme y fue ordenado sacerdote.\n\nGrecia llevaba tres siglos bajo dominio otomano, y en muchas aldeas el pueblo apenas sabía leer ni conocía su fe. En 1760 Cosme obtuvo del patriarca de Constantinopla permiso para predicar, y durante veinte años recorrió a pie el Epiro, Macedonia, Tesalia, las islas y Albania. Hablaba en griego llano, en plazas y campos, con una gran cruz de madera plantada a su lado, y decía que había que abrir escuelas antes que iglesias. Se le atribuyen unas doscientas escuelas. Reconciliaba enemistades, pedía a la gente que dejara la usura y que guardara el domingo.\n\nSu popularidad inquietó a las autoridades otomanas y a algunos notables locales. En agosto de 1779 fue arrestado cerca de Berat, en Albania, y ahorcado sin juicio el día 24. Tiraron su cuerpo al río; unos cristianos lo recuperaron y lo enterraron en el monasterio de Kolikondasi.\n\nFue canonizado en 1961 y se le llama igual a los Apóstoles. Circulan con su nombre muchas profecías sobre el futuro de Grecia, recogidas de memoria por quienes lo oyeron. Se leen mucho, y buena parte de ellas se han ido adornando con el tiempo.' },

  /* ---------------- Septiembre ---------------- */
  { id: 'simeon-estilita', name: 'San Simeón el Estilita', day: '09-01', category: ['monje'], century: 'V', place: 'Siria', biography: 'Nació hacia 389 en Sis, en la frontera de Cilicia con Siria, y fue pastor. A los trece años oyó en la iglesia las Bienaventuranzas y se quedó con la idea de que sólo los que lloran serán consolados. Entró en un monasterio, pero sus penitencias eran tan extremas —se ató una cuerda a la cintura hasta que la carne se le pudrió— que los monjes acabaron por despedirlo.\n\nSe retiró como ermitaño a Telanisos, cerca de Antioquía, y empezaron a llegar peregrinos que lo tocaban y le arrancaban trozos de ropa. Para apartarse de ellos, hacia 423 subió a lo alto de una columna. La fue elevando con los años hasta unos quince metros, y vivió en ella treinta y siete años, a la intemperie, en una plataforma con una barandilla.\n\nNo estaba aislado: desde lo alto predicaba dos veces al día, oía confesiones, arbitraba pleitos entre aldeas, pedía justicia para los pobres y escribía a los emperadores. Defendió el Concilio de Calcedonia. Teodoreto de Ciro, que lo conoció en vida, cuenta que su fama llegaba hasta Hispania y Britania.\n\nMurió el 2 de septiembre de 459, y la Iglesia lo conmemora el 1, que es el primer día del año litúrgico. Alrededor de su columna se levantó una gran basílica, cuyas ruinas siguen en pie cerca de Alepo. Tuvo muchos imitadores, entre ellos san Daniel el Estilita y san Simeón el Joven.' },
  { id: 'exaltacion-s', name: 'Exaltación de la Cruz', day: '09-14', category: ['senor'], biography: 'La fiesta conmemora dos hechos. Según la tradición, hacia 326 santa Elena, madre de Constantino, buscó en Jerusalén el lugar de la Crucifixión y encontró tres cruces. Para saber cuál era la del Señor, el obispo Macario las acercó a una mujer moribunda, y ésta sanó al contacto de la tercera. En el lugar se construyó la basílica del Santo Sepulcro, dedicada un 13 de septiembre, y al día siguiente se mostró por primera vez la Cruz al pueblo.\n\nEn 614 los persas tomaron Jerusalén y se llevaron la reliquia. El emperador Heraclio la recuperó tras vencerlos y la devolvió a Jerusalén en 630. La tradición cuenta que, al intentar entrar en la ciudad con ropas imperiales, no pudo dar un paso hasta que se descalzó y se despojó de ellas.\n\nEl nombre de la fiesta viene del gesto litúrgico: el obispo levanta la Cruz en alto hacia los cuatro puntos cardinales, bajándola hasta el suelo y alzándola de nuevo, mientras el pueblo canta «Señor, ten piedad» cien veces seguidas. El rito se sigue haciendo. La Cruz se adorna con albahaca, que según la tradición crecía en el lugar donde fue hallada, y el sacerdote la reparte después.\n\nEs una de las doce grandes fiestas y la única que se celebra ayunando: se honra la Cruz, pero se recuerda también lo que costó. Su tropario, «Salva, Señor, a tu pueblo», es de los más cantados del año.' },
  { id: 'juan-teologo-dormicion', name: 'Dormición de San Juan el Teólogo', day: '09-26', category: ['apostol'], century: 'I', place: 'Éfeso', biography: 'Tras el destierro en Patmos, san Juan volvió a Éfeso, donde la tradición lo sitúa hasta el final de su vida, ya bajo el emperador Trajano y con cerca de cien años. Era el último superviviente de los doce.\n\nSan Jerónimo cuenta que, cuando ya no podía caminar, sus discípulos lo llevaban en brazos a la asamblea, y que allí sólo decía una cosa: «Hijitos, amaos los unos a los otros». Cansados de oír siempre lo mismo, le preguntaron por qué, y respondió que ése era el mandamiento del Señor, y que si se cumplía, bastaba.\n\nUn antiguo relato, los Hechos de Juan, cuenta que, sintiendo cerca el final, pidió a sus discípulos que cavaran una fosa en forma de cruz, se tendió en ella y les pidió que lo cubrieran. Cuando volvieron al día siguiente, el sepulcro estaba vacío. La Iglesia no ha convertido el relato en doctrina, pero lo recuerda en esta fiesta.\n\nSobre su tumba, en Éfeso, Justiniano levantó en el siglo VI una gran basílica, cuyas ruinas siguen en pie en la colina de Ayasoluk, en la actual Selçuk. La fiesta del 8 de mayo recuerda otra tradición del mismo sepulcro.' },
  { id: 'silvano-athonita', name: 'San Silvano del Monte Athos', day: '09-24', category: ['monje'], century: 'XIX–XX', place: 'Monasterio de San Panteleimón, Athos', biography: 'Se llamaba Simeón Antónov y nació en 1866 en Shovsk, en la región de Tambov, en una familia de campesinos. Era un joven fuerte y alegre, y en una pelea estuvo a punto de matar a un hombre. Poco después, según contó él mismo, vio en sueños a la Theotokos, que le reprochaba su vida. Tras el servicio militar, en 1892, se fue al monasterio ruso de San Panteleimón, en el Monte Athos, y allí fue tonsurado con el nombre de Silvano.\n\nSus primeros años fueron de una lucha interior muy dura, hasta rozar la desesperación. En ese estado, un día, durante las Vísperas, vio a Cristo vivo en la iglesia, y aquella visión lo marcó para siempre. Años después, en otra crisis, oyó en la oración una palabra que resume su enseñanza: «Mantén tu mente en el infierno y no desesperes». Es decir: verse a sí mismo sin engañarse, y confiar a la vez del todo en la misericordia de Dios.\n\nFue durante décadas ecónomo del monasterio, a cargo de los obreros, y los trataba con tanta bondad que muchos iban a verle sólo para hablar. Rezaba por el mundo entero con lágrimas, y decía que el criterio de la fe verdadera es el amor a los enemigos.\n\nMurió el 24 de septiembre de 1938. Su discípulo, el archimandrita Sofronio, publicó sus escritos junto con una biografía, y el libro se convirtió en un clásico. Fue canonizado en 1987.' },

  /* ---------------- Octubre ---------------- */
  { id: 'dionisio-areopagita', name: 'San Dionisio Areopagita', day: '10-03', category: ['obispo', 'martir'], century: 'I', place: 'Atenas', biography: 'Los Hechos de los Apóstoles cuentan que, cuando san Pablo habló en el Areópago de Atenas sobre el altar dedicado al dios desconocido, casi todos se burlaron al oírle hablar de la resurrección, pero algunos creyeron: entre ellos, Dionisio, miembro de aquel consejo. En el siglo II, Dionisio de Corinto dice que fue el primer obispo de Atenas, y así lo recuerda la tradición.\n\nMás tarde se le atribuyeron otros episodios: que en Heliópolis de Egipto vio el eclipse del día de la Crucifixión y exclamó que o sufría el Dios del universo o el mundo se venía abajo; que estuvo presente en la Dormición de la Theotokos, y que murió mártir en Atenas. En Occidente se le confundió con san Dionisio, el obispo mártir de París, una identificación que ya nadie sostiene.\n\nBajo su nombre circulan desde comienzos del siglo VI cuatro tratados —Sobre los nombres divinos, La jerarquía celeste, La jerarquía eclesiástica y La teología mística— y diez cartas. Tuvieron una influencia enorme: san Máximo el Confesor los comentó, y de ellos procede la clasificación de los nueve coros de ángeles y buena parte del vocabulario de la teología apofática.\n\nLa crítica los atribuye hoy a un autor sirio de hacia el año 500, muy influido por el neoplatonismo de Proclo. La Iglesia los sigue leyendo y los llama areopagíticos, sin sostener ya que los escribiera él.' },
  { id: 'demetrio-s', name: 'San Demetrio de Tesalónica', day: '10-26', category: ['granmartir'], century: 'IV', place: 'Tesalónica', biography: 'Según la tradición, era hijo de una familia noble de Tesalónica, cristiana en secreto, y llegó a ser oficial del ejército y magistrado de la ciudad. En lugar de perseguir a los cristianos, como se esperaba de él, predicaba abiertamente.\n\nHacia 306 llegó a Tesalónica el emperador Maximiano, que organizó juegos en honor de su victoria. Su campeón era un gladiador gigantesco, Lieo, que mataba a cuantos se le enfrentaban. Demetrio, que ya estaba preso en unos baños públicos, bendijo a un joven cristiano llamado Néstor, que se atrevió a luchar con Lieo y lo mató. Maximiano, furioso, mandó degollar a Néstor y atravesar con lanzas a Demetrio en su prisión.\n\nSobre el lugar de su muerte se levantó en el siglo V la basílica que todavía se conserva, reconstruida tras el incendio de 1917. Le llaman Mirobleta, el que mana mirra, por el aceite perfumado que según la tradición brota de su sepulcro. Los relatos de sus milagros, escritos en el siglo VII, lo presentan defendiendo a la ciudad durante los asedios de ávaros y eslavos.\n\nEs el patrono de Tesalónica y uno de los santos militares más venerados de los Balcanes y de Rusia, junto con san Jorge. Parte de sus reliquias, llevadas a Italia en la Edad Media, volvieron a Tesalónica en 1980.' },

  /* ---------------- Noviembre ---------------- */
  { id: 'miguel-arcangel', name: 'Arcángel Miguel', fullName: 'Sinaxis del Arcángel Miguel y todas las Potestades incorpóreas', day: '11-08', category: ['justo'], biography: 'Sinaxis de todas las potestades incorpóreas. El nombre de Miguel es una pregunta —«¿Quién como Dios?»— y la tradición la pone en su boca frente a la caída de Lucifer. La Escritura lo nombra en Daniel como protector del pueblo de Dios, en la carta de Judas disputando con el diablo por el cuerpo de Moisés, y en el Apocalipsis al frente de los ángeles en la guerra del cielo. Por eso se le llama archistratego, jefe de los ejércitos celestiales.\n\nCon él se honra a Gabriel, el mensajero de la Anunciación, a Rafael, que acompaña a Tobías, y a todos los ángeles. La fiesta reúne a los nueve coros que enumera el Areopagita: serafines, querubines y tronos; dominaciones, virtudes y potestades; principados, arcángeles y ángeles.\n\nSe fijó a comienzos del siglo IV, en un concilio de Laodicea que al mismo tiempo condenó los excesos de quienes daban a los ángeles un culto que sólo corresponde a Dios. Se celebra el día octavo del noveno mes, en el cómputo antiguo que empezaba el año en marzo: por los nueve coros, y por el octavo día, que en la tradición patrística es el de la eternidad.\n\nEn el ciclo de la semana, el lunes está dedicado a los ángeles. El milagro de Miguel en Colosas, donde desvió un río que iba a destruir su santuario, tiene fiesta propia el 6 de septiembre.' },
  { id: 'gregorio-palamas-nov', name: 'San Gregorio Palamás (traslación)', day: '11-14', category: ['obispo', 'padre'], century: 'XIV', biography: 'Es la segunda conmemoración del defensor del hesicasmo, el día de su muerte, junto al apóstol Felipe. Gregorio Palamás murió en Tesalónica el 14 de noviembre de 1359, después de una larga enfermedad, con sesenta y tres años y apenas nueve de episcopado efectivo: la guerra civil primero y el cautiverio entre los turcos después le habían tenido casi siempre lejos de su sede.\n\nSus últimos años fueron de pastor más que de polemista. Sus homilías para los domingos y fiestas del año, que se conservan, hablan poco de la controversia y mucho de la limosna, de la justicia con los pobres y de la oración, en una ciudad empobrecida y dividida.\n\nLa veneración empezó enseguida. En 1368, sólo nueve años después de su muerte, el patriarca Nilo lo canonizó y escribió su encomio, y la fiesta principal se trasladó al segundo domingo de Cuaresma, como prolongación del Triunfo de la Ortodoxia del domingo anterior. Que un teólogo del siglo XIV tenga un domingo cuaresmal es señal de hasta qué punto la Iglesia consideró decisivo lo que estaba en juego.\n\nSus reliquias se veneran en la catedral metropolitana de Tesalónica, que lleva su nombre.' },
  { id: 'entrada-theotokos-s', name: 'Entrada de la Theotokos en el Templo', day: '11-21', category: ['theotokos'], biography: 'Joaquín y Ana llevan al Templo a la Virgen de tres años, cumpliendo la promesa que habían hecho antes de tenerla. El relato no está en el Evangelio sino en el Protoevangelio de Santiago, un escrito del siglo II que la Iglesia no cuenta entre los libros inspirados pero cuya memoria conservó en la liturgia.\n\nCuenta que la acompañaron doncellas con lámparas encendidas para que la niña no se volviera atrás, que el sumo sacerdote Zacarías la recibió y la sentó en la tercera grada del altar, y que ella bailó de alegría. Los himnos de la fiesta añaden que fue conducida al Santo de los Santos, donde sólo entraba el sumo sacerdote una vez al año, y que allí vivió alimentada por un ángel hasta los doce años.\n\nLa fiesta nació en Jerusalén en el siglo VI, con la dedicación de la iglesia Nueva de la Theotokos, construida por Justiniano, y se extendió después a Constantinopla. Su sentido lo dicen los textos: la que va a ser el templo vivo de Dios entra en el templo de piedra, y lo que éste prefiguraba empieza a cumplirse.\n\nEs una de las doce grandes fiestas. Desde este día empiezan a cantarse los irmos de Navidad, «Cristo nace, glorificadle»: es el primer aviso de que la fiesta se acerca.' },

  /* ---------------- Diciembre ---------------- */
  { id: 'esteban-protomartir', name: 'San Esteban Protomártir', day: '12-27', category: ['martir'], century: 'I', place: 'Jerusalén', biography: 'Cuando en la primera comunidad de Jerusalén los cristianos de lengua griega se quejaron de que sus viudas quedaban desatendidas, los apóstoles eligieron a siete hombres para ocuparse del servicio de las mesas, y les impusieron las manos. El primero de ellos fue Esteban, «lleno de fe y del Espíritu Santo». La Iglesia ve en aquellos siete a los primeros diáconos.\n\nEsteban no se quedó en servir: hacía prodigios y discutía con los judíos de habla griega, que no podían resistir la sabiduría con que hablaba. Lo acusaron con falsos testigos de blasfemar contra el Templo y la Ley, y lo llevaron ante el sanedrín. Su discurso es el más largo de los Hechos y consiste casi entero en repasar la historia de Israel, para acabar acusando a sus jueces de resistir siempre al Espíritu Santo, y afirmando que el Altísimo no habita en templos hechos por mano de hombre.\n\nEntonces dijo ver los cielos abiertos y al Hijo del hombre de pie a la derecha de Dios. Lo sacaron de la ciudad y lo apedrearon, hacia el año 34. Murió diciendo «Señor Jesús, recibe mi espíritu» y pidiendo perdón para quienes lo mataban. Entre los que aprobaban su muerte estaba Saulo de Tarso, guardando la ropa de los ejecutores.\n\nSus reliquias se encontraron en 415 cerca de Jerusalén. La Iglesia lo conmemora dos días después de la Navidad, y en los iconos aparece vestido de diácono, con el incensario.' },

  /* ---------------- Padres y ancianos athonitas ---------------- */
  { id: 'isaac-sirio', name: 'San Isaac el Sirio', day: '01-28', category: ['obispo', 'monje', 'padre'], century: 'VII', place: 'Nínive', biography: 'Nació en el siglo VII en Beth Qatraye, la región del golfo Pérsico que corresponde a la actual Catar. Se hizo monje, y hacia 676 el católicos de la Iglesia de Oriente lo consagró obispo de Nínive. A los cinco meses renunció. Según una noticia antigua, lo hizo tras ver cómo se aplicaba la ley contra un deudor pobre, y comprender que un obispo no podía gobernar con los criterios del mundo.\n\nSe retiró a las montañas del Juzistán, en el actual Irán, y vivió en soledad y estudio hasta quedarse ciego. Dictaba a sus discípulos. Murió muy anciano.\n\nEscribió en siriaco. Pertenecía a la Iglesia de Oriente, separada del resto desde el siglo V, y aun así sus Discursos ascéticos fueron traducidos al griego en el siglo IX por dos monjes de San Sabas, en Palestina, y desde entonces se leen en todos los monasterios ortodoxos. Es de los pocos casos en que la tradición recibió a un autor por encima de las fronteras de comunión.\n\nSu tema es la misericordia. Define el corazón misericordioso como un corazón que arde por toda la creación, por los hombres, los pájaros, los animales y hasta los demonios, y que no soporta ver el menor daño hecho a una criatura. Dostoievski lo menciona en Los hermanos Karamázov: es el libro que lee el viejo criado Grigori.' },
  { id: 'juan-damasceno', name: 'San Juan Damasceno', day: '12-04', category: ['monje', 'padre'], century: 'VII–VIII', place: 'Damasco y San Sabas', biography: 'Nació hacia 675 en Damasco, capital del califato omeya, en una familia cristiana de lengua árabe y griega, los Mansur. Su abuelo y su padre habían sido altos funcionarios de las finanzas bajo los califas, y Juan heredó el cargo. Se educó con un monje siciliano rescatado del cautiverio, junto a su hermano adoptivo, que sería san Cosme el Melodista.\n\nHacia 706 dejó la corte y se retiró con Cosme al monasterio de San Sabas, cerca de Jerusalén, donde fue ordenado sacerdote. Cuando en 726 el emperador León III empezó a destruir los iconos, Juan, que vivía bajo dominio musulmán y fuera de su alcance, escribió los Tres discursos contra los que atacan las santas imágenes. Su argumento central es la Encarnación: el Dios invisible se hizo visible, y lo que se ha visto se puede representar. La veneración que se da a la imagen pasa a quien representa.\n\nEscribió también La fuente del conocimiento, cuya tercera parte, la Exposición exacta de la fe ortodoxa, fue durante siglos el manual de teología de Oriente y de Occidente. Fue un gran poeta litúrgico: suyo es el Canon Pascual, «Día de la Resurrección», y la tradición le atribuye buena parte del Octoecos. Según una leyenda, le cortaron la mano derecha por calumnia y la Theotokos se la restituyó: de ahí el icono de la Tricherusa, la de las tres manos.\n\nEl concilio iconoclasta de 754 lo anatematizó; el segundo Concilio de Nicea, en 787, lo rehabilitó. Murió hacia 749 en San Sabas.' },
  { id: 'maximo-confesor', name: 'San Máximo el Confesor', day: '01-21', category: ['monje', 'confesor', 'padre'], century: 'VII', place: 'Constantinopla', biography: 'Nació hacia 580, en Constantinopla según su Vida griega o en Palestina según una biografía siriaca hostil, y la cuestión sigue abierta. Fue secretario en la corte del emperador Heraclio, y hacia 614 lo dejó todo para hacerse monje en Crisópolis, frente a la capital. La invasión persa lo empujó hacia el sur, y acabó en Cartago, junto a san Sofronio de Jerusalén.\n\nPor entonces el emperador buscaba reconciliar a los que rechazaban Calcedonia con una fórmula de compromiso: en Cristo habría dos naturalezas, pero una sola voluntad. Máximo vio que eso deshacía la Encarnación: si Cristo no tiene voluntad humana, no ha asumido al hombre entero, y lo que no se asume no se salva. En 645 venció en debate público al expatriarca Pirro, y en 649 inspiró el sínodo de Letrán, que con el papa Martín condenó el monotelismo.\n\nEn 653 lo arrestaron en Roma y lo llevaron a Constantinopla. Le ofrecieron la libertad a cambio de entrar en comunión con el patriarca; contestó que aunque todo el mundo comulgara con él, él no. En 662, tras un segundo juicio, le cortaron la lengua y la mano derecha para que no pudiera hablar ni escribir, y lo desterraron al Cáucaso, donde murió el 13 de agosto de ese año.\n\nDiecinueve años después, el sexto Concilio Ecuménico le dio la razón. Sus obras —los Capítulos sobre la caridad, la Mistagogia, los Ambigua— hacen de él el mayor teólogo bizantino del siglo VII.' },
  { id: 'juan-kronstadt', name: 'San Juan de Kronstadt', day: '12-20', category: ['justo'], century: 'XIX–XX', place: 'Kronstadt, Rusia', biography: 'Se llamaba Iván Serguéiev y nació en 1829 en Sura, un pueblo del norte de Rusia, hijo de un sacristán pobre. En la escuela no conseguía aprender, hasta que, según contaba, rezando una noche se le abrió de golpe el entendimiento. Estudió en la Academia Teológica de San Petersburgo, se casó con Isabel, hija del arcipreste de la catedral de San Andrés de Kronstadt, y en 1855 fue ordenado sacerdote para esa iglesia, en la que sirvió cincuenta y tres años. El matrimonio vivió en continencia.\n\nKronstadt era una base naval llena de obreros sin trabajo, borrachera y miseria. El padre Juan se metía en los sótanos, daba su dinero, y fundó la Casa de la Laboriosidad, con talleres, escuela, comedor y albergue. Celebraba la Liturgia todos los días y animaba a comulgar con frecuencia, cuando lo habitual era hacerlo una vez al año. Las multitudes llegaron a ser tan grandes que introdujo la confesión general en voz alta.\n\nSe le atribuían curaciones y recibía cartas y visitas de toda Rusia. Su diario espiritual, Mi vida en Cristo, sigue siendo una de las guías de oración más leídas. En sus últimos años se opuso con dureza a Tolstói y se acercó a los círculos monárquicos más conservadores, y esas posiciones políticas se siguen discutiendo.\n\nMurió el 20 de diciembre de 1908 y está enterrado en el convento de San Juan, en San Petersburgo. Lo canonizaron la Iglesia rusa en el exilio en 1964 y el Patriarcado de Moscú en 1990.' },
  { id: 'teofano-recluso', name: 'San Teófano el Recluso', day: '01-10', category: ['obispo'], century: 'XIX', place: 'Vysha, Rusia', biography: 'Se llamaba Gueorgui Góvorov y nació en 1815 en Chernavsk, hijo del sacerdote del pueblo. Estudió en la Academia Teológica de Kiev, donde se hizo monje en 1841 con el nombre de Teófano. Pasó años en la misión rusa de Jerusalén y en Constantinopla, conoció de cerca el monacato griego y el del Sinaí, y fue rector de la Academia de San Petersburgo.\n\nFue obispo de Tambov y después de Vladímir, y a los cincuenta y un años, en 1866, pidió el retiro. Se instaló en el monasterio de Vysha, y desde 1872 no volvió a salir de sus dos habitaciones: celebraba la Liturgia solo en una capilla dentro de ellas y sólo recibía al abad y a su confesor.\n\nAquel encierro fue el periodo más fecundo de su vida. Tradujo al ruso la Filocalia, en cinco volúmenes, y la hizo accesible a los laicos. Escribió libros como El camino de la salvación y Qué es la vida espiritual, y respondió por carta a miles de personas: cada día llegaban decenas, y las contestaba todas. Su enseñanza sobre la oración se resume en una fórmula que ha quedado: bajar con la mente al corazón y estar allí ante Dios.\n\nMurió el 6 de enero de 1894, día de la Teofanía, y lo encontraron con las manos cruzadas como para recibir la Comunión. Fue canonizado en 1988.' },
  { id: 'paisios-athonita', name: 'San Paisios del Monte Athos', day: '07-12', category: ['monje'], century: 'XX', place: 'Monte Athos', biography: 'Se llamaba Arsenios Eznepidis y nació el 25 de julio de 1924 en Fárasa, en Capadocia. Lo bautizó san Arsenio de Capadocia, que le dio su propio nombre. Semanas después, con el intercambio de poblaciones entre Grecia y Turquía, su familia tuvo que abandonarlo todo y se estableció en Kónitsa, en el Epiro. Allí creció, trabajó como carpintero y sirvió como radiotelegrafista durante la guerra civil.\n\nEn 1950 subió al Monte Athos. Fue monje en Esfigmenu y en Filotheu, donde recibió el nombre de Paisios, pasó unos años en el monasterio de Stomio, junto a Kónitsa, y otros dos en el Sinaí, en una celda aislada. En 1966 le extirparon parte de un pulmón. Volvió a la Montaña y vivió en ermitas cada vez más apartadas, hasta instalarse en 1979 en la celda de Panagúda, junto a Kutlumusiu. Ayudó además a fundar el convento de mujeres de San Juan el Teólogo en Suroti, cerca de Tesalónica.\n\nA su puerta llegaban cada día decenas y a veces centenares de visitantes: monjes, estudiantes, gente angustiada. Los recibía en el patio, con un vaso de agua y una delicia turca, y hablaba sencillo, con humor y con ejemplos del campo. Insistía en el buen pensamiento, en ver a los demás con los ojos de Cristo, y en rezar por el mundo entero.\n\nMurió de cáncer el 12 de julio de 1994 en Suroti, donde está enterrado. Fue canonizado en 2015. Sus consejos, recogidos por las monjas y por quienes lo trataron, se publican en varios volúmenes.' },
  { id: 'porfirio-kavsokalivita', name: 'San Porfirio Kavsokalivita', day: '12-02', category: ['monje'], century: 'XX', place: 'Athos y Atenas', biography: 'Se llamaba Evangelos Bairaktaris y nació en 1906 en una aldea de Eubea, en una familia muy pobre. De niño trabajó en una tienda de Calcis y en otra del Pireo. Leyó la vida de san Juan el Calibita y quiso imitarla, y a los doce años se escapó al Monte Athos, a la skete de Kavsokalivia, donde dos ancianos lo tomaron como discípulo. Fue tonsurado con el nombre de Nicetas.\n\nMuy joven recibió, según contaba, un don de discernimiento que le permitía ver el interior de las personas. Una pleuresía lo obligó a dejar el Athos a los diecinueve años. En 1927 fue ordenado sacerdote con el nombre de Porfirio y empezó a confesar en Eubea.\n\nDesde 1940 y durante treinta y tres años fue capellán de la Policlínica de Atenas, junto a la plaza Omonia, atendiendo a enfermos y a una fila interminable de gente que buscaba consejo. Fundó un monasterio en Milesi, en el Ática. Enseñaba que la vida cristiana no se hace a base de miedo ni de lucha contra el mal, sino dejando entrar el amor de Cristo, que desplaza lo demás como la luz desplaza a la oscuridad.\n\nPoco antes de morir volvió a Kavsokalivia, y allí murió el 2 de diciembre de 1991, como había pedido, sin que nadie supiera dónde ni cuándo, para que no se hiciera ruido en torno a él. Fue canonizado en 2013.' },
  { id: 'sergio-radonezh', name: 'San Sergio de Rádonezh', day: '09-25', category: ['monje'], century: 'XIV', place: 'Rusia', biography: 'Se llamaba Bartolomé y nació hacia 1314 cerca de Rostov, en una familia de boyardos empobrecidos que se mudó a Rádonezh. De niño no conseguía aprender a leer, hasta que, según su Vida, un anciano monje lo bendijo en el campo y desde entonces leyó sin dificultad.\n\nMuertos sus padres, se internó en el bosque con su hermano Esteban y construyó en el cerro de Makóvets una pequeña iglesia dedicada a la Santísima Trinidad. El hermano no aguantó la soledad y se marchó. Bartolomé se hizo monje con el nombre de Sergio y vivió solo, entre osos y privaciones, hasta que empezaron a llegar discípulos. En 1354 aceptó ser su abad, y por consejo del patriarca de Constantinopla introdujo la vida común: nadie tenía nada propio. Él mismo trabajaba de carpintero y cocinero.\n\nRechazó ser metropolitano de Moscú. Pero su autoridad moral era enorme: reconcilió a príncipes enfrentados y, en 1380, bendijo al gran príncipe Dimitri Donskói antes de la batalla de Kulikovo contra los tártaros, la primera gran victoria rusa sobre la Horda de Oro.\n\nMurió el 25 de septiembre de 1392. Sus discípulos fundaron decenas de monasterios que llevaron el monacato hasta el norte de Rusia. Su monasterio es hoy la Laura de la Trinidad y San Sergio, y el famoso icono de la Trinidad de Rubliov se pintó para ella, en su honor.' },
  { id: 'ambrosio-optina', name: 'San Ambrosio de Óptina', day: '10-10', category: ['monje'], century: 'XIX', place: 'Óptina, Rusia', biography: 'Se llamaba Alexandr Grenkov y nació en 1812 en Bolshaya Lipovitsa, en la región de Tambov, hijo de un sacristán. Estudió en el seminario de Tambov y fue profesor en Lipetsk. Durante una grave enfermedad prometió hacerse monje si sanaba; tardó en cumplirlo, hasta que en 1839 se marchó sin avisar a nadie al monasterio de Óptina.\n\nAllí fue discípulo de los stárets León y Macario, que habían traído a Óptina la tradición de la dirección espiritual de san Paisio Velichkovski. Fue tonsurado con el nombre de Ambrosio y ordenado sacerdote en 1845. Al año siguiente una enfermedad lo dejó inválido para el resto de su vida: pasaría casi cincuenta años recibiendo a la gente echado en un diván.\n\nA la muerte del stárets Macario, en 1860, se convirtió en el guía espiritual de toda una generación. Recibía desde el amanecer hasta la noche a campesinas, comerciantes, estudiantes y escritores, y respondía decenas de cartas al día. Lo buscaron Dostoievski, que fue a verle en 1878 tras la muerte de su hijo pequeño y se inspiró en él para el stárets Zósima de Los hermanos Karamázov, el filósofo Soloviov, Leóntiev y también Tolstói.\n\nFundó el convento de mujeres de Shamordino, cerca de Óptina, y allí murió el 10 de octubre de 1891. Fue canonizado en 1988, en el concilio que celebró el milenio del bautismo de la Rus.' },
];

const troparia: Record<string, TextBlock[]> = {
  pascua: [
    { kind: 'text', content: 'Cristo ha resucitado de entre los muertos, con su muerte ha vencido a la muerte y a los que estaban en los sepulcros les ha dado la vida.' },
  ],
};

/** Primera tanda y ampliación, ordenadas por su día del calendario. */
const allSeeds: SaintSeed[] = [
  ...seeds,
  ...MORE_SAINTS,
  ...THIRD_SAINTS,
  ...YEAR_SAINTS_1,
  ...YEAR_SAINTS_2,
].sort((a, b) =>
  a.day === b.day ? a.name.localeCompare(b.name, 'es') : a.day.localeCompare(b.day),
);

export const SAINTS: Saint[] = allSeeds.map((s) => ({
  id: s.id,
  name: s.name,
  fullName: s.fullName,
  day: s.day,
  category: s.category,
  century: s.century,
  place: s.place,
  biography: s.biography,
  troparion: s.troparion ?? troparia[s.id] ?? pendingHymn,
  kontakion: pendingHymn,
  status: s.status ?? 'partial',
  meta: bio,
  searchText: `${s.name} ${s.fullName ?? ''} ${s.place ?? ''} ${s.biography}`.toLowerCase(),
}));

export const SAINT_CATEGORY_LABELS: Record<SaintCategory, string> = {
  apostol: 'Apóstol',
  martir: 'Mártir',
  granmartir: 'Gran Mártir',
  confesor: 'Confesor',
  monje: 'Monje',
  obispo: 'Obispo',
  profeta: 'Profeta',
  justo: 'Justo',
  neomartir: 'Neomártir',
  padre: 'Padre de la Iglesia',
  theotokos: 'Theotokos',
  senor: 'Fiesta del Señor',
};

const byDay = new Map<string, Saint[]>();
for (const saint of SAINTS) {
  for (const day of [saint.day, ...(saint.otherDays ?? [])]) {
    const list = byDay.get(day) ?? [];
    list.push(saint);
    byDay.set(day, list);
  }
}

export function saintsOnDay(monthDay: string): Saint[] {
  return byDay.get(monthDay) ?? [];
}

export const SAINTS_COVERAGE_NOTE =
  `El santoral de ATHOS reúne ${SAINTS.length} conmemoraciones con su vida escrita, y no queda ` +
  'ningún día del año sin al menos una. Aun así, esto no es el Menaion: el libro completo trae ' +
  'varios santos cada día, y aquí hay una selección. Las vidas son reseñas históricas redactadas ' +
  'para ATHOS. En cuanto a los troparios: el propio de cada santo sigue sin incorporarse —son ' +
  'cientos y ATHOS no los escribe—, pero ninguna ficha se queda muda, porque se muestra el ' +
  'tropario general de su rango, que es justo lo que la Iglesia canta cuando no dispone del ' +
  'propio. Las grandes fiestas llevan el suyo. Ambos van traducidos del griego para ATHOS y su ' +
  'ficha lo dice.';

/** Cuántos días del año tienen conmemoración. Los 366 desde agosto de 2026. */
export const SAINT_DAYS_COVERED = new Set(SAINTS.map((s) => s.day)).size;

/** Días del año que ya tienen alguna conmemoración incorporada. */
export const SAINT_DAYS = new Set(SAINTS.map((s) => s.day));
