/**
 * Ampliación del santoral.
 *
 * Segunda tanda de conmemoraciones, con el mismo criterio que la primera: las
 * biografías son reseñas históricas redactadas para ATHOS a partir de fuentes
 * hagiográficas comunes, y los troparios sólo se incluyen si hay versión
 * española verificable. Aquí no hay ninguno todavía, así que todos figuran
 * como pendientes.
 */
import type { SaintCategory } from '@/types';

export interface SaintSeedMore {
  id: string;
  name: string;
  fullName?: string;
  day: string;
  category: SaintCategory[];
  century?: string;
  place?: string;
  biography: string;
}

export const MORE_SAINTS: SaintSeedMore[] = [
  /* ---------------- Enero ---------------- */
  { id: 'silvestre-roma', name: 'San Silvestre de Roma', day: '01-02', category: ['obispo'], century: 'IV', place: 'Roma', biography: 'Papa de Roma († 335) durante el reinado de Constantino, en los años en que la Iglesia pasó de la persecución a la libertad. Bajo su pontificado se celebró el Concilio de Nicea y se levantaron las primeras grandes basílicas romanas.' },
  { id: 'teodosio-cenobiarca', name: 'San Teodosio el Cenobiarca', day: '01-11', category: ['monje'], century: 'V–VI', place: 'Desierto de Judea', biography: 'Organizó la vida común de los monjes del desierto de Judea († 529). Su monasterio, cerca de Belén, llegó a albergar a centenares de monjes de distintas lenguas, con iglesias separadas para cada una y un hospital abierto a todos. Murió a los ciento cinco años.' },
  { id: 'pablo-tebas', name: 'San Pablo de Tebas', fullName: 'San Pablo, primer ermitaño', day: '01-15', category: ['monje'], century: 'III–IV', place: 'Tebaida, Egipto', biography: 'Primero de los anacoretas cristianos († c. 341). Huyó de la persecución de Decio a una cueva del desierto egipcio y allí permaneció noventa años. San Antonio lo encontró ya anciano y lo enterró con sus propias manos.' },
  { id: 'eutimio-grande', name: 'San Eutimio el Grande', day: '01-20', category: ['monje'], century: 'IV–V', place: 'Palestina', biography: 'Fundador de la laura que lleva su nombre en el desierto de Judea († 473). Formó a una generación entera de monjes palestinos y sostuvo la fe de Calcedonia cuando casi toda la región se inclinaba al monofisismo.' },
  { id: 'timoteo-apostol', name: 'San Timoteo Apóstol', day: '01-22', category: ['apostol', 'martir'], century: 'I', place: 'Éfeso', biography: 'Discípulo predilecto de san Pablo, que le dirigió dos cartas y lo llamó «hijo verdadero en la fe». Fue el primer obispo de Éfeso y murió apedreado por oponerse a una fiesta pagana.' },
  { id: 'xenia-petersburgo', name: 'Santa Xenia de San Petersburgo', day: '01-24', category: ['justo'], century: 'XVIII', place: 'San Petersburgo', biography: 'Enviudó a los veintiséis años y lo repartió todo. Se vistió con el uniforme de su marido, tomó su nombre y vivió cuarenta y cinco años en la calle, tenida por loca. Los albañiles de la iglesia de Smolensk descubrieron que era ella quien subía los ladrillos de noche. Canonizada en 1988.' },
  { id: 'efren-sirio-santo', name: 'San Efrén el Sirio', day: '01-28', category: ['monje', 'padre'], century: 'IV', place: 'Nísibis y Edesa', biography: 'Diácono y poeta († 373), llamado «el arpa del Espíritu Santo». Escribió en siríaco millares de himnos que enseñaban la fe cantando. Su oración cuaresmal —«Señor y Soberano de mi vida»— se reza con postraciones en toda la Iglesia.' },
  { id: 'ignacio-antioquia', name: 'San Ignacio de Antioquía', fullName: 'San Ignacio el Teóforo', day: '01-29', category: ['obispo', 'martir', 'padre'], century: 'I–II', place: 'Antioquía y Roma', biography: 'Obispo de Antioquía llevado a Roma para morir en el circo († c. 107). Por el camino escribió siete cartas que son el testimonio más antiguo del episcopado y de la Eucaristía. «Soy trigo de Dios: que me muelan los dientes de las fieras para ser pan limpio de Cristo».' },

  /* ---------------- Febrero ---------------- */
  { id: 'simeon-justo', name: 'San Simeón el Justo y Santa Ana profetisa', day: '02-03', category: ['justo', 'profeta'], century: 'I', place: 'Jerusalén', biography: 'El anciano que recibió al Niño en el Templo y pronunció el «Ahora, Señor, despides a tu siervo en paz», y la profetisa Ana, viuda de ochenta y cuatro años que no se apartaba del Templo. Se conmemoran al día siguiente del Encuentro.' },
  { id: 'isidoro-pelusiota', name: 'San Isidoro de Pelusio', day: '02-04', category: ['monje', 'padre'], century: 'IV–V', place: 'Egipto', biography: 'Monje egipcio († c. 450) del que se conservan cerca de dos mil cartas, breves y directas, dirigidas a obispos, funcionarios y monjes. Defendió a san Juan Crisóstomo cuando casi nadie se atrevía.' },
  { id: 'fotio-constantinopla', name: 'San Focio el Grande', day: '02-06', category: ['obispo', 'padre'], century: 'IX', place: 'Constantinopla', biography: 'Patriarca de Constantinopla († 893) y uno de los hombres más cultos de su siglo; su Biblioteca resume trescientas obras antiguas, muchas hoy perdidas. Envió a Cirilo y Metodio a los eslavos y se opuso a la añadidura del Filioque.' },
  { id: 'meletio-antioquia', name: 'San Meletio de Antioquía', day: '02-12', category: ['obispo'], century: 'IV', place: 'Antioquía', biography: 'Arzobispo de Antioquía († 381), desterrado tres veces por los arrianos. Presidió el inicio del Segundo Concilio Ecuménico y murió durante sus sesiones; san Gregorio de Nisa pronunció su elogio fúnebre.' },
  { id: 'onesimo', name: 'San Onésimo', day: '02-15', category: ['apostol'], century: 'I', biography: 'El esclavo fugitivo por quien san Pablo escribió la carta a Filemón, pidiendo que lo recibiera «no ya como esclavo, sino como hermano amado». La tradición lo hace después obispo y mártir.' },
  { id: 'leon-magno', name: 'San León Magno', day: '02-18', category: ['obispo', 'padre'], century: 'V', place: 'Roma', biography: 'Papa de Roma († 461). Su Tomo a Flaviano fue leído en Calcedonia y los Padres exclamaron: «Pedro ha hablado por boca de León». Salió al encuentro de Atila y logró que se retirara de Italia.' },
  { id: 'tarasio', name: 'San Tarasio de Constantinopla', day: '02-25', category: ['obispo'], century: 'VIII–IX', place: 'Constantinopla', biography: 'Alto funcionario imperial elegido patriarca († 806). Convocó el Séptimo Concilio Ecuménico, que restauró la veneración de los iconos, y repartió las rentas del patriarcado entre los pobres de la capital.' },

  /* ---------------- Marzo ---------------- */
  { id: 'gerasimo-jordan', name: 'San Gerásimo del Jordán', day: '03-04', category: ['monje'], century: 'V', place: 'Valle del Jordán', biography: 'Fundó una laura junto al Jordán († 475). La tradición cuenta que curó a un león herido y que la fiera lo siguió hasta su muerte, negándose después a comer sobre su tumba.' },
  { id: 'obispos-quersoneso', name: 'Los santos obispos de Quersoneso', day: '03-07', category: ['obispo', 'martir'], century: 'IV', place: 'Crimea', biography: 'Siete obispos enviados a evangelizar Crimea, casi todos martirizados por los habitantes. De aquella semilla nació la cristiandad de la que después bebería la Rus de Kiev.' },
  { id: 'sofronio-jerusalen', name: 'San Sofronio de Jerusalén', day: '03-11', category: ['obispo', 'padre'], century: 'VI–VII', place: 'Jerusalén', biography: 'Patriarca de Jerusalén († 638) que hubo de entregar la ciudad al califa Omar. Escribió la Vida de santa María Egipcíaca y los versos de la Gran Bendición de las Aguas que aún se cantan en la Teofanía.' },
  { id: 'teofano-cronista', name: 'San Teófanes el Confesor', day: '03-12', category: ['monje', 'confesor'], century: 'VIII–IX', place: 'Bitinia', biography: 'Noble que dejó la corte por el monasterio († 818). Su Cronografía es una de las fuentes principales de la historia bizantina. Murió desterrado por defender los iconos.' },
  { id: 'benito-nursia', name: 'San Benito de Nursia', day: '03-14', category: ['monje'], century: 'V–VI', place: 'Montecasino', biography: 'Padre del monacato occidental († 547). Su Regla, breve y templada, ordenó la vida de los monasterios de Occidente durante mil años. La Iglesia ortodoxa lo venera entre los santos del período indiviso.' },
  { id: 'alexis-hombre-dios', name: 'San Alejo, el hombre de Dios', day: '03-17', category: ['justo'], century: 'V', place: 'Roma y Edesa', biography: 'Hijo de un senador romano que huyó la noche de su boda para vivir de limosna en Edesa. Volvió irreconocible a casa de su padre y pasó allí diecisiete años bajo la escalera, sin decir quién era.' },
  { id: 'cirilo-jerusalen', name: 'San Cirilo de Jerusalén', day: '03-18', category: ['obispo', 'padre'], century: 'IV', place: 'Jerusalén', biography: 'Arzobispo de Jerusalén († 386). Sus Catequesis, dirigidas a los que iban a bautizarse, describen la iniciación cristiana con un detalle que ninguna otra fuente antigua iguala.' },
  { id: 'juan-escala-marzo', name: 'San Juan Clímaco', day: '03-30', category: ['monje', 'padre'], century: 'VI–VII', place: 'Monte Sinaí', biography: 'Abad del Sinaí († c. 649), autor de La Escala Santa, treinta peldaños de ascenso espiritual que se leen en los monasterios cada Cuaresma. El cuarto domingo de la Gran Cuaresma lleva su nombre.' },

  /* ---------------- Abril ---------------- */
  { id: 'tito-taumaturgo', name: 'San Tito el Taumaturgo', day: '04-02', category: ['monje'], century: 'IX', biography: 'Monje del monasterio de Estudion en Constantinopla, célebre por su mansedumbre y su firmeza frente a los iconoclastas.' },
  { id: 'jorge-maleo', name: 'San Jorge de Maleo', day: '04-04', category: ['monje'], century: 'IX', place: 'Peloponeso', biography: 'Monje del Peloponeso que dejó una vida acomodada por la montaña de Maleo, donde vivió en soledad y atrajo a numerosos discípulos.' },
  { id: 'metodio-eslavos', name: 'San Metodio, igual a los Apóstoles', day: '04-06', category: ['obispo'], century: 'IX', place: 'Moravia', biography: 'Hermano mayor de san Cirilo († 885). Tras la muerte de éste continuó solo la misión entre los eslavos: tradujo casi toda la Escritura al eslavo y defendió esa liturgia frente al clero germánico, que lo tuvo dos años en prisión.' },
  { id: 'antipas-pergamo', name: 'San Antipas de Pérgamo', day: '04-11', category: ['obispo', 'martir'], century: 'I', place: 'Pérgamo', biography: 'Obispo de Pérgamo nombrado en el Apocalipsis: «mi testigo fiel, que fue muerto entre vosotros» (Ap 2, 13). Murió dentro de un toro de bronce al rojo.' },
  { id: 'martin-confesor', name: 'San Martín el Confesor', day: '04-14', category: ['obispo', 'confesor'], century: 'VII', place: 'Roma y Quersoneso', biography: 'Papa de Roma († 655). Condenó el monotelismo en el Concilio de Letrán y el emperador lo hizo secuestrar, juzgar y desterrar a Crimea, donde murió de hambre y frío. Último papa venerado como mártir.' },
  { id: 'sabas-godo', name: 'San Sabas el Godo', day: '04-15', category: ['martir'], century: 'IV', place: 'Dacia', biography: 'Lector godo ahogado en el río Musaios el año 372 por negarse a comer carne sacrificada a los ídolos. Su martirio está contado en una carta contemporánea, uno de los documentos hagiográficos más fiables de la Antigüedad.' },
  { id: 'juan-antiguo', name: 'San Juan el Antiguo de Palestina', day: '04-19', category: ['monje'], century: 'VI', place: 'Palestina', biography: 'Monje de la laura de San Sabas, maestro de vida interior y autor de sentencias recogidas en las colecciones de los Padres del desierto.' },
  { id: 'teodoro-siceota', name: 'San Teodoro el Siceota', day: '04-22', category: ['obispo', 'monje'], century: 'VI–VII', place: 'Galacia', biography: 'Obispo de Anastasiópolis († 613) que renunció a la sede para volver al monasterio. Su Vida, escrita por un discípulo, es un retrato vivísimo de la Anatolia rural de su tiempo.' },
  { id: 'juan-atalla', name: 'San Simeón, pariente del Señor', day: '04-27', category: ['obispo', 'martir'], century: 'I–II', place: 'Jerusalén', biography: 'Pariente del Señor y segundo obispo de Jerusalén, sucesor de Santiago el Hermano del Señor. Guio a la comunidad durante la guerra judía y la huida a Pella. Fue crucificado bajo Trajano a los ciento veinte años, según cuenta Eusebio, que se apoya en Hegesipo.' },

  /* ---------------- Mayo ---------------- */
  { id: 'atanasio-mayo', name: 'San Atanasio el Grande (traslación)', day: '05-02', category: ['obispo', 'padre'], century: 'IV', place: 'Alejandría', biography: 'Segunda conmemoración del arzobispo de Alejandría, en recuerdo del traslado de sus reliquias. La principal es el 18 de enero.' },
  { id: 'irene-macedonia', name: 'Santa Irene de Tesalónica', day: '05-05', category: ['granmartir'], century: 'IV', place: 'Macedonia', biography: 'Hija de un gobernante pagano, encerrada por su padre en una torre para apartarla del cristianismo. Convertida, sufrió el martirio bajo Diocleciano. Su nombre significa «paz».' },
  { id: 'job-paciente', name: 'Santo Job el Paciente', day: '05-06', category: ['justo'], century: 'antes de Cristo', place: 'Uz', biography: 'El justo del Antiguo Testamento que lo perdió todo sin maldecir a Dios. Su libro se lee íntegro en la Semana Santa, porque la Iglesia ve en su padecer una figura del de Cristo.' },
  { id: 'simon-zelote', name: 'San Simón el Zelote', day: '05-10', category: ['apostol'], century: 'I', biography: 'Uno de los Doce, llamado el Zelote o el Cananeo. La tradición lo hace predicar en Persia y Georgia, y morir crucificado.' },
  { id: 'epifanio-chipre', name: 'San Epifanio de Chipre', day: '05-12', category: ['obispo', 'padre'], century: 'IV–V', place: 'Salamina de Chipre', biography: 'Arzobispo de Salamina († 403). Su Panarion cataloga ochenta herejías y conserva citas de obras hoy perdidas. Fue implacable con el error y proverbialmente generoso con los pobres.' },
  { id: 'pacomio-grande', name: 'San Pacomio el Grande', day: '05-15', category: ['monje'], century: 'IV', place: 'Tabenna, Egipto', biography: 'Soldado convertido que fundó el primer monasterio cenobítico propiamente dicho († 348). Antes de él los monjes vivían dispersos; Pacomio les dio muros, horario y regla escrita, y con ello nació la vida común.' },
  { id: 'teodoro-estudita', name: 'San Teodoro Estudita', day: '11-11', category: ['monje', 'confesor'], century: 'VIII–IX', place: 'Constantinopla', biography: 'Abad del monasterio de Estudion († 826). Reformó el monacato urbano bizantino con una regla que se copió durante siglos, y sufrió destierro y azotes por defender los iconos. Sus catequesis a los monjes se siguen leyendo.' },
  { id: 'ciril-metodio', name: 'Santos Cirilo y Metodio', day: '05-11', category: ['obispo'], century: 'IX', place: 'Tesalónica y Moravia', biography: 'Los dos hermanos de Tesalónica que crearon el alfabeto eslavo y tradujeron la Escritura y los oficios, dando a los pueblos eslavos una lengua litúrgica propia. Su obra cambió la historia de media Europa.' },
  { id: 'juan-ruso', name: 'San Juan el Ruso', day: '05-27', category: ['justo'], century: 'XVIII', place: 'Prokopi, Eubea', biography: 'Soldado ruso hecho prisionero por los turcos († 1730). Sirvió de esclavo en Capadocia durante años sin renegar de su fe, durmiendo en el establo. Sus reliquias, veneradas hoy en Eubea, atraen a miles de peregrinos.' },

  /* ---------------- Junio ---------------- */
  { id: 'nicéforo-confesor', name: 'San Nicéforo el Confesor', day: '06-02', category: ['obispo', 'confesor'], century: 'VIII–IX', place: 'Constantinopla', biography: 'Patriarca de Constantinopla († 828), depuesto y desterrado por negarse a condenar los iconos. Escribió una historia bizantina y tres tratados en defensa de las imágenes.' },
  { id: 'metrofanes', name: 'San Metrófanes de Constantinopla', day: '06-04', category: ['obispo'], century: 'IV', place: 'Constantinopla', biography: 'Primer obispo de Bizancio cuando la ciudad se convirtió en capital († 326). Anciano y enfermo, no pudo acudir a Nicea y envió en su lugar a su corepíscopo.' },
  { id: 'ciril-alejandria', name: 'San Cirilo de Alejandría', day: '06-09', category: ['obispo', 'padre'], century: 'IV–V', place: 'Alejandría', biography: 'Patriarca de Alejandría († 444). Defendió en Éfeso que María es verdaderamente Theotokos, Madre de Dios, porque el que nació de ella es una sola persona divina. Su cristología marcó todos los concilios posteriores.' },
  { id: 'bartolome-apostol', name: 'San Bartolomé Apóstol', day: '06-11', category: ['apostol'], century: 'I', place: 'Armenia', biography: 'Uno de los Doce, identificado con el Natanael del Evangelio de Juan. Predicó en la India y Armenia, donde fue desollado vivo.' },
  { id: 'onofre-grande', name: 'San Onofre el Grande', day: '06-12', category: ['monje'], century: 'IV', place: 'Tebaida', biography: 'Anacoreta que pasó sesenta años solo en el desierto egipcio, sin ver rostro humano hasta que el monje Pafnucio lo encontró poco antes de su muerte y recogió su relato.' },
  { id: 'ciriaco-anacoreta', name: 'San Ciriaco el Anacoreta', day: '09-29', category: ['monje'], century: 'V–VI', place: 'Palestina', biography: 'Monje palestino († 557) que vivió ciento nueve años, los últimos en el desierto de Natufa alimentándose de hierbas amargas que, según su Vida, Dios volvía dulces.' },
  { id: 'metodio-patara', name: 'San Metodio de Patara', day: '06-20', category: ['obispo', 'martir'], century: 'III–IV', place: 'Licia', biography: 'Obispo y mártir († c. 311), autor del Banquete de las diez vírgenes, primer tratado cristiano sobre la virginidad, escrito en forma de diálogo platónico.' },
  { id: 'david-tesalonica', name: 'San David de Tesalónica', day: '06-26', category: ['monje'], century: 'V–VI', place: 'Tesalónica', biography: 'Vivió tres años sobre un almendro, a la intemperie, hasta que un ángel le mandó bajar. Después se recluyó en una celda y fue consejero de la ciudad.' },
  { id: 'sampson-hospedador', name: 'San Sansón el Hospedador', day: '06-27', category: ['justo'], century: 'VI', place: 'Constantinopla', biography: 'Médico romano que repartió su herencia y abrió en Constantinopla un hospital para pobres, sostenido después por Justiniano. Atendía él mismo a los enfermos y no cobraba a nadie.' },

  /* ---------------- Julio ---------------- */
  { id: 'andres-creta', name: 'San Andrés de Creta', day: '07-04', category: ['obispo', 'padre'], century: 'VII–VIII', place: 'Creta', biography: 'Arzobispo de Creta († 740) y creador del canon como forma himnográfica. Su Gran Canon penitencial, de doscientas cincuenta estrofas, se canta entero en la quinta semana de Cuaresma.' },
  { id: 'sergio-german-valaam', name: 'Santos Sergio y Germán de Valaam', day: '06-28', category: ['monje'], century: 'XIV', place: 'Lago Ladoga', biography: 'Fundadores del monasterio de Valaam, en una isla del lago Ladoga, desde donde el monacato ruso alcanzó Carelia y, siglos después, Alaska.' },
  { id: 'tomas-apostol', name: 'Santo Tomás Apóstol', day: '10-06', category: ['apostol'], century: 'I', place: 'India', biography: 'El que exigió ver para creer y confesó al Resucitado con las palabras más rotundas del Evangelio: «Señor mío y Dios mío». Predicó en la India, donde los cristianos de Kerala se llaman aún hoy «cristianos de santo Tomás».' },
  { id: 'euphemia', name: 'Santa Eufemia la Gran Mártir', day: '07-11', category: ['granmartir'], century: 'IV', place: 'Calcedonia', biography: 'Martirizada en Calcedonia el año 303. En el Cuarto Concilio Ecuménico, celebrado sobre su tumba, se depositaron en ella las dos definiciones enfrentadas: según la tradición, la santa retuvo en su mano la ortodoxa y arrojó la otra a sus pies.' },
  { id: 'padres-nicea-julio', name: 'Los Padres de los Seis Concilios', day: '07-13', category: ['obispo'], biography: 'Conmemoración conjunta de los obispos que definieron la fe en los seis primeros concilios ecuménicos, de Nicea a Constantinopla III.' },
  { id: 'marina-antioquia', name: 'Santa Marina de Antioquía', day: '07-17', category: ['granmartir'], century: 'III–IV', place: 'Antioquía de Pisidia', biography: 'Hija de un sacerdote pagano que la repudió al hacerse cristiana. Martirizada muy joven bajo Diocleciano; una de las santas más veneradas del Mediterráneo oriental.' },
  { id: 'macrina-joven', name: 'Santa Macrina la Joven', day: '07-19', category: ['justo'], century: 'IV', place: 'Capadocia', biography: 'Hermana mayor de san Basilio y san Gregorio de Nisa († 379). Convirtió la casa familiar en comunidad monástica y fue la maestra de sus dos hermanos. Gregorio contó su muerte en un diálogo que es a la vez retrato y tratado sobre la resurrección.' },
  { id: 'maria-magdalena', name: 'Santa María Magdalena', fullName: 'Santa María Magdalena, igual a los Apóstoles', day: '07-22', category: ['justo', 'apostol'], century: 'I', place: 'Éfeso', biography: 'La primera en ver al Resucitado y en anunciarlo a los Apóstoles, por lo que la Iglesia la llama «igual a los Apóstoles» y «apóstol de los apóstoles». La tradición la lleva después a Éfeso con san Juan.' },
  { id: 'ana-madre', name: 'Dormición de santa Ana', day: '07-25', category: ['justo'], century: 'I a. C.', biography: 'Madre de la Theotokos. La tradición la recuerda estéril durante años y madre ya anciana, como Sara y como Isabel.' },

  /* ---------------- Agosto ---------------- */
  { id: 'siete-macabeos', name: 'Los siete santos Macabeos', day: '08-01', category: ['martir'], century: 'II a. C.', place: 'Jerusalén', biography: 'Los siete hermanos, su madre Solomonia y el anciano Eleazar, martirizados por negarse a quebrantar la Ley bajo Antíoco Epífanes. La Iglesia los venera como mártires anteriores a Cristo.' },
  { id: 'esteban-hallazgo', name: 'Hallazgo de las reliquias de san Esteban', day: '08-02', category: ['martir'], century: 'V', place: 'Jerusalén', biography: 'Conmemoración del hallazgo, el año 415, de los restos del Protomártir en las afueras de Jerusalén, y de su traslado a Constantinopla.' },
  { id: 'siete-durmientes', name: 'Los siete jóvenes de Éfeso', day: '08-04', category: ['martir'], century: 'III', place: 'Éfeso', biography: 'Siete jóvenes que se refugiaron en una cueva durante la persecución de Decio y, según la tradición, despertaron casi dos siglos después, cuando la ciudad ya era cristiana. Su relato se leía como una parábola de la resurrección.' },
  { id: 'maximo-agosto', name: 'San Máximo el Confesor (traslación)', day: '08-13', category: ['monje', 'confesor', 'padre'], century: 'VII', biography: 'Segunda conmemoración del defensor de las dos voluntades en Cristo, por el traslado de sus reliquias. La principal es el 21 de enero.' },
  { id: 'diomedes', name: 'San Diomedes el Médico', day: '08-16', category: ['martir'], century: 'III–IV', place: 'Nicea', biography: 'Médico de Tarso que ejercía gratuitamente y aprovechaba cada visita para hablar de Cristo; bautizaba él mismo a los que convencía. Fue detenido en Nicea y decapitado bajo Diocleciano. Se le cuenta entre los santos anargiros, los que curaban sin cobrar.' },
  { id: 'tadeo-apostol', name: 'San Tadeo Apóstol', day: '08-21', category: ['apostol'], century: 'I', place: 'Edesa', biography: 'Uno de los Setenta, enviado a Edesa según la tradición del rey Abgar. Allí predicó y, según unos relatos, murió en paz; según otros, mártir en Fenicia.' },
  { id: 'natalia-adrian', name: 'Santos Adrián y Natalia', day: '08-26', category: ['martir'], century: 'IV', place: 'Nicomedia', biography: 'Adrián era oficial de la guardia imperial y se declaró cristiano al ver la entereza de los mártires que custodiaba. Su mujer Natalia lo animó a resistir y recogió después sus restos. Patronos de los matrimonios.' },
  { id: 'moises-etiope', name: 'San Moisés el Etíope', day: '08-28', category: ['monje'], century: 'IV', place: 'Escete, Egipto', biography: 'Fue jefe de una banda de salteadores antes de convertirse y hacerse monje en Escete († c. 405). Cuando los hermanos quisieron juzgar a otro monje, apareció con un cesto agujereado a la espalda: «Mis pecados corren detrás de mí y no los veo, ¿y hoy vengo a juzgar los ajenos?».' },

  /* ---------------- Septiembre ---------------- */
  { id: 'mamas', name: 'San Mamante de Cesarea', day: '09-02', category: ['martir'], century: 'III', place: 'Capadocia', biography: 'Pastor de Capadocia martirizado a los quince años. Muy venerado en Chipre y en toda Anatolia; san Basilio le dedicó una homilía.' },
  { id: 'joaquin-ana', name: 'Santos Joaquín y Ana', day: '09-09', category: ['justo'], century: 'I a. C.', biography: 'Padres de la Theotokos. Se los conmemora al día siguiente de la Natividad de la Virgen, como sinaxis de quienes la engendraron ya ancianos.' },
  { id: 'teodora-alejandria', name: 'Santa Teodora de Alejandría', day: '09-11', category: ['monje'], century: 'V', place: 'Alejandría', biography: 'Se retiró a un monasterio de varones vestida de hombre para hacer penitencia de un adulterio. Cargó durante años con una acusación falsa sin defenderse; sólo al morir se supo quién era.' },
  { id: 'cornelio-centurion', name: 'San Cornelio el Centurión', day: '09-13', category: ['obispo'], century: 'I', place: 'Cesarea', biography: 'El primer pagano bautizado, cuya conversión abrió la Iglesia a las naciones (Hch 10). La tradición lo hace después obispo de Cesarea.' },
  { id: 'nicetas-godo', name: 'San Nicetas el Godo', day: '09-15', category: ['granmartir'], century: 'IV', place: 'Dacia', biography: 'Godo convertido, quemado vivo el año 372 durante la persecución de Atanarico contra los cristianos de su pueblo.' },
  { id: 'sofia-fe-esperanza-caridad', name: 'Santas Fe, Esperanza y Caridad y su madre Sofía', day: '09-17', category: ['martir'], century: 'II', place: 'Roma', biography: 'Tres niñas martirizadas ante su madre bajo Adriano; Sofía murió de dolor tres días después sobre sus tumbas. Sus nombres —Sabiduría, Fe, Esperanza y Caridad— hicieron de ellas una alegoría venerada en todo Oriente.' },
  { id: 'eustaquio', name: 'San Eustaquio Plácidas', day: '09-20', category: ['granmartir'], century: 'II', place: 'Roma', biography: 'General romano convertido al ver un ciervo con una cruz entre la cornamenta. Perdió fortuna, mujer e hijos, los recobró años después y murió con ellos en el martirio bajo Adriano.' },
  { id: 'tecla', name: 'Santa Tecla, igual a los Apóstoles', day: '09-24', category: ['martir'], century: 'I', place: 'Iconio y Seleucia', biography: 'Primera mártir entre las mujeres según la tradición, discípula de san Pablo en Iconio. Sobrevivió al fuego y a las fieras y acabó sus días como anacoreta cerca de Seleucia.' },

  /* ---------------- Octubre ---------------- */
  { id: 'romano-meloda', name: 'San Romano el Meloda', day: '10-01', category: ['justo'], century: 'V–VI', place: 'Constantinopla', biography: 'Diácono sirio de voz áspera y poca letra que, según la tradición, recibió de la Theotokos el don del canto una noche de Navidad. Compuso cerca de mil kontakia; se le atribuye el Himno Akáthistos. Se le conmemora el mismo día que la Protección.' },
  { id: 'ciprian-justina', name: 'Santos Cipriano y Justina', day: '10-02', category: ['martir'], century: 'III', place: 'Antioquía', biography: 'Cipriano era mago y quiso doblegar con sortilegios a la joven Justina; al ver que la señal de la cruz deshacía sus artes, quemó sus libros y se hizo cristiano. Murieron juntos bajo Diocleciano.' },
  { id: 'juan-kukuzelis', name: 'San Juan Kukuzelis', day: '10-01', category: ['monje'], century: 'XIII–XIV', place: 'Monte Athos', biography: 'Cantor de la corte imperial que huyó al Athos para vivir de pastor, hasta que su voz lo delató. Reformó la notación del canto bizantino y su obra sigue siendo la base de la salmodia griega.' },
  { id: 'pelagia', name: 'Santa Pelagia de Antioquía', day: '10-08', category: ['monje'], century: 'V', place: 'Antioquía y Jerusalén', biography: 'Célebre actriz y cortesana de Antioquía que, al oír predicar al obispo Nonno, lo dejó todo y vivió el resto de su vida como recluso en el Monte de los Olivos, sin que nadie supiera que era mujer.' },
  { id: 'padres-nicea-ii', name: 'Los Padres del VII Concilio Ecuménico', day: '10-11', category: ['obispo'], century: 'VIII', place: 'Nicea', biography: 'Los 367 Padres reunidos en Nicea el año 787, que restauraron la veneración de los santos iconos distinguiendo la adoración debida sólo a Dios del honor que se rinde a la imagen.' },
  { id: 'lucas-octubre', name: 'San Lucas Evangelista', day: '10-18', category: ['apostol'], century: 'I', place: 'Antioquía y Beocia', biography: 'Médico antioqueno, compañero de san Pablo y autor del tercer Evangelio y de los Hechos. Escribió lo que nadie más cuenta: la Anunciación, la Visitación, el Magníficat y las parábolas de la misericordia.' },
  { id: 'demetrio-tesalonica-oct', name: 'San Demetrio de Tesalónica', day: '10-26', category: ['granmartir'], century: 'IV', place: 'Tesalónica', biography: 'Mirobléta, «el que mana mirra». Oficial romano martirizado con lanzas en los baños de Tesalónica; su basílica es desde entonces el corazón de la ciudad y su patrono frente a cuantos asedios sufrió.' },
  { id: 'anastasia-romana', name: 'Santa Anastasia la Romana', day: '10-29', category: ['martir'], century: 'III', place: 'Roma', biography: 'Huérfana desde niña, criada en una pequeña comunidad de vírgenes a las afueras de Roma. Denunciada durante la persecución de Decio, se negó a sacrificar a los ídolos y fue martirizada a los veinte años. Es distinta de santa Anastasia de Sirmio, la Libradora de venenos.' },

  /* ---------------- Noviembre ---------------- */
  { id: 'cosme-damian-nov', name: 'Santos Cosme y Damián de Asia', day: '11-01', category: ['justo'], century: 'III', place: 'Asia Menor', biography: 'Hermanos médicos que curaban sin cobrar, de donde el nombre de anargiros, «sin plata». Su madre, santa Teodota, los educó en la fe. Muy invocados por los enfermos en todo el mundo ortodoxo.' },
  { id: 'pablo-confesor', name: 'San Pablo el Confesor', day: '11-06', category: ['obispo', 'confesor'], century: 'IV', place: 'Constantinopla', biography: 'Arzobispo de Constantinopla desterrado cuatro veces por los arrianos y finalmente estrangulado en Armenia con su propio omoforio († c. 350).' },
  { id: 'nectario-noviembre', name: 'San Nectario de Egina', day: '11-09', category: ['obispo'], century: 'XIX–XX', place: 'Egina', biography: 'Metropolita de Pentápolis († 1920), calumniado y apartado del ministerio sin que se le probara nada. Aceptó la humillación en silencio, dio clases a seminaristas pobres y fundó el monasterio de Egina. Canonizado en 1961.' },
  { id: 'juan-limosnero', name: 'San Juan el Limosnero', day: '11-12', category: ['obispo'], century: 'VI–VII', place: 'Alejandría', biography: 'Patriarca de Alejandría († 620) que llamaba «mis señores» a los pobres porque, decía, ellos abren el reino. Repartió la fortuna del patriarcado hasta vaciarla y organizó hospitales y albergues por toda la ciudad.' },
  { id: 'felipe-apostol', name: 'San Felipe Apóstol', day: '11-14', category: ['apostol'], century: 'I', place: 'Hierápolis', biography: 'Uno de los Doce, el que llevó a Natanael ante Cristo. Predicó en Frigia y murió crucificado en Hierápolis. En su fiesta comienza el Ayuno de la Natividad.' },
  { id: 'mateo-evangelista', name: 'San Mateo Evangelista', day: '11-16', category: ['apostol'], century: 'I', place: 'Etiopía', biography: 'Recaudador de impuestos que dejó su mesa al oír «sígueme». Escribió el primer Evangelio, dirigido a los judíos, con el que se abre el Nuevo Testamento.' },
  { id: 'gregorio-neocesarea', name: 'San Gregorio el Taumaturgo', day: '11-17', category: ['obispo', 'padre'], century: 'III', place: 'Neocesarea del Ponto', biography: 'Discípulo de Orígenes y obispo de Neocesarea († c. 270). Cuentan que al llegar sólo había diecisiete cristianos en la ciudad y al morir sólo diecisiete paganos.' },
  { id: 'catalina-alejandria', name: 'Santa Catalina de Alejandría', day: '11-25', category: ['granmartir'], century: 'IV', place: 'Alejandría', biography: 'Joven de familia noble y gran cultura que discutió con los filósofos de la corte y los convenció a todos, según su Vida. Martirizada bajo Majencio. El monasterio del Sinaí lleva su nombre.' },

  /* ---------------- Diciembre ---------------- */
  { id: 'habacuc', name: 'Santo Profeta Habacuc', day: '12-02', category: ['profeta'], century: 'VII a. C.', biography: 'Profeta menor que se atrevió a discutir con Dios por el mal del mundo y recibió por respuesta: «El justo vivirá por su fe». Su cántico forma la cuarta oda de los cánones.' },
  { id: 'barbara', name: 'Santa Bárbara la Gran Mártir', day: '12-04', category: ['granmartir'], century: 'III–IV', place: 'Heliópolis', biography: 'Encerrada por su padre en una torre, mandó abrir en ella una tercera ventana en honor de la Trinidad. Él mismo la denunció y la ejecutó. Patrona de quienes trabajan con explosivos y de la muerte súbita.' },
  { id: 'sabas-santificado', name: 'San Sabas el Santificado', day: '12-05', category: ['monje'], century: 'V–VI', place: 'Palestina', biography: 'Fundador de la Gran Laura del desierto de Judea († 532), el monasterio habitado sin interrupción más antiguo del mundo. De allí salió el Typikon que ordena hasta hoy los oficios bizantinos.' },
  { id: 'ambrosio-milan', name: 'San Ambrosio de Milán', day: '12-07', category: ['obispo', 'padre'], century: 'IV', place: 'Milán', biography: 'Gobernador aclamado obispo por el pueblo cuando ni siquiera estaba bautizado († 397). Se enfrentó a los emperadores, bautizó a san Agustín e introdujo en Occidente el canto de himnos por el pueblo.' },
  { id: 'daniel-estilita', name: 'San Daniel el Estilita', day: '12-11', category: ['monje'], century: 'V', place: 'Constantinopla', biography: 'Discípulo de san Simeón el Estilita; pasó treinta y tres años sobre una columna a las afueras de Constantinopla, aconsejando a emperadores y patriarcas.' },
  { id: 'espiridón-diciembre', name: 'San Espiridón de Trimitonte', day: '12-12', category: ['obispo'], century: 'IV', place: 'Chipre y Corfú', biography: 'Pastor de ovejas hecho obispo, que siguió cuidando su rebaño. En Nicea explicó la Trinidad apretando un ladrillo del que, según el relato, salieron fuego, agua y barro. Sus reliquias incorruptas se veneran en Corfú.' },
  { id: 'eleuterio', name: 'San Eleuterio', day: '12-15', category: ['obispo', 'martir'], century: 'II', place: 'Iliria', biography: 'Obispo de Iliria elevado al episcopado siendo muy joven, según su Vida a los veinte años. Predicó con tal fruto que fue denunciado ante Adriano, y murió mártir junto con su madre Antía, que lo había criado cristiano desde la cuna.' },
  { id: 'ignacio-teoforo-dic', name: 'San Ignacio el Teóforo (traslación)', day: '12-20', category: ['obispo', 'martir'], century: 'I–II', biography: 'Conmemoración del traslado de las reliquias del obispo de Antioquía desde Roma, donde había sido devorado por las fieras, hasta su propia ciudad. Los cristianos recogieron lo que quedó de él y lo llevaron de vuelta como el mayor tesoro de la Iglesia antioquena.' },
  { id: 'anastasia-farmacolitria', name: 'Santa Anastasia la Libradora de venenos', day: '12-22', category: ['granmartir'], century: 'III–IV', place: 'Sirmio', biography: 'Noble romana que dedicó su fortuna a socorrer a los presos por la fe, hasta correr su misma suerte. Su sobrenombre alude a la curación de envenenamientos que se le atribuye.' },
  { id: 'eugenia', name: 'Santa Eugenia de Roma', day: '12-24', category: ['martir'], century: 'III', place: 'Roma y Alejandría', biography: 'Hija del prefecto de Egipto; se hizo monje vestida de hombre y llegó a ser abad sin que nadie lo supiera. Descubierta al ser acusada falsamente, murió mártir en Roma.' },
  { id: 'melania-romana', name: 'Santa Melania la Joven', day: '12-31', category: ['justo'], century: 'IV–V', place: 'Roma y Jerusalén', biography: 'Una de las mujeres más ricas del Imperio († 439). Con su marido Piniano liberó a miles de esclavos y vendió cuanto tenía para fundar monasterios en África y en el Monte de los Olivos, donde murió.' },
];
